package com.indianservers.aiexplorer.phase3.assessment

import com.indianservers.aiexplorer.connectedlearning.ScientificReviewStatus
import com.indianservers.aiexplorer.core.ExactRational
import com.indianservers.aiexplorer.core.SymbolicCasEngine
import com.indianservers.aiexplorer.curriculum.SchoolSubject
import com.indianservers.aiexplorer.learningintelligence.model.*
import kotlin.math.abs
import kotlin.math.log10
import kotlin.math.pow

data class StepScoringRubric(val taskId:String,val criteria:List<StepCriterion>,val maximumMarks:Double,val subject:SchoolSubject,val reviewStatus:ScientificReviewStatus){init{require(maximumMarks>0&&abs(criteria.sumOf{it.marks}-maximumMarks)<1e-8)}}
data class StepCriterion(val id:String,val title:String,val marks:Double,val validatorId:String,val prerequisiteCriterionIds:Set<String>,val errorCategory:LearnerErrorType?)
data class CriterionAttempt(val criterionId:String,val answer:String,val carriedValueFrom:String?=null)
data class CriterionScore(val criterionId:String,val earned:Double,val maximum:Double,val valid:Boolean,val followThrough:Boolean,val feedback:String,val errorCategory:LearnerErrorType?)
data class StepAssessmentResult(val taskId:String,val earnedMarks:Double,val maximumMarks:Double,val firstInvalidCriterionId:String?,val scores:List<CriterionScore>,val suggestedRetry:String)
data class CriterionValidation(val valid:Boolean,val methodValid:Boolean=valid,val safeConclusion:Boolean=true,val feedback:String="",val corrected:String?=null)
fun interface SubjectCriterionValidator{fun validate(criterion:StepCriterion,attempt:CriterionAttempt,prior:Map<String,CriterionScore>):CriterionValidation}

class PartialCreditAssessmentEngine(private val subjectValidators:Map<SchoolSubject,SubjectCriterionValidator>){
 fun score(rubric:StepScoringRubric,attempts:List<CriterionAttempt>):StepAssessmentResult{require(rubric.reviewStatus==ScientificReviewStatus.Verified);val validator=subjectValidators[rubric.subject]?:error("Missing subject-owned validator");val byAttempt=attempts.associateBy{it.criterionId};val scores=mutableListOf<CriterionScore>();rubric.criteria.forEach{criterion->val attempt=byAttempt[criterion.id];val prerequisites=criterion.prerequisiteCriterionIds.mapNotNull{p->scores.singleOrNull{it.criterionId==p}};val validation=if(attempt==null)CriterionValidation(false,false,feedback="Step not attempted")else validator.validate(criterion,attempt,scores.associateBy{it.criterionId});val followThrough=attempt?.carriedValueFrom!=null&&prerequisites.any{!it.valid}&&validation.methodValid;val earned=when{validation.valid->criterion.marks;followThrough&&validation.safeConclusion->criterion.marks*.75;validation.methodValid->criterion.marks*.5;else->0.0};scores+=CriterionScore(criterion.id,earned,criterion.marks,validation.valid,followThrough,validation.feedback,if(validation.valid)null else criterion.errorCategory)};val first=scores.firstOrNull{!it.valid};return StepAssessmentResult(rubric.taskId,scores.sumOf{it.earned},rubric.maximumMarks,first?.criterionId,scores,first?.let{"Retry ${it.criterionId}: ${it.feedback}"}?:"Explain the conclusion independently.")}
}

data class SymbolicValidationResult(val equivalent:Boolean,val domainEquivalent:Boolean,val simplificationTrace:List<String>,val excludedValues:Set<String>,val issueCode:String?)
class SafeSymbolicEquivalenceEngine(private val cas:SymbolicCasEngine=SymbolicCasEngine()){
 fun validate(expected:String,actual:String,variables:Set<String> = setOf("x"),assumptions:Set<String> = emptySet()):SymbolicValidationResult{
  val allowed=Regex("^[0-9A-Za-z_+\\-*/^().,=\\[\\] ]+$");if(!allowed.matches(expected)||!allowed.matches(actual))return SymbolicValidationResult(false,false,emptyList(),emptySet(),"unsupported_symbol")
  val exExpected=excluded(expected);val exActual=excluded(actual);val domain=exExpected==exActual||assumptions.containsAll((exExpected+exActual).map{"$it!=0"});val trace=mutableListOf<String>()
  val trigA=trigCanonical(expected);val trigB=trigCanonical(actual);if(trigA!=null&&trigA==trigB)return SymbolicValidationResult(domain,domain,listOf("Applied a reviewed Pythagorean trigonometric identity."),exExpected+exActual,if(domain)null else "domain_mismatch")
  val matrixA=parseMatrix(expected);val matrixB=parseMatrix(actual);if(matrixA!=null||matrixB!=null){val eq=matrixA!=null&&matrixA==matrixB;return SymbolicValidationResult(eq&&domain,domain,listOf("Compared matrix dimensions and exact entries."),exExpected+exActual,if(eq)null else "matrix_mismatch")}
  return runCatching{val a=cas.parse(normalize(expected));val b=cas.parse(normalize(actual));val ea=cas.simplify(cas.expand(a));val eb=cas.simplify(cas.expand(b));trace+="Expanded and simplified both restricted expression trees.";val samples=listOf(-7L,-3L,-1L,0L,2L,5L,11L);val equivalent=samples.all{s->variables.all{true};val values=variables.associateWith{ExactRational.of(s)};val av=cas.evaluate(ea,values).getOrNull();val bv=cas.evaluate(eb,values).getOrNull();av==null&&bv==null||av!=null&&av==bv};SymbolicValidationResult(equivalent&&domain,domain,trace,exExpected+exActual,when{!domain->"domain_mismatch";!equivalent->"not_equivalent";else->null})}.getOrElse{SymbolicValidationResult(false,false,trace,exExpected+exActual,"parse_error")}
 }
 private fun normalize(s:String)=s.substringAfter('=',s).replace(Regex("(\\d|\\))(?=\\()"),"$1*").replace(Regex("(\\d|\\))(?=[A-Za-z])"),"$1*").replace(" ","")
 private fun excluded(s:String)=Regex("/\\s*\\(?([A-Za-z][A-Za-z0-9_]*(?:[+\\-]\\d+)?)\\)?").findAll(s).map{it.groupValues[1]}.toSet()
 private fun trigCanonical(s:String):String?{val n=s.lowercase().replace(" ","").replace("²","^2");return when(n){"sin(x)^2+cos(x)^2","cos(x)^2+sin(x)^2","1"->"1";"1-tan(x)^2/sec(x)^2","cos(x)^2"->"cos2";else->null}}
 private fun parseMatrix(s:String)=s.replace(" ","").takeIf{it.startsWith("[[")&&it.endsWith("]] ".trim())}?.removePrefix("[[")?.removeSuffix("]] ".trim())?.split("],[")?.map{row->row.split(',').mapNotNull(String::toDoubleOrNull)}
}

enum class BaseDimension{MASS,LENGTH,TIME,TEMPERATURE,AMOUNT,CURRENT,LUMINOUS_INTENSITY}
data class Dimension(val powers:Map<BaseDimension,Int> = emptyMap()){operator fun times(o:Dimension)=Dimension((powers.keys+o.powers.keys).associateWith{(powers[it]?:0)+(o.powers[it]?:0)}.filterValues{it!=0});operator fun div(o:Dimension)=Dimension((powers.keys+o.powers.keys).associateWith{(powers[it]?:0)-(o.powers[it]?:0)}.filterValues{it!=0});fun pow(n:Int)=Dimension(powers.mapValues{it.value*n})}
data class UnitDefinition(val symbol:String,val dimension:Dimension,val scaleToSi:Double,val offsetToSi:Double=0.0)
data class ScientificAnswerValidation(val numericCorrectness:Double,val unitCorrectness:Double,val significantFigureCorrectness:Double,val dimensionalCorrectness:Boolean,val physicallyPlausible:Boolean,val feedback:List<String>)
class ScientificUnitEngine{
 val units=mapOf("kg" to UnitDefinition("kg",Dimension(mapOf(BaseDimension.MASS to 1)),1.0),"g" to UnitDefinition("g",Dimension(mapOf(BaseDimension.MASS to 1)),.001),"m" to UnitDefinition("m",Dimension(mapOf(BaseDimension.LENGTH to 1)),1.0),"cm" to UnitDefinition("cm",Dimension(mapOf(BaseDimension.LENGTH to 1)),.01),"s" to UnitDefinition("s",Dimension(mapOf(BaseDimension.TIME to 1)),1.0),"K" to UnitDefinition("K",Dimension(mapOf(BaseDimension.TEMPERATURE to 1)),1.0),"°C" to UnitDefinition("°C",Dimension(mapOf(BaseDimension.TEMPERATURE to 1)),1.0,273.15),"mol" to UnitDefinition("mol",Dimension(mapOf(BaseDimension.AMOUNT to 1)),1.0),"N" to UnitDefinition("N",Dimension(mapOf(BaseDimension.MASS to 1,BaseDimension.LENGTH to 1,BaseDimension.TIME to -2)),1.0),"J" to UnitDefinition("J",Dimension(mapOf(BaseDimension.MASS to 1,BaseDimension.LENGTH to 2,BaseDimension.TIME to -2)),1.0),"Pa" to UnitDefinition("Pa",Dimension(mapOf(BaseDimension.MASS to 1,BaseDimension.LENGTH to -1,BaseDimension.TIME to -2)),1.0),"M" to UnitDefinition("M",Dimension(mapOf(BaseDimension.AMOUNT to 1,BaseDimension.LENGTH to -3)),1000.0))
 fun validate(expected:Double,expectedUnit:String,actual:String,actualUnit:String,significantFigures:Int?=null,plausible:ClosedFloatingPointRange<Double>?=null):ScientificAnswerValidation{val e=units[expectedUnit];val a=units[actualUnit];val n=actual.toDoubleOrNull();val dimension=e!=null&&a!=null&&e.dimension==a.dimension;val si=n?.let{it*a!!.scaleToSi+a.offsetToSi};val expectedSi=e?.let{expected*it.scaleToSi+it.offsetToSi};val numeric=if(si!=null&&expectedSi!=null&&abs(si-expectedSi)<=maxOf(1e-8,abs(expectedSi)*1e-4))1.0 else 0.0;val sf=significantFigures?.let{if(sigFigs(actual)==it)1.0 else 0.0}?:1.0;val physical=si!=null&&(plausible==null||si in plausible)&&!(expectedUnit=="K"&&si<0);return ScientificAnswerValidation(numeric,if(actualUnit==expectedUnit)1.0 else if(dimension).75 else 0.0,sf,dimension,physical,buildList{if(n==null)add("Enter a valid number.");if(!dimension)add("Unit dimensions do not match.");if(numeric<1)add("Converted numeric value is incorrect.");if(sf<1)add("Significant figures do not match.");if(!physical)add("Value is outside the valid physical domain.")})}
 private fun sigFigs(s:String)=s.lowercase().substringBefore('e').filter(Char::isDigit).dropWhile{it=='0'}.length.coerceAtLeast(1)
}

data class ErrorCluster(val key:String,val entries:List<ErrorBookEntry>,val confidentlyWrong:Int,val dueForRetry:Int,val improvementEvidence:Int)
enum class ErrorBookView{ALL,CONFIDENTLY_WRONG,RECURRING_MISCONCEPTIONS,DUE_FOR_RETRY,IMPROVEMENT_EVIDENCE}
data class WeeklyErrorSummary(val topRecurringError:String?,val mostImprovedMisconception:String?,val conceptsNeedingRepair:List<String>,val suggestedReviewMinutes:Int,val evidence:List<String>)
class AdvancedErrorBookEngine{
 fun clusters(entries:List<ErrorBookEntry>,now:java.time.Instant=java.time.Instant.now())=entries.groupBy{it.misconceptionId?:it.errorType.name}.map{(key,v)->ErrorCluster(key,v,v.count{it.confidence==LearnerConfidence.VERY_SURE},v.count{it.retryAt?.isBefore(now)==true},v.count{it.status in setOf(ErrorBookStatus.IMPROVING,ErrorBookStatus.RESOLVED)})}.sortedByDescending{it.entries.size}
 fun view(entries:List<ErrorBookEntry>,view:ErrorBookView,now:java.time.Instant=java.time.Instant.now())=clusters(entries,now).filter{cluster->when(view){ErrorBookView.ALL->true;ErrorBookView.CONFIDENTLY_WRONG->cluster.confidentlyWrong>0;ErrorBookView.RECURRING_MISCONCEPTIONS->cluster.entries.size>1;ErrorBookView.DUE_FOR_RETRY->cluster.dueForRetry>0;ErrorBookView.IMPROVEMENT_EVIDENCE->cluster.improvementEvidence>0}}
 fun weekly(entries:List<ErrorBookEntry>):WeeklyErrorSummary{val c=clusters(entries);return WeeklyErrorSummary(c.firstOrNull()?.key,c.filter{it.improvementEvidence>0}.maxByOrNull{it.improvementEvidence}?.key,c.filter{it.improvementEvidence<it.entries.size}.map{it.entries.first().conceptId}.distinct().take(4),(c.sumOf{it.dueForRetry}*5).coerceIn(5,30),c.take(3).map{"${it.key}: ${it.entries.size} evidence item(s), ${it.improvementEvidence} improved."})}
}

data class ChallengeDifficultyProfile(val conceptualComplexity:Int,val arithmeticComplexity:Int,val representationComplexity:Int,val numberOfSteps:Int,val readingComplexity:Int,val timePressure:Int)
data class AdaptiveChallenge(val id:String,val conceptId:String,val prompt:String,val profile:ChallengeDifficultyProfile,val validatorId:String,val misconceptionId:String?)
class AdaptiveChallengeGenerator{fun generate(conceptId:String,profile:ChallengeDifficultyProfile,misconceptionId:String?=null,seed:Int=1):AdaptiveChallenge{require(listOf(profile.conceptualComplexity,profile.arithmeticComplexity,profile.representationComplexity,profile.numberOfSteps,profile.readingComplexity,profile.timePressure).all{it in 1..5});val n=(seed*31%9+2);val prompt=when{misconceptionId!=null->"Find and correct the reasoning error ($misconceptionId) in a $conceptId example with value $n.";profile.representationComplexity>=4->"Connect a table, graph and formula for $conceptId using parameter $n.";else->"Solve and justify a $conceptId boundary case using $n; state what remains invariant."};return AdaptiveChallenge("challenge-$conceptId-$seed",conceptId,prompt,profile,"local-$conceptId",misconceptionId)}}
