package com.indianservers.aiexplorer.physics.ncert.experience

import com.indianservers.aiexplorer.curriculum.experience.*
import com.indianservers.aiexplorer.physics.ncert.interaction.PhysicsInteractiveReference

object PhysicsConceptExperiences {
 private fun v(s:String,m:String,u:String,t:String,r:String)=FormulaVariableLink(s,m,u,t,r)
 private fun p(id:String,location:String,input:String,action:String,output:String,why:String,error:String)=ProcessStep(id,location,listOf(input),action,listOf(output),why,error)
 private fun build(id:String,c:AuthoredExperienceCopy)=ConceptExperienceAuthoring.build(PhysicsInteractiveReference.definitions.single{it.activityId==id},c)
 val motion=build("physics-motion-graphs",AuthoredExperienceCopy("Motion · Velocity and acceleration","A moving-object model and two synchronized graphs connect position, velocity, acceleration, and time.",listOf("signed numbers","graph axes","rate of change"),"Velocity is the rate of change of position; acceleration is the rate of change of velocity. With constant acceleration, the velocity-time graph is straight and the position-time graph is curved unless acceleration is zero.","The slope of a position-time graph is velocity, not the height of the graph.","A cyclist starting at 4 m/s and accelerating at 1 m/s² for 8 s reaches 12 m/s and travels 64 m from x₀=0.","If acceleration becomes negative, must the object immediately move backward?","No. Velocity changes gradually; direction reverses only after velocity crosses zero.","Negative acceleration always means motion backward.","Use the braking preset and step through time until velocity crosses zero.","Acceleration describes how velocity changes; direction is set by the sign of velocity.","For v₀=5 m/s, a=2 m/s², find v after 4 s.","13 m/s","v=v₀+at=5+2×4.","Read motion from slopes and signed values, not from a graph's visual height alone.","xt",listOf(v("x","position","m","object","output"),v("v","velocity","m/s","vt","slope of x-t"),v("a","acceleration","m/s²","a","slope of v-t"),v("t","time","s","time","independent variable")),listOf(p("motion-update","track and graphs","x₀, v₀, a and elapsed time","advance the constant-acceleration model","new x and v","Both equations use the same elapsed time.","Do not confuse negative acceleration with negative velocity."))))
 val newton=build("physics-newton-second-law",AuthoredExperienceCopy("Mechanics · Newton's laws","A cart, force vector, and acceleration vector show how net force changes motion for different masses.",listOf("vectors","mass","velocity"),"Newton's second law relates net external force to acceleration. Mass measures inertia, so the same net force produces less acceleration for a larger mass.","The formula uses net force—the vector sum—not merely one force shown in isolation.","A 20 N net force on 5 kg produces 4 m/s²; on 10 kg it produces 2 m/s².","What happens to acceleration if mass doubles at fixed net force?","It halves, and the acceleration vector keeps the net-force direction.","A moving object must have a force in the direction of motion.","Set net force to zero after giving the cart a velocity and distinguish velocity from acceleration.","Zero net force means zero acceleration, not necessarily zero velocity.","What net force gives 3 m/s² to a 4 kg object?","12 N","F=ma=4×3.","Net force determines acceleration; velocity can persist without net force.","force-vector",listOf(v("ΣF","net force","N","force-vector","direct"),v("m","mass","kg","mass","inverse effect on acceleration"),v("a","acceleration","m/s²","acceleration-vector","output"))))
 val waves=build("physics-wave-speed",AuthoredExperienceCopy("Waves and sound · Wave speed","A live wave profile links wavelength, frequency, amplitude, period, phase, and propagation speed.",listOf("oscillation","distance and time","graphs"),"Frequency counts cycles per second and wavelength measures distance per cycle. Their product is distance per second. Amplitude controls displacement size in this ideal linear model.","Changing amplitude does not change wave speed in this model; the medium or chosen f–λ relationship sets speed.","A 3 Hz wave with wavelength 2 m travels at 6 m/s and has period 1/3 s.","At fixed speed, what must happen to wavelength when frequency increases?","Wavelength decreases so fλ remains constant; use paired settings to test this constraint.","Wave particles travel forward with the wave crest.","Follow one position on the profile while changing phase and compare local oscillation with pattern propagation.","The medium's particles oscillate around equilibrium; energy and pattern propagate.","Find the wavelength of a 4 Hz wave travelling at 12 m/s.","3 m","λ=v/f=12/4.","Frequency describes repetition in time; wavelength describes repetition in space.","wave",listOf(v("v","wave speed","m/s","wave","product"),v("f","frequency","Hz","frequency","direct at fixed wavelength"),v("λ","wavelength","m","lambda","inverse at fixed speed"),v("A","amplitude","m","amplitude","independent of speed in this model")),comparisonLabels="time repetition" to "spatial repetition"))
 val circuits=build("physics-electric-circuits",AuthoredExperienceCopy("Electricity · Series and parallel circuits","A battery and two-resistor circuit connect topology to equivalent resistance, current, and power.",listOf("electric current","potential difference","fractions"),"Series components share one current path and their resistances add. Parallel components share the same potential difference and their conductances add, reducing equivalent resistance.","Current transfers energy through components; it is not used up by a resistor.","Two 6 Ω resistors give 12 Ω in series but 3 Ω in parallel. At 12 V the total currents are 1 A and 4 A.","With the same battery and resistors, which topology draws more total current?","Parallel has lower equivalent resistance and therefore greater source current.","A resistor consumes current.","Compare current before and after a resistor conceptually, then inspect power as energy transferred per second.","Charge flow is continuous around a steady series loop; energy is transferred in the component.","Find the current through two 4 Ω resistors in series across 12 V.","1.5 A","Rₑ=8 Ω, so I=12/8.","Topology changes equivalent resistance and energy transfer, not charge conservation.","current",listOf(v("V","supply potential difference","V","battery","direct"),v("Rₑ","equivalent resistance","Ω","r1","inverse effect on current"),v("I","source current","A","current","output"),v("P","power","W","current","VI")),comparisonLabels="series" to "parallel"))
 val optics=build("physics-reflection-refraction",AuthoredExperienceCopy("Optics · Reflection and refraction","A ray diagram links incident, reflected, and refracted rays to the normal and both refractive indices.",listOf("angles","sine","normal to a surface"),"Angles are measured from the normal. Reflection is symmetric about the normal. Refraction follows Snell's law and bends toward the normal on entering a higher refractive index.","A ray does not always bend at a boundary: at normal incidence its direction is unchanged.","For air to glass, a 40° incident ray refracts to a smaller angle while reflecting at 40°.","What happens when light goes from higher to lower refractive index at a large angle?","The refracted angle grows; beyond the critical condition no transmitted solution exists and total internal reflection occurs.","Optical angles are measured from the surface.","Set incidence to 35° and compare the ray with both the normal and boundary.","The labelled angle lies between ray and normal; measuring from the surface gives its complement.","State the reflected angle for 52° incidence.","52°","The law of reflection gives θᵣ=θᵢ, both from the normal.","Measure every optical angle from the normal and use refractive index to predict bending.","normal",listOf(v("θᵢ","incidence angle","degrees","incident","input"),v("θᵣ","reflection angle","degrees","reflected","equal"),v("θ₂","refraction angle","degrees","refracted","Snell relation"),v("n","refractive index","index","normal","controls bending")),comparisonLabels="lower to higher index" to "higher to lower index"))
 val all=listOf(motion,newton,waves,circuits,optics)
}
