package com.indianservers.aiexplorer.phase3.exam

import com.indianservers.aiexplorer.connectedlearning.ScientificReviewStatus
import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.CurriculumQuestionType
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.reference.LearningIntelligenceCatalog
import com.indianservers.aiexplorer.phase3.assessment.StepAssessmentResult
import java.time.Instant

data class InternalChoiceRule(val choose:Int,val fromQuestionIds:List<String>)
data class ExaminationSection(val id:String,val title:String,val marks:Int,val questionCount:Int,val competencyDistribution:Map<CompetencyType,Double>,val allowedQuestionTypes:Set<CurriculumQuestionType>,val internalChoiceRules:List<InternalChoiceRule>)
data class ExaminationManifest(val id:String,val board:EducationBoard,val academicYear:String,val classLevel:SchoolClassLevel,val subject:SchoolSubject,val durationMinutes:Int,val totalMarks:Int,val sections:List<ExaminationSection>,val instructions:List<String>,val reviewStatus:ScientificReviewStatus){init{require(sections.sumOf{it.marks}==totalMarks&&sections.all{abs(it.competencyDistribution.values.sum()-1.0)<.001})}}
data class ExamQuestion(val id:String,val curriculumNodeId:String,val conceptId:String,val sectionId:String,val prompt:String,val marks:Double,val type:CurriculumQuestionType,val original:Boolean=true)
enum class ExamQuestionStatus{UNANSWERED,ANSWERED,MARKED_FOR_REVIEW}
enum class ExamSessionStatus{NOT_STARTED,ACTIVE,PAUSED,SUBMITTED,AUTO_SUBMITTED}
data class ExamResponse(val questionId:String,val answer:String,val confidence:LearnerConfidence?,val savedAt:Instant,val timeSpentSeconds:Int)
data class ExamSession(val id:String,val manifestId:String,val startedAt:Instant?,val remainingSeconds:Int,val status:ExamSessionStatus,val currentQuestionId:String?,val responses:Map<String,ExamResponse> = emptyMap(),val markedForReview:Set<String> = emptySet(),val accommodations:Set<String> = emptySet())
data class ExamAnalytics(val marks:Double,val totalMarks:Double,val sectionPerformance:Map<String,Double>,val competencyPerformance:Map<CompetencyType,Double>,val timeDistribution:Map<String,Int>,val firstInvalidSteps:List<String>,val topicGaps:List<String>,val recommendedRevision:List<String>)

class LocalExamRuntime(private val manifest:ExaminationManifest,private val questions:List<ExamQuestion>,private val pauseAllowed:Boolean=false){
 init{require(manifest.reviewStatus==ScientificReviewStatus.Verified);val concepts=LearningIntelligenceCatalog.concepts.associateBy{it.conceptId};require(questions.all{q->concepts[q.conceptId]?.curriculumNodeId==q.curriculumNodeId&&concepts[q.conceptId]?.subject==manifest.subject});require(questions.all{q->manifest.sections.any{it.id==q.sectionId}})}
 fun newSession(id:String,accommodations:Set<String> = emptySet())=ExamSession(id,manifest.id,null,manifest.durationMinutes*60,ExamSessionStatus.NOT_STARTED,questions.firstOrNull()?.id,accommodations=accommodations)
 fun start(s:ExamSession,now:Instant)=s.copy(startedAt=s.startedAt?:now,status=ExamSessionStatus.ACTIVE)
 fun save(s:ExamSession,response:ExamResponse)=requireActive(s).copy(responses=s.responses+(response.questionId to response))
 fun mark(s:ExamSession,id:String,marked:Boolean)=requireActive(s).copy(markedForReview=if(marked)s.markedForReview+id else s.markedForReview-id)
 fun navigate(s:ExamSession,id:String)=requireActive(s).copy(currentQuestionId=id.also{require(questions.any{q->q.id==it})})
 fun pause(s:ExamSession)=if(pauseAllowed)requireActive(s).copy(status=ExamSessionStatus.PAUSED)else s
 fun tick(s:ExamSession,seconds:Int):ExamSession{if(s.status!=ExamSessionStatus.ACTIVE)return s;val left=(s.remainingSeconds-seconds).coerceAtLeast(0);return s.copy(remainingSeconds=left,status=if(left==0)ExamSessionStatus.AUTO_SUBMITTED else s.status)}
 fun submit(s:ExamSession)=require(s.status in setOf(ExamSessionStatus.ACTIVE,ExamSessionStatus.PAUSED)).let{s.copy(status=ExamSessionStatus.SUBMITTED)}
 fun palette(s:ExamSession)=questions.associate{q->q.id to when{q.id in s.markedForReview->ExamQuestionStatus.MARKED_FOR_REVIEW;q.id in s.responses->ExamQuestionStatus.ANSWERED;else->ExamQuestionStatus.UNANSWERED}}
 fun analytics(s:ExamSession,stepScores:Map<String,StepAssessmentResult>):ExamAnalytics{require(s.status in setOf(ExamSessionStatus.SUBMITTED,ExamSessionStatus.AUTO_SUBMITTED));val marks=questions.sumOf{q->stepScores[q.id]?.earnedMarks?:0.0};val sections=manifest.sections.associate{section->val own=questions.filter{it.sectionId==section.id};section.id to own.sumOf{stepScores[it.id]?.earnedMarks?:0.0}/own.sumOf{it.marks}.coerceAtLeast(1.0)};val gaps=questions.filter{(stepScores[it.id]?.earnedMarks?:0.0)<it.marks*.5}.map{it.conceptId}.distinct();return ExamAnalytics(marks,manifest.totalMarks.toDouble(),sections,emptyMap(),s.responses.mapValues{it.value.timeSpentSeconds},stepScores.values.mapNotNull{it.firstInvalidCriterionId},gaps,gaps.map{"Review $it with one bridge and delayed retry."})}
 private fun requireActive(s:ExamSession)=s.also{require(it.status==ExamSessionStatus.ACTIVE)}
}

object ReferenceExaminations{
 private fun manifest(id:String,level:SchoolClassLevel,subject:SchoolSubject,total:Int,duration:Int)=ExaminationManifest(id,EducationBoard.CBSE_NCERT,"2026-27",level,subject,duration,total,listOf(ExaminationSection("A","Competency and reasoning",total/2,10,mapOf(CompetencyType.UNDERSTANDING to .4,CompetencyType.APPLYING to .6),setOf(CurriculumQuestionType.MULTIPLE_CHOICE,CurriculumQuestionType.NUMERIC_INPUT),emptyList()),ExaminationSection("B","Structured response",total-total/2,5,mapOf(CompetencyType.APPLYING to .5,CompetencyType.ANALYSING to .5),setOf(CurriculumQuestionType.SHORT_ANSWER,CurriculumQuestionType.PROOF_DERIVATION,CurriculumQuestionType.EXPERIMENTAL_REASONING),emptyList())),listOf("Questions are original practice mapped to the active curriculum.","Answers remain hidden until submission."),ScientificReviewStatus.Verified)
 val manifests=listOf(manifest("cbse-10-math",SchoolClassLevel.CLASS_10,SchoolSubject.MATHEMATICS,80,180),manifest("cbse-12-physics",SchoolClassLevel.CLASS_12,SchoolSubject.PHYSICS,70,180),manifest("cbse-12-chemistry",SchoolClassLevel.CLASS_12,SchoolSubject.CHEMISTRY,70,180),manifest("cbse-12-biology",SchoolClassLevel.CLASS_12,SchoolSubject.BIOLOGY,70,180))
 fun originalQuestions(manifest:ExaminationManifest):List<ExamQuestion>{val concepts=LearningIntelligenceCatalog.concepts.filter{it.subject==manifest.subject};return concepts.flatMapIndexed{i,c->listOf(ExamQuestion("${manifest.id}-q${i*2+1}",c.curriculumNodeId,c.conceptId,"A","Select and justify the representation that best tests ${c.conceptId}.",manifest.sections[0].marks.toDouble()/concepts.size,CurriculumQuestionType.MULTIPLE_CHOICE),ExamQuestion("${manifest.id}-q${i*2+2}",c.curriculumNodeId,c.conceptId,"B","Solve an original application of ${c.conceptId}; show method, checks and conclusion.",manifest.sections[1].marks.toDouble()/concepts.size,CurriculumQuestionType.SHORT_ANSWER))}}
}

enum class VivaDomain{PHYSICS_PRACTICAL,CHEMISTRY_PRACTICAL,BIOLOGY_PRACTICAL,MATHEMATICS_REASONING,DIAGRAM_INTERPRETATION,EXPERIMENT_DESIGN}
data class VivaQuestion(val id:String,val conceptId:String,val prompt:String,val followUp:String?,val expectedTerms:Set<String>,val safetyTerms:Set<String> = emptySet())
data class VivaRubric(val conceptAccuracy:Double,val reasoning:Double,val terminology:Double,val safetyAwareness:Double,val independence:Double,val communication:Double){init{require(abs(listOf(conceptAccuracy,reasoning,terminology,safetyAwareness,independence,communication).sum()-1.0)<.001)}}
data class VivaScore(val total:Double,val components:Map<String,Double>,val followUpQuestion:String?,val feedback:List<String>)
class LocalVivaEngine{fun score(question:VivaQuestion,response:String,rubric:VivaRubric,hints:Int):VivaScore{val words=response.lowercase().split(Regex("\\W+")).toSet();val term=question.expectedTerms.count{it.lowercase() in words}.toDouble()/question.expectedTerms.size.coerceAtLeast(1);val safety=if(question.safetyTerms.isEmpty())1.0 else question.safetyTerms.count{it.lowercase() in words}.toDouble()/question.safetyTerms.size;val reasoning=if(listOf("because","therefore","so","evidence").any{it in words})1.0 else .5;val independence=(1.0-hints*.2).coerceAtLeast(0.0);val communication=if(response.length>=20)1.0 else .5;val concept=term;val components=mapOf("concept" to concept,"reasoning" to reasoning,"terminology" to term,"safety" to safety,"independence" to independence,"communication" to communication);val weights=listOf(rubric.conceptAccuracy,rubric.reasoning,rubric.terminology,rubric.safetyAwareness,rubric.independence,rubric.communication);val total=components.values.zip(weights).sumOf{it.first*it.second};return VivaScore(total,components,question.followUp?.takeIf{total<.8},buildList{if(term<1)add("Use the reviewed scientific terminology.");if(reasoning<1)add("Connect the claim to evidence with because or therefore.");if(safety<1)add("Include the required safety principle.")})}}

data class CapabilityEvidence(val capability:String,val independent:Int,val assisted:Int,val delayed:Int,val lastAt:Instant?)
data class EvidenceProgressReport(val learnerId:String,val mastered:List<String>,val proficient:List<String>,val learning:List<String>,val dueReviews:List<String>,val weakPrerequisites:List<String>,val misconceptions:List<String>,val capabilities:List<CapabilityEvidence>,val confidenceNote:String,val examReadiness:String,val nextActions:List<String>,val limitation:String?)
class EvidenceReportEngine{fun create(learnerId:String,states:List<LearnerConceptState>,now:Instant=Instant.now()):EvidenceProgressReport{val capabilities=MasteryEvidenceType.entries.map{type->val e=states.flatMap{it.masteryEvidence}.filter{it.type==type};CapabilityEvidence(type.name,e.count{it.independence>=.7},e.count{it.independence<.7},e.count{it.type==MasteryEvidenceType.DELAYED_RETRIEVAL},e.maxOfOrNull{it.occurredAt})}.filter{it.independent+it.assisted>0};val evidenceCount=states.sumOf{it.masteryEvidence.size};return EvidenceProgressReport(learnerId,states.filter{it.masteryState==ConceptMasteryState.MASTERED}.map{it.conceptId},states.filter{it.masteryState==ConceptMasteryState.PROFICIENT}.map{it.conceptId},states.filter{it.masteryState in setOf(ConceptMasteryState.LEARNING,ConceptMasteryState.PRACTISING)}.map{it.conceptId},states.filter{it.nextReviewAt?.isBefore(now)==true}.map{it.conceptId},emptyList(),states.flatMap{it.misconceptionEvidence}.filter{!it.resolved}.map{it.misconceptionId}.distinct(),capabilities,"Calibration uses ${states.sumOf{it.confidenceSummary.observations}} confidence observations.",if(evidenceCount<10)"Insufficient evidence for a precise readiness estimate." else "Readiness is based on independent, diverse and delayed evidence.",states.filter{it.masteryState==ConceptMasteryState.NEEDS_REVIEW}.map{"Review ${it.conceptId}"}.take(3),if(evidenceCount<5)"Early report: collect more diverse evidence." else null)}}
private fun abs(v:Double)=kotlin.math.abs(v)
