package com.indianservers.aiexplorer.physics.ncert.interaction

import com.indianservers.aiexplorer.curriculum.SchoolClassLevel.*
import com.indianservers.aiexplorer.curriculum.SchoolSubject
import com.indianservers.aiexplorer.curriculum.interaction.*
import kotlin.math.*

object PhysicsInteractiveReference {
 private fun c(i:String,l:String,n:Double,x:Double,s:Double,v:Double,u:String)=ActivityControl(i,l,n,x,s,v,u)
 private fun ch(i:String,t:String,f:(VisualState)->Boolean)=ActivityChallenge(i,t,t,t,f)
 private fun vs(v:Map<String,Double>,u:Map<String,String>,l:Map<String,String>,p:List<PlotPoint>,e:String,part:String)=VisualState(v,u,l,p,listOf("Predict the response.","Change a variable and compare visual, graph, formula, and units.","Record an evidence-based observation."),e,"${l.values.joinToString()}. $e",part)
 private fun a(id:String,title:String,concept:String,levels:Set<com.indianservers.aiexplorer.curriculum.SchoolClassLevel>,objective:String,formula:String,controls:List<ActivityControl>,presets:List<ActivityPreset>,parts:List<DiagramPart>,compute:(Map<String,Double>)->VisualState,challenges:List<ActivityChallenge>)=ActivityDefinition(id,concept,SchoolSubject.PHYSICS,levels,title,listOf(objective),listOf("Make a prediction.","Manipulate at least two controls.","Inspect the graph/vector/measurement and explain the relationship.","Complete a challenge."),controls,presets,challenges,formula,listOf("Idealised school-level model; stated losses are neglected.","SI units are used unless a control states otherwise."),parts,ActivityAccessibility("Vectors, rays, graph points and measured values have a step-by-step text equivalent."),compute)

 val motionGraphs=a("physics-motion-graphs","Motion Graph Studio","physics-motion",setOf(CLASS_7,CLASS_9,CLASS_11),"Link initial velocity and constant acceleration to position-time and velocity-time graphs.","x = x₀ + v₀t + 1/2 at²; v = v₀ + at",
  listOf(c("x0","Initial position",-20.0,20.0,1.0,0.0,"m"),c("v0","Initial velocity",-10.0,20.0,.5,4.0,"m/s"),c("a","Acceleration",-5.0,5.0,.25,1.0,"m/s²"),c("time","Time",1.0,20.0,.5,8.0,"s")),listOf(ActivityPreset("uniform","Uniform",mapOf("x0" to 0.0,"v0" to 5.0,"a" to 0.0,"time" to 10.0)),ActivityPreset("brake","Braking",mapOf("x0" to 0.0,"v0" to 12.0,"a" to -2.0,"time" to 6.0))),listOf(DiagramPart("object","moving object","position on track"),DiagramPart("xt","position-time graph","sampled trajectory"),DiagramPart("vt","velocity-time graph","straight-line velocity")),
  {q->val t=q.getValue("time");val x=q.getValue("x0")+q.getValue("v0")*t+.5*q.getValue("a")*t*t;val v=q.getValue("v0")+q.getValue("a")*t;val pts=(0..20).flatMap{j->val z=t*j/20;listOf(PlotPoint(z,q.getValue("x0")+q.getValue("v0")*z+.5*q.getValue("a")*z*z,"position"),PlotPoint(z,q.getValue("v0")+q.getValue("a")*z,"velocity"))};vs(q+mapOf("position" to x,"velocity" to v),mapOf("x0" to "m","v0" to "m/s","a" to "m/s²","time" to "s","position" to "m","velocity" to "m/s"),mapOf("state" to "At ${t}s: x=${"%.2f".format(x)} m, v=${"%.2f".format(v)} m/s","graph" to "Position curve slope equals velocity; velocity graph slope equals acceleration."),pts,"Constant acceleration bends x-t into a parabola and keeps v-t linear.","xt")},listOf(ch("stop","Make final velocity zero"){near(it.values["velocity"],0.0,.01)},ch("x50","Reach x = 50 m"){near(it.values["position"],50.0,.05)},ch("reverse","Finish with negative velocity"){(it.values["velocity"]?:0.0)<0}))

 val newton=a("physics-newton-second-law","Newton's Second Law Lab","physics-newton-second-law",setOf(CLASS_8,CLASS_9,CLASS_11),"Relate net force, mass, acceleration, and force-vector direction.","ΣF = ma; a = ΣF/m",
  listOf(c("force","Net force",-50.0,50.0,1.0,20.0,"N"),c("mass","Mass",1.0,20.0,.5,5.0,"kg"),c("duration","Force duration",.5,10.0,.5,3.0,"s")),listOf(ActivityPreset("same-force","20 N on 5 kg",mapOf("force" to 20.0,"mass" to 5.0,"duration" to 3.0)),ActivityPreset("heavy","20 N on 10 kg",mapOf("force" to 20.0,"mass" to 10.0,"duration" to 3.0))),listOf(DiagramPart("cart","cart","object receiving net force"),DiagramPart("force-vector","force vector","signed net-force arrow"),DiagramPart("acceleration-vector","acceleration vector","same-direction acceleration arrow")),
  {q->val a=q.getValue("force")/q.getValue("mass");val v=a*q.getValue("duration");vs(q+mapOf("acceleration" to a,"deltaVelocity" to v),mapOf("force" to "N","mass" to "kg","duration" to "s","acceleration" to "m/s²","deltaVelocity" to "m/s"),mapOf("result" to "a=${"%.2f".format(a)} m/s²; Δv=${"%.2f".format(v)} m/s","direction" to if(a>=0)"force and acceleration point right" else "force and acceleration point left"),listOf(PlotPoint(0.0,0.0),PlotPoint(q.getValue("force"),a,"F-a")),"For fixed mass, acceleration is proportional to net force; for fixed force it is inversely proportional to mass.","force-vector")},listOf(ch("a4","Make acceleration 4 m/s²"){near(it.values["acceleration"],4.0,.01)},ch("aMinus2","Make acceleration -2 m/s²"){near(it.values["acceleration"],-2.0,.01)},ch("dv10","Make Δv = 10 m/s"){near(it.values["deltaVelocity"],10.0,.01)}))

 val wave=a("physics-wave-speed","Wave Speed Explorer","physics-wave-speed",setOf(CLASS_8,CLASS_9,CLASS_11),"Connect frequency and wavelength to propagation speed while separating amplitude from speed.","v = fλ",
  listOf(c("frequency","Frequency",.5,20.0,.5,3.0,"Hz"),c("wavelength","Wavelength",.25,10.0,.25,2.0,"m"),c("amplitude","Amplitude",.1,3.0,.1,1.0,"m"),c("phase","Phase",0.0,6.28,.1,0.0,"rad")),listOf(ActivityPreset("six","6 m/s wave",mapOf("frequency" to 3.0,"wavelength" to 2.0,"amplitude" to 1.0)),ActivityPreset("short","Short wavelength",mapOf("frequency" to 8.0,"wavelength" to .75,"amplitude" to .5))),listOf(DiagramPart("wave","wave profile","displacement against distance"),DiagramPart("lambda","wavelength marker","crest-to-crest distance"),DiagramPart("amplitude","amplitude marker","equilibrium-to-crest distance")),
  {q->val f=q.getValue("frequency");val l=q.getValue("wavelength");val amp=q.getValue("amplitude");val pts=(0..80).map{j->val x=l*2*j/80;PlotPoint(x,amp*sin(2*PI*x/l+q.getValue("phase")),"wave")};vs(q+mapOf("speed" to f*l,"period" to 1/f),mapOf("frequency" to "Hz","wavelength" to "m","amplitude" to "m","phase" to "rad","speed" to "m/s","period" to "s"),mapOf("result" to "v=${"%.2f".format(f*l)} m/s","shape" to "λ=$l m, amplitude=$amp m"),pts,"Frequency counts oscillations per second; wavelength is distance per oscillation. Amplitude changes height, not v in this model.","wave")},listOf(ch("v6","Create v = 6 m/s"){near(it.values["speed"],6.0,.01)},ch("periodHalf","Create period 0.5 s"){near(it.values["period"],.5,.01)},ch("v10","Create v = 10 m/s"){near(it.values["speed"],10.0,.01)}))

 val circuits=a("physics-electric-circuits","Series/Parallel Circuit Lab","physics-electric-circuits",setOf(CLASS_7,CLASS_10,CLASS_12),"Compare equivalent resistance, current, and power in series and parallel resistor circuits.","Series: Rₑ=R₁+R₂; parallel: 1/Rₑ=1/R₁+1/R₂; I=V/Rₑ; P=VI",
  listOf(c("voltage","Supply voltage",1.0,24.0,.5,6.0,"V"),c("r1","R₁",1.0,30.0,1.0,6.0,"Ω"),c("r2","R₂",1.0,30.0,1.0,6.0,"Ω"),c("parallel","Topology: 0 series, 1 parallel",0.0,1.0,1.0,0.0,"mode")),listOf(ActivityPreset("series","Two in series",mapOf("voltage" to 12.0,"r1" to 6.0,"r2" to 6.0,"parallel" to 0.0)),ActivityPreset("parallel","Two in parallel",mapOf("voltage" to 12.0,"r1" to 6.0,"r2" to 6.0,"parallel" to 1.0))),listOf(DiagramPart("battery","battery","voltage source"),DiagramPart("r1","resistor one","first load"),DiagramPart("r2","resistor two","second load"),DiagramPart("current","current path","conventional current direction")),
  {q->val par=q.getValue("parallel")>=.5;val r=if(par)q.getValue("r1")*q.getValue("r2")/(q.getValue("r1")+q.getValue("r2")) else q.getValue("r1")+q.getValue("r2");val i=q.getValue("voltage")/r;vs(q+mapOf("equivalentResistance" to r,"current" to i,"power" to q.getValue("voltage")*i),mapOf("voltage" to "V","r1" to "Ω","r2" to "Ω","parallel" to "mode","equivalentResistance" to "Ω","current" to "A","power" to "W"),mapOf("topology" to if(par)"parallel branches" else "single series loop","result" to "Rₑ=${"%.2f".format(r)} Ω, I=${"%.2f".format(i)} A"),listOf(PlotPoint(0.0,q.getValue("voltage")),PlotPoint(r,i,"operating point")),"Series resistances add along one path; parallel branches increase conductance. The current and brightness proxy respond immediately.","current")},listOf(ch("i1","Create current 1 A"){near(it.values["current"],1.0,.01)},ch("r3","Create equivalent resistance 3 Ω"){near(it.values["equivalentResistance"],3.0,.01)},ch("p24","Create power 24 W"){near(it.values["power"],24.0,.05)}))

 val optics=a("physics-reflection-refraction","Reflection and Refraction Ray Lab","physics-reflection-refraction",setOf(CLASS_7,CLASS_8,CLASS_10,CLASS_12),"Manipulate incidence and refractive indices to verify reflection and Snell's law.","θᵣ = θᵢ; n₁ sin θ₁ = n₂ sin θ₂",
  listOf(c("incidence","Angle of incidence",0.0,80.0,1.0,35.0,"degrees"),c("n1","Refractive index 1",1.0,2.5,.05,1.0,"index"),c("n2","Refractive index 2",1.0,2.5,.05,1.5,"index")),listOf(ActivityPreset("air-glass","Air to glass",mapOf("incidence" to 40.0,"n1" to 1.0,"n2" to 1.5)),ActivityPreset("glass-air","Glass to air",mapOf("incidence" to 35.0,"n1" to 1.5,"n2" to 1.0))),listOf(DiagramPart("incident","incident ray","incoming ray"),DiagramPart("reflected","reflected ray","symmetric about normal"),DiagramPart("refracted","refracted ray","transmitted ray"),DiagramPart("normal","normal","perpendicular reference line")),
  {q->val i=Math.toRadians(q.getValue("incidence"));val ratio=q.getValue("n1")*sin(i)/q.getValue("n2");val tir=ratio>1;val refr=if(tir)Double.NaN else Math.toDegrees(asin(ratio));val pts=listOf(PlotPoint(-sin(i),-cos(i),"incident"),PlotPoint(0.0,0.0,"boundary"),PlotPoint(sin(i),-cos(i),"reflected"))+(if(tir)emptyList() else listOf(PlotPoint(sin(Math.toRadians(refr)),cos(Math.toRadians(refr)),"refracted")));vs(q+mapOf("reflectionAngle" to q.getValue("incidence"),"refractionAngle" to refr,"totalInternalReflection" to if(tir)1.0 else 0.0),mapOf("incidence" to "°","n1" to "index","n2" to "index","reflectionAngle" to "°","refractionAngle" to "°","totalInternalReflection" to "boolean"),mapOf("reflection" to "θᵣ=${q["incidence"]}°","refraction" to if(tir)"total internal reflection: no transmitted ray" else "θ₂=${"%.2f".format(refr)}°"),pts,"Reflection preserves angle about the normal. Refraction bends toward the normal on entering the higher-index medium; TIR occurs only when the sine solution is impossible.",if(tir)"reflected" else "refracted")},listOf(ch("refl45","Reflect at 45°"){near(it.values["reflectionAngle"],45.0,.01)},ch("normal","No bending at normal incidence"){near(it.values["incidence"],0.0,.01)},ch("tir","Produce total internal reflection"){near(it.values["totalInternalReflection"],1.0,.01)}))

 val definitions=listOf(motionGraphs,newton,wave,circuits,optics)
 fun create(id:String)=FunctionalInteractiveActivity(definitions.single{it.activityId==id})
}
