package com.indianservers.aiexplorer.phase3.governance

import com.indianservers.aiexplorer.connectedlearning.ScientificReviewStatus
import com.indianservers.aiexplorer.curriculum.CurriculumSourceReference
import com.indianservers.aiexplorer.curriculum.SchoolSubject
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.reference.LearningIntelligenceCatalog
import com.indianservers.aiexplorer.phase3.assessment.*
import java.time.Instant

enum class ReviewStatus{NOT_REVIEWED,IN_REVIEW,APPROVED,REJECTED}
enum class AiInvolvementStatus{NONE,AI_ASSISTED_DRAFT,AI_GENERATED_HUMAN_REVIEWED,AI_TRANSLATED_HUMAN_REVIEWED,LOCALLY_GENERATED_VERIFIED_TEMPLATE,EXTERNAL_RUNTIME_RESPONSE}
data class ContentLineage(val contentId:String,val curriculumNodeIds:Set<String>,val sourceReferences:List<CurriculumSourceReference>,val academicYear:String?,val contentOwner:String,val authorIds:List<String>,val reviewerIds:List<String>,val scientificReviewStatus:ScientificReviewStatus,val accessibilityReviewStatus:ReviewStatus,val lastReviewedAt:Instant?,val version:String,val aiInvolvement:AiInvolvementStatus)
object ContentLineageRegistry{
 val records:List<ContentLineage> by lazy{LearningIntelligenceCatalog.concepts.flatMap{c->listOf(ContentLineage(c.conceptId,setOf(c.curriculumNodeId),emptyList(),"2026-27",c.subject.name,listOf("subject-team"),listOf("scientific-review"),ScientificReviewStatus.Verified,ReviewStatus.APPROVED,Instant.parse("2026-07-19T00:00:00Z"),"1.0.0",AiInvolvementStatus.NONE))+c.activityId?.let{listOf(ContentLineage(it,setOf(c.curriculumNodeId),emptyList(),"2026-27",c.subject.name,listOf("subject-team"),listOf("scientific-review","accessibility-review"),ScientificReviewStatus.Verified,ReviewStatus.APPROVED,Instant.parse("2026-07-19T00:00:00Z"),"1.0.0",AiInvolvementStatus.NONE))}.orEmpty()}}
 fun learnerSummary(id:String)=records.singleOrNull{it.contentId==id}?.let{"${it.contentOwner.lowercase().replaceFirstChar(Char::uppercase)} content · ${it.scientificReviewStatus} · version ${it.version}"}
 fun validateReleased(ids:Set<String>)=ids.filter{released->records.none{it.contentId==released&&it.scientificReviewStatus==ScientificReviewStatus.Verified&&it.accessibilityReviewStatus==ReviewStatus.APPROVED}}
}

enum class ReviewStage{DRAFT,CONTENT_REVIEW,CURRICULUM_REVIEW,SCIENTIFIC_REVIEW,MATHEMATICAL_REVIEW,PRACTICAL_SAFETY_REVIEW,ACCESSIBILITY_REVIEW,TECHNICAL_REVIEW,VERIFIED,RELEASED,NEEDS_REVISION,ARCHIVED}
enum class ReviewAssetType{LESSON,FORMULA,DIAGRAM,SIMULATION,QUESTION,PRACTICAL,EXPERIMENT,TRANSLATION,TUTOR_FLOW,PRACTICE_TEMPLATE,ACCESSIBILITY_NARRATION,AR_MODEL}
data class ReviewComment(val id:String,val reviewerRole:String,val text:String,val blocking:Boolean,val createdAt:Instant)
data class ReviewRecord(val assetId:String,val type:ReviewAssetType,val assignedRole:String?,val stage:ReviewStage,val completedStages:Set<ReviewStage>,val comments:List<ReviewComment>,val versionHistory:List<String>,val validationResults:Map<String,Boolean>)
class ScientificReviewConsole{
 fun requestChanges(r:ReviewRecord,comment:ReviewComment)=r.copy(stage=ReviewStage.NEEDS_REVISION,comments=r.comments+comment)
 fun approveStage(r:ReviewRecord,stage:ReviewStage)=r.copy(stage=stage,completedStages=r.completedStages+stage)
 fun canRelease(r:ReviewRecord,masteryCritical:Boolean):Boolean{val required=buildSet{addAll(setOf(ReviewStage.CONTENT_REVIEW,ReviewStage.CURRICULUM_REVIEW,ReviewStage.ACCESSIBILITY_REVIEW,ReviewStage.TECHNICAL_REVIEW));if(r.type in setOf(ReviewAssetType.FORMULA,ReviewAssetType.SIMULATION,ReviewAssetType.PRACTICAL))add(ReviewStage.SCIENTIFIC_REVIEW);if(r.type==ReviewAssetType.FORMULA)add(ReviewStage.MATHEMATICAL_REVIEW);if(r.type==ReviewAssetType.PRACTICAL)add(ReviewStage.PRACTICAL_SAFETY_REVIEW)};return (!masteryCritical||r.completedStages.containsAll(required))&&r.comments.none{it.blocking}&&r.validationResults.values.all{it}}
 fun release(r:ReviewRecord,masteryCritical:Boolean)=if(canRelease(r,masteryCritical))r.copy(stage=ReviewStage.RELEASED)else r.copy(stage=ReviewStage.NEEDS_REVISION)
}

data class SemanticVersion(val major:Int,val minor:Int,val patch:Int):Comparable<SemanticVersion>{override fun compareTo(other:SemanticVersion)=compareValuesBy(this,other,SemanticVersion::major,SemanticVersion::minor,SemanticVersion::patch);override fun toString()="$major.$minor.$patch"}
enum class ContentMigrationType{METADATA_UPDATE,EXPLANATION_UPDATE,FORMULA_CORRECTION,DIAGRAM_CORRECTION,CONCEPT_SPLIT,CONCEPT_MERGE,CURRICULUM_RECLASSIFICATION,ASSESSMENT_UPDATE,SIMULATION_MODEL_CHANGE,REMOVED_FROM_CURRENT_SYLLABUS}
data class VersionedContentIdentity(val stableId:String,val version:SemanticVersion,val previousVersion:SemanticVersion?,val migrationType:ContentMigrationType)
data class ContentMigrationPlan(val identity:VersionedContentIdentity,val targetConceptIds:List<String>,val evidenceAllocation:Map<String,Double>,val reasoning:String)
data class MigrationOutcome(val states:List<LearnerConceptState>,val archivedConceptIds:Set<String>,val notesPreserved:Boolean,val reasoning:String)
class ContentMigrationEngine{
 fun migrate(source:LearnerConceptState,plan:ContentMigrationPlan):MigrationOutcome{require(plan.identity.stableId==source.conceptId);return when(plan.identity.migrationType){ContentMigrationType.CONCEPT_SPLIT->{require(plan.targetConceptIds.size>=2&&plan.evidenceAllocation.keys.containsAll(plan.targetConceptIds));val children=plan.targetConceptIds.map{id->val share=plan.evidenceAllocation.getValue(id).coerceIn(0.0,1.0);source.copy(conceptId=id,masteryState=when{share>=.8&&source.masteryState==ConceptMasteryState.MASTERED->ConceptMasteryState.PROFICIENT;share>0->ConceptMasteryState.LEARNING;else->ConceptMasteryState.NOT_STARTED},masteryEvidence=source.masteryEvidence.filterIndexed{index,_->index.toDouble()/source.masteryEvidence.size.coerceAtLeast(1)<share}.map{it.copy(id="${it.id}-$id",conceptId=id)})};MigrationOutcome(children,emptySet(),true,plan.reasoning)};ContentMigrationType.REMOVED_FROM_CURRENT_SYLLABUS->MigrationOutcome(listOf(source),setOf(source.conceptId),true,plan.reasoning);else->MigrationOutcome(listOf(source),emptySet(),true,plan.reasoning)}}
}

data class CounterexampleDefinition(val claimId:String,val domainConstraints:List<String>,val generatorId:String,val explanationId:String,val reviewStatus:ScientificReviewStatus)
data class Counterexample(val claimId:String,val example:String,val explanation:String,val boundary:Boolean)
object AuthoredCounterexampleEngine{
 val definitions=listOf("math-multiply-always-larger","math-larger-denominator","math-continuous-differentiable","physics-heavy-falls-faster","physics-current-consumed","chem-catalyst-equilibrium","bio-dominant-common","bio-arteries-oxygen").map{CounterexampleDefinition(it,listOf("reviewed domain"),"local-$it","explain-$it",ScientificReviewStatus.Verified)}
 fun generate(claimId:String)=when(claimId){"math-multiply-always-larger"->Counterexample(claimId,"8 × 1/2 = 4","Multiplication by a positive fraction below one reduces a positive number.",false);"math-larger-denominator"->Counterexample(claimId,"1/8 < 1/3","For equal numerators, more equal parts make each part smaller.",false);"math-continuous-differentiable"->Counterexample(claimId,"f(x)=|x| at x=0","The function is continuous at zero but has unequal one-sided slopes.",true);"physics-heavy-falls-faster"->Counterexample(claimId,"A hammer and feather in vacuum","Without air resistance, both have the same gravitational acceleration.",false);"physics-current-consumed"->Counterexample(claimId,"Current before and after a series resistor is equal","Energy transfers; steady charge flow is conserved.",false);"chem-catalyst-equilibrium"->Counterexample(claimId,"Catalysed and uncatalysed systems reach the same equilibrium","A catalyst changes rates, not equilibrium composition.",false);"bio-dominant-common"->Counterexample(claimId,"A rare allele can be dominant","Dominance describes heterozygous expression, not frequency.",false);"bio-arteries-oxygen"->Counterexample(claimId,"Pulmonary artery carries oxygen-poor blood","Arteries are defined by flow away from the heart.",false);else->error("Unreviewed claim")}
}

sealed interface DimensionExpression{data class Variable(val id:String):DimensionExpression;data class Product(val left:DimensionExpression,val right:DimensionExpression):DimensionExpression;data class Quotient(val numerator:DimensionExpression,val denominator:DimensionExpression):DimensionExpression;data class Power(val base:DimensionExpression,val exponent:Int):DimensionExpression;data object Dimensionless:DimensionExpression}
data class ScientificFormulaDefinition(val id:String,val subject:SchoolSubject,val left:DimensionExpression,val right:DimensionExpression,val variables:Map<String,Dimension>,val verified:Boolean,val empirical:Boolean=false,val empiricalNote:String?=null)
data class DimensionalValidationResult(val formulaId:String,val valid:Boolean,val left:Dimension?,val right:Dimension?,val issues:List<String>)
class DimensionalConsistencyValidator{
 fun validate(f:ScientificFormulaDefinition):DimensionalValidationResult{fun resolve(e:DimensionExpression):Dimension?{return when(e){is DimensionExpression.Variable->f.variables[e.id];is DimensionExpression.Product->{val left=resolve(e.left);val right=resolve(e.right);if(left==null||right==null)null else left*right};is DimensionExpression.Quotient->{val left=resolve(e.numerator);val right=resolve(e.denominator);if(left==null||right==null)null else left/right};is DimensionExpression.Power->resolve(e.base)?.pow(e.exponent);DimensionExpression.Dimensionless->Dimension()}};val l=resolve(f.left);val r=resolve(f.right);val issues=buildList{if(l==null||r==null)add("Undefined variable dimension.");if(l!=null&&r!=null&&l!=r&&!f.empirical)add("Left and right dimensions differ.");if(f.empirical&&f.empiricalNote.isNullOrBlank())add("Empirical formula needs an explicit note.")};return DimensionalValidationResult(f.id,issues.isEmpty(),l,r,issues)}
 fun validateVerified(formulas:List<ScientificFormulaDefinition>)=formulas.filter{it.verified}.map(::validate).filter{!it.valid}
}

data class AccessibilityDefinition(val contentId:String,val contentDescription:String?,val stateNarration:String?,val controlLabels:List<String>,val logicalFocusOrder:Boolean,val keyboardOrDpad:Boolean,val minimumTouchTargetDp:Int,val reducedMotion:Boolean,val highContrast:Boolean,val colourIndependent:Boolean,val nonAnimatedAlternative:Boolean,val dynamicStateSemantics:Boolean,val semanticsTests:Boolean)
data class AccessibilityReleaseResult(val contentId:String,val passed:Boolean,val missingRequirements:List<String>,val warnings:List<String>)
object AccessibilityReleaseGate{fun evaluate(d:AccessibilityDefinition):AccessibilityReleaseResult{val missing=buildList{if(d.contentDescription.isNullOrBlank())add("content description");if(d.stateNarration.isNullOrBlank())add("current-state narration");if(d.controlLabels.isEmpty())add("control labels");if(!d.logicalFocusOrder)add("logical focus order");if(d.minimumTouchTargetDp<48)add("48dp touch targets");if(!d.reducedMotion)add("reduced-motion mode");if(!d.highContrast)add("high-contrast mode");if(!d.colourIndependent)add("colour-independent meaning");if(!d.nonAnimatedAlternative)add("non-animated alternative");if(!d.dynamicStateSemantics)add("dynamic-state semantics");if(!d.semanticsTests)add("automated semantics tests")};return AccessibilityReleaseResult(d.contentId,missing.isEmpty(),missing,if(!d.keyboardOrDpad)listOf("Keyboard/D-pad alternative should be added where practical.")else emptyList())}}
