package com.indianservers.aiexplorer.learning.ncert.interaction

import com.indianservers.aiexplorer.curriculum.SchoolClassLevel.*
import com.indianservers.aiexplorer.curriculum.SchoolSubject
import com.indianservers.aiexplorer.curriculum.interaction.*
import kotlin.math.*

object MathematicsInteractiveReference {
    private fun c(id:String,label:String,min:Double,max:Double,step:Double,initial:Double,unit:String)=ActivityControl(id,label,min,max,step,initial,unit)
    private fun a(id:String,title:String,concept:String,levels:Set<com.indianservers.aiexplorer.curriculum.SchoolClassLevel>,objective:String,formula:String,controls:List<ActivityControl>,presets:List<ActivityPreset>,parts:List<DiagramPart>,compute:(Map<String,Double>)->VisualState,challenges:List<ActivityChallenge>)=ActivityDefinition(
        id,concept,SchoolSubject.MATHEMATICS,levels,title,listOf(objective),listOf("Predict what will change.","Adjust at least two values and inspect the linked picture and values.","Record the invariant or relationship, then complete a target challenge."),controls,presets,challenges,formula,listOf("Values use the displayed coordinate and measurement units.","The diagram is a mathematical model and may not be to scale."),parts,ActivityAccessibility("All geometry, values, and changes are described as text."),compute)
    private fun state(v:Map<String,Double>,u:Map<String,String>,labels:Map<String,String>,p:List<PlotPoint>,steps:List<String>,why:String,part:String?=null)=VisualState(v,u,labels,p,steps,why,"${labels.values.joinToString()}. $why",part)
    private fun challenge(id:String,title:String,target:String,test:(VisualState)->Boolean)=ActivityChallenge(id,title,target,target,test)

    val linearEquations = a("math-linear-equation-balance","Equation Balance","math-linear-equations",setOf(CLASS_7,CLASS_8,CLASS_9,CLASS_10),"Connect identical operations on both sides of an equation to its solution.","ax + b = c, so x = (c - b) / a",
        listOf(c("a","Coefficient a",1.0,10.0,1.0,2.0,"coefficient"),c("b","Constant b",-10.0,10.0,1.0,4.0,"units"),c("c","Right side c",-10.0,30.0,1.0,12.0,"units")),
        listOf(ActivityPreset("simple","2x + 4 = 12",mapOf("a" to 2.0,"b" to 4.0,"c" to 12.0)),ActivityPreset("negative","3x - 6 = 9",mapOf("a" to 3.0,"b" to -6.0,"c" to 9.0))),
        listOf(DiagramPart("left-pan","left balance pan","a x-blocks and b unit blocks"),DiagramPart("right-pan","right balance pan","c unit blocks")),
        { q->val x=(q.getValue("c")-q.getValue("b"))/q.getValue("a");state(q+mapOf("x" to x),mapOf("a" to "","b" to "units","c" to "units","x" to "units"),mapOf("equation" to "${q["a"]}x + ${q["b"]} = ${q["c"]}","solution" to "x = ${"%.2f".format(x)}"),listOf(PlotPoint(0.0,q.getValue("b"),"left"),PlotPoint(x,q.getValue("c"),"intersection")),listOf("Subtract b from both pans.","Divide both pans into a equal groups."),"Each operation is applied equally, so balance is preserved.","left-pan") },
        listOf(challenge("x4","Make x = 4","Set an equation whose solution is 4."){near(it.values["x"],4.0,.01)},challenge("xminus2","Make x = -2","Set an equation whose solution is -2."){near(it.values["x"],-2.0,.01)},challenge("xhalf","Make x = 0.5","Set an equation whose solution is 0.5."){near(it.values["x"],.5,.01)}))

    val triangles = a("math-triangle-lab","Triangle Invariant Lab","math-triangles",setOf(CLASS_7,CLASS_9,CLASS_10),"Manipulate a triangle and verify its angle and area relationships.","Area = 1/2 × base × height; interior angles sum to 180°",
        listOf(c("base","Base",2.0,14.0,.5,8.0,"cm"),c("height","Height",1.0,10.0,.5,5.0,"cm"),c("offset","Apex offset",0.0,14.0,.5,4.0,"cm")),
        listOf(ActivityPreset("right","Right triangle",mapOf("base" to 8.0,"height" to 6.0,"offset" to 0.0)),ActivityPreset("isosceles","Isosceles",mapOf("base" to 8.0,"height" to 5.0,"offset" to 4.0))),
        listOf(DiagramPart("a","vertex A","left base vertex"),DiagramPart("b","vertex B","right base vertex"),DiagramPart("c","vertex C","draggable apex"),DiagramPart("altitude","altitude","perpendicular height")),
        { q->val b=q.getValue("base");val h=q.getValue("height");val o=q.getValue("offset");val s1=hypot(o,h);val s2=hypot(b-o,h);val a1=Math.toDegrees(atan2(h,o.coerceAtLeast(1e-9)));val a2=Math.toDegrees(atan2(h,(b-o).coerceAtLeast(1e-9)));val a3=180-a1-a2;state(q+mapOf("area" to b*h/2,"angleSum" to a1+a2+a3),mapOf("base" to "cm","height" to "cm","offset" to "cm","area" to "cm²","angleSum" to "°"),mapOf("sides" to "${"%.1f".format(s1)}, ${"%.1f".format(s2)}, $b cm","angles" to "${"%.1f".format(a1)}° + ${"%.1f".format(a2)}° + ${"%.1f".format(a3)}° = 180°"),listOf(PlotPoint(0.0,0.0),PlotPoint(b,0.0),PlotPoint(o,h),PlotPoint(0.0,0.0)),listOf("Drag the apex.","Compare base × height with the enclosing parallelogram."),"The apex can slide parallel to the base: height and area stay fixed; the angle sum remains 180°.","c") },
        listOf(challenge("area24","Area 24 cm²","Construct area 24 cm²."){near(it.values["area"],24.0,.01)},challenge("isosceles","Isosceles position","Place the apex over the midpoint."){near(it.values["offset"],(it.values["base"]?:0.0)/2,.01)},challenge("area40","Area 40 cm²","Construct area 40 cm²."){near(it.values["area"],40.0,.01)}))

    val coordinateGeometry = a("math-coordinate-geometry","Coordinate Geometry Explorer","math-coordinate-geometry",setOf(CLASS_9,CLASS_10,CLASS_11),"Relate two plotted points to slope, distance, and midpoint.","m = Δy/Δx; d = √(Δx²+Δy²); midpoint = ((x₁+x₂)/2,(y₁+y₂)/2)",
        listOf(c("x1","x₁",-10.0,10.0,1.0,-2.0,"coordinate units"),c("y1","y₁",-10.0,10.0,1.0,1.0,"coordinate units"),c("x2","x₂",-10.0,10.0,1.0,4.0,"coordinate units"),c("y2","y₂",-10.0,10.0,1.0,5.0,"coordinate units")),
        listOf(ActivityPreset("rise-run","Rise 4, run 6",mapOf("x1" to -2.0,"y1" to 1.0,"x2" to 4.0,"y2" to 5.0)),ActivityPreset("negative","Negative slope",mapOf("x1" to -4.0,"y1" to 5.0,"x2" to 4.0,"y2" to -3.0))),
        listOf(DiagramPart("p1","point one","first endpoint"),DiagramPart("p2","point two","second endpoint"),DiagramPart("slope-triangle","slope triangle","run and rise")),
        {q->val dx=q.getValue("x2")-q.getValue("x1");val dy=q.getValue("y2")-q.getValue("y1");val slope=if(abs(dx)<1e-9) Double.NaN else dy/dx;val d=hypot(dx,dy);state(q+mapOf("slope" to slope,"distance" to d,"midX" to (q.getValue("x1")+q.getValue("x2"))/2,"midY" to (q.getValue("y1")+q.getValue("y2"))/2),mapOf("x1" to "units","y1" to "units","x2" to "units","y2" to "units","slope" to "","distance" to "units","midX" to "units","midY" to "units"),mapOf("delta" to "rise $dy, run $dx","slope" to if(slope.isNaN()) "vertical: undefined slope" else "slope ${"%.2f".format(slope)}"),listOf(PlotPoint(q.getValue("x1"),q.getValue("y1")),PlotPoint(q.getValue("x2"),q.getValue("y2"))),listOf("Plot both endpoints.","Draw the horizontal run and vertical rise."),"Distance is the hypotenuse of the slope triangle; the midpoint averages corresponding coordinates.","slope-triangle")},
        listOf(challenge("slope1","Slope 1","Create a line of slope 1."){near(it.values["slope"],1.0,.01)},challenge("distance10","Distance 10","Make endpoints 10 units apart."){near(it.values["distance"],10.0,.01)},challenge("midorigin","Midpoint at origin","Make midpoint (0,0)."){near(it.values["midX"],0.0,.01)&&near(it.values["midY"],0.0,.01)}))

    val trigonometry = a("math-right-triangle-trig","Right-Triangle Ratio Explorer","math-trigonometry",setOf(CLASS_10,CLASS_11),"Observe that trigonometric ratios depend on angle, not triangle scale.","sin θ = opposite/hypotenuse; cos θ = adjacent/hypotenuse; tan θ = opposite/adjacent",
        listOf(c("angle","Angle θ",5.0,85.0,1.0,30.0,"degrees"),c("hypotenuse","Hypotenuse",2.0,20.0,.5,10.0,"cm")),
        listOf(ActivityPreset("thirty","30°",mapOf("angle" to 30.0,"hypotenuse" to 10.0)),ActivityPreset("fortyfive","45°",mapOf("angle" to 45.0,"hypotenuse" to 10.0))),
        listOf(DiagramPart("opposite","opposite side","side across from theta"),DiagramPart("adjacent","adjacent side","non-hypotenuse side beside theta"),DiagramPart("hypotenuse","hypotenuse","side opposite right angle")),
        {q->val rad=Math.toRadians(q.getValue("angle"));val h=q.getValue("hypotenuse");val op=h*sin(rad);val ad=h*cos(rad);state(q+mapOf("opposite" to op,"adjacent" to ad,"sin" to sin(rad),"cos" to cos(rad),"tan" to tan(rad)),mapOf("angle" to "°","hypotenuse" to "cm","opposite" to "cm","adjacent" to "cm","sin" to "","cos" to "","tan" to ""),mapOf("lengths" to "opposite ${"%.2f".format(op)} cm, adjacent ${"%.2f".format(ad)} cm","ratios" to "sin ${"%.3f".format(sin(rad))}, cos ${"%.3f".format(cos(rad))}, tan ${"%.3f".format(tan(rad))}"),listOf(PlotPoint(0.0,0.0),PlotPoint(ad,0.0),PlotPoint(ad,op),PlotPoint(0.0,0.0)),listOf("Choose an angle.","Scale the triangle without changing the angle."),"Scaling changes all lengths by the same factor, so each side ratio is invariant.","hypotenuse")},
        listOf(challenge("sinhalf","sin θ = 0.5","Find an angle with sine one half."){near(it.values["sin"],.5,.01)},challenge("equallegs","Equal legs","Make opposite equal adjacent."){near(it.values["opposite"],it.values["adjacent"]?:0.0,.01)},challenge("tanroot3","tan θ ≈ √3","Find the angle whose tangent is √3."){near(it.values["tan"],sqrt(3.0),.04)}))

    val probability = a("math-probability-experiment","Probability Experiment","math-probability",setOf(CLASS_9,CLASS_10,CLASS_11,CLASS_12),"Compare theoretical probability with a reproducible experimental frequency.","P(E) = favourable outcomes / total outcomes; expected frequency = nP(E)",
        listOf(c("favourable","Favourable outcomes",1.0,10.0,1.0,1.0,"outcomes"),c("total","Total outcomes",2.0,12.0,1.0,6.0,"outcomes"),c("trials","Trials",10.0,1000.0,10.0,100.0,"trials")),
        listOf(ActivityPreset("die","One face on a die",mapOf("favourable" to 1.0,"total" to 6.0,"trials" to 120.0)),ActivityPreset("coin","Heads",mapOf("favourable" to 1.0,"total" to 2.0,"trials" to 100.0))),
        listOf(DiagramPart("sample-space","sample space","equally likely outcome cells"),DiagramPart("frequency-bar","frequency bar","expected and deterministic observed proportions")),
        {q->val total=q.getValue("total");val fav=q.getValue("favourable").coerceAtMost(total);val n=q.getValue("trials");val p=fav/total;val observed=((n*p + sin(n+fav)*sqrt(n*p*(1-p).coerceAtLeast(0.0))).roundToInt()).coerceIn(0,n.toInt());state(q+mapOf("favourableUsed" to fav,"probability" to p,"expected" to n*p,"observed" to observed.toDouble(),"observedProbability" to observed/n),mapOf("favourable" to "outcomes","total" to "outcomes","trials" to "trials","favourableUsed" to "outcomes","probability" to "","expected" to "successes","observed" to "successes","observedProbability" to ""),mapOf("theory" to "P(E) = ${"%.3f".format(p)}","experiment" to "$observed successes in ${n.toInt()} trials"),listOf(PlotPoint(0.0,p,"theory"),PlotPoint(1.0,observed/n,"experiment")),listOf("Build the sample space.","Predict a count, then run the reproducible trial model."),"Larger trial counts tend to bring relative frequency closer to theoretical probability, without guaranteeing an exact count.","frequency-bar")},
        listOf(challenge("half","Probability 1/2","Build an event with probability one half."){near(it.values["probability"],.5,.001)},challenge("quarter","Probability 1/4","Build an event with probability one quarter."){near(it.values["probability"],.25,.001)},challenge("expected100","Expected count 100","Make expected successes 100."){near(it.values["expected"],100.0,.01)}))

    val definitions = listOf(linearEquations,triangles,coordinateGeometry,trigonometry,probability)
    fun create(activityId:String)=FunctionalInteractiveActivity(definitions.single{it.activityId==activityId})
}
