package com.indianservers.aiexplorer.solver.domain.visualisation

import com.indianservers.aiexplorer.solver.domain.model.ProblemType
import com.indianservers.aiexplorer.solver.domain.model.SolverSolution

object SolverFormulaUnderstanding {
    fun forSolution(solution: SolverSolution, visualisations: List<VisualisationSpec>): FormulaUnderstanding? {
        if (!solution.supported || solution.steps.isEmpty()) return null
        val source = solution.input.normalized.lowercase()
        val id = when {
            solution.classification.type == ProblemType.QuadraticEquation -> "quadratic-formula"
            "distance(" in source -> "distance-formula"
            "midpoint(" in source -> "midpoint-formula"
            "gradient(" in source -> "gradient-formula"
            "pythag" in source -> "pythagorean-theorem"
            "sine rule" in source -> "sine-rule"
            "cosine rule" in source -> "cosine-rule"
            "arithmeticsum" in source -> "arithmetic-series"
            "geometricsum" in source || "infinitegeometric" in source -> "geometric-series"
            solution.classification.type == ProblemType.MatrixOperation && "inverse" in source -> "matrix-inverse-2x2"
            solution.classification.type == ProblemType.MatrixOperation && "det" in source -> "determinant-2x2"
            solution.classification.type == ProblemType.Calculus && ("different" in source || "derivative" in source) ->
                when {
                    '*' in source -> "product-rule"
                    Regex("""(?:sin|cos|tan|ln|exp)\([^)]*[+\-*/^][^)]*\)""").containsMatchIn(source) -> "chain-rule"
                    else -> "derivative-power-rule"
                }
            solution.classification.type == ProblemType.Calculus && ("integr" in source) -> "integration-power-rule"
            else -> null
        } ?: return null
        val entry = entries[id] ?: return null
        val visual = visualisations.firstOrNull { spec -> spec.type in entry.visualTypes }
            ?: visualisations.first()
        return FormulaUnderstanding(
            id = id,
            title = entry.title,
            symbolicDerivation = entry.derivation,
            visualInterpretation = entry.visual,
            conditions = entry.conditions,
            example = entry.example,
            verification = entry.verification,
            visualisation = visual,
        )
    }

    private data class Entry(
        val title: String,
        val derivation: List<String>,
        val visual: String,
        val conditions: List<String>,
        val example: String,
        val verification: String,
        val visualTypes: Set<VisualisationType>,
    )

    private val entries = mapOf(
        "quadratic-formula" to Entry(
            "Why the quadratic formula works",
            listOf("ax^2+bx+c=0", "x^2+(b/a)x=-c/a", "(x+b/2a)^2=(b^2-4ac)/(4a^2)", "x=(-b +/- sqrt(b^2-4ac))/(2a)"),
            "Completing a geometric square exposes the horizontal shift and the two symmetric root offsets.",
            listOf("a must not equal 0", "The discriminant chooses two, one, or no real intersections."),
            "For x^2-5x+6=0, the formula returns 2 and 3.",
            "Substitute each root into ax^2+bx+c and obtain zero.",
            setOf(VisualisationType.QuadraticGeometry),
        ),
        "distance-formula" to Entry(
            "Why the distance formula works",
            listOf("Delta x=x2-x1", "Delta y=y2-y1", "d^2=(Delta x)^2+(Delta y)^2", "d=sqrt((Delta x)^2+(Delta y)^2)"),
            "The coordinate differences form perpendicular legs of a right triangle.",
            listOf("Both points use the same coordinate scale."),
            "The distance from (0,0) to (3,4) is 5.",
            "Squaring the displayed distance reproduces the sum of the squared legs.",
            setOf(VisualisationType.CoordinateGraph, VisualisationType.Triangle),
        ),
        "midpoint-formula" to Entry(
            "Why the midpoint formula works",
            listOf("xm-x1=x2-xm", "2xm=x1+x2", "xm=(x1+x2)/2", "Apply the same argument to y."),
            "The midpoint divides both coordinate changes into equal halves.",
            listOf("Coordinates belong to an affine Cartesian plane."),
            "The midpoint of (0,2) and (4,6) is (2,4).",
            "Distances from the midpoint to each endpoint are equal.",
            setOf(VisualisationType.CoordinateGraph),
        ),
        "gradient-formula" to Entry(
            "Why the gradient formula works",
            listOf("rise=Delta y", "run=Delta x", "m=rise/run=(y2-y1)/(x2-x1)"),
            "Every slope triangle on one straight line is similar, so rise divided by run is constant.",
            listOf("x2 must not equal x1 for a finite gradient."),
            "Through (1,2) and (3,6), m=4/2=2.",
            "A third point generated by y-y1=m(x-x1) lies on the same line.",
            setOf(VisualisationType.CoordinateGraph, VisualisationType.Triangle),
        ),
        "pythagorean-theorem" to Entry(
            "Why the Pythagorean theorem works",
            listOf("(a+b)^2=4(ab/2)+c^2", "a^2+2ab+b^2=2ab+c^2", "a^2+b^2=c^2"),
            "Rearranging four identical right triangles leaves exactly the square on the hypotenuse.",
            listOf("The triangle must be right-angled."),
            "For legs 3 and 4, c^2=9+16=25, so c=5.",
            "Measured square areas satisfy the same equality.",
            setOf(VisualisationType.Triangle),
        ),
        "sine-rule" to Entry(
            "Why the sine rule works",
            listOf("h=c sin(B)", "h=b sin(C)", "c sin(B)=b sin(C)", "b/sin(B)=c/sin(C)"),
            "Dropping one altitude expresses the same height from two sides.",
            listOf("Use matched opposite side-angle pairs.", "Ambiguous SSA data can produce two triangles."),
            "If B=30 degrees, C=45 degrees and b=5, then c=5 sin(45)/sin(30).",
            "Reconstruct the triangle and compare the common altitude.",
            setOf(VisualisationType.Triangle),
        ),
        "cosine-rule" to Entry(
            "Why the cosine rule works",
            listOf("horizontal projection=b cos(C)", "height=b sin(C)", "c^2=(a-b cos(C))^2+(b sin(C))^2", "c^2=a^2+b^2-2ab cos(C)"),
            "A side is split into horizontal and vertical projections before applying Pythagoras.",
            listOf("C is the included angle between a and b."),
            "For a=b=1 and C=60 degrees, c=1.",
            "Coordinates of the constructed endpoint reproduce side c.",
            setOf(VisualisationType.Triangle),
        ),
        "arithmetic-series" to Entry(
            "Why the arithmetic-series sum works",
            listOf("S=a+(a+d)+...+l", "S=l+(l-d)+...+a", "2S=n(a+l)", "S=n(a+l)/2"),
            "Pairing the first and last bars gives the same height for every pair.",
            listOf("Terms have a constant difference.", "n is a positive integer."),
            "1+2+3+4+5=5(1+5)/2=15.",
            "Directly add the generated finite terms.",
            setOf(VisualisationType.SequencePattern),
        ),
        "geometric-series" to Entry(
            "Why the geometric-series sum works",
            listOf("S=a+ar+...+ar^(n-1)", "rS=ar+...+ar^n", "S-rS=a-ar^n", "S=a(1-r^n)/(1-r)"),
            "Each new bar is a fixed fraction or multiple of the preceding bar.",
            listOf("r must not equal 1 for the finite closed form.", "|r|<1 for an infinite sum."),
            "1+1/2+1/4+... converges to 2.",
            "Partial sums approach the stated limit only when |r|<1.",
            setOf(VisualisationType.SequencePattern),
        ),
        "derivative-power-rule" to Entry(
            "Why the derivative power rule works",
            listOf("d(x^n)/dx=lim[h->0]((x+h)^n-x^n)/h", "Expand (x+h)^n", "Cancel x^n and divide by h", "All higher powers of h vanish, leaving nx^(n-1)"),
            "Secant slopes approach one tangent slope as the horizontal interval shrinks.",
            listOf("For the displayed elementary real function, x is inside its domain."),
            "d(x^3)/dx=3x^2.",
            "Finite-difference slopes approach the symbolic derivative.",
            setOf(VisualisationType.DerivativeTangent),
        ),
        "product-rule" to Entry(
            "Why the product rule works",
            listOf("Delta(uv)=u Delta v+v Delta u+Delta u Delta v", "Divide by Delta x", "Let Delta x approach 0", "(uv)'=u'v+uv'"),
            "A changing rectangle gains one strip from each changing side; the tiny corner vanishes in the limit.",
            listOf("Both factors are differentiable at the point."),
            "d(x sin x)/dx=sin x+x cos x.",
            "Compare the symbolic result with centred finite differences.",
            setOf(VisualisationType.DerivativeTangent),
        ),
        "chain-rule" to Entry(
            "Why the chain rule works",
            listOf("dy/dx=(dy/du)(du/dx)", "A small x change first changes u", "That u change then changes y"),
            "Nested input scales combine: the outer slope is multiplied by the inner slope.",
            listOf("The inner and outer functions are differentiable on the evaluated branch."),
            "d(sin(x^2))/dx=cos(x^2)*2x.",
            "Centred differences match the composed symbolic derivative away from discontinuities.",
            setOf(VisualisationType.DerivativeTangent),
        ),
        "integration-power-rule" to Entry(
            "Why the integration power rule works",
            listOf("d(x^(n+1))/dx=(n+1)x^n", "Divide by n+1", "integral x^n dx=x^(n+1)/(n+1)+C"),
            "Accumulated signed area changes at a rate equal to the curve height.",
            listOf("n must not equal -1", "Use ln|x| when n=-1."),
            "Integral of x^2 is x^3/3+C.",
            "Differentiate the antiderivative and recover the integrand.",
            setOf(VisualisationType.IntegralArea),
        ),
        "determinant-2x2" to Entry(
            "Why the 2 by 2 determinant works",
            listOf("A maps the unit square to a parallelogram", "Signed area scale=ad-bc", "det(A)=ad-bc"),
            "The determinant is the signed area scaling of the transformed basis square.",
            listOf("Matrix is 2 by 2."),
            "det([[2,0],[0,3]])=6.",
            "Compute the transformed parallelogram area independently.",
            setOf(VisualisationType.MatrixTransformation, VisualisationType.RowReductionGrid),
        ),
        "matrix-inverse-2x2" to Entry(
            "Why the 2 by 2 inverse works",
            listOf("A=[[a,b],[c,d]]", "adj(A)=[[d,-b],[-c,a]]", "A adj(A)=(ad-bc)I", "A^-1=adj(A)/(ad-bc)"),
            "The inverse transformation returns transformed basis vectors to their original positions.",
            listOf("ad-bc must not equal 0."),
            "inverse([[2,0],[0,4]])=[[1/2,0],[0,1/4]].",
            "Multiply A by the proposed inverse and obtain the identity.",
            setOf(VisualisationType.MatrixTransformation, VisualisationType.RowReductionGrid),
        ),
    )
}
