package com.indianservers.aiexplorer.biology.ncert.interaction

import com.indianservers.aiexplorer.curriculum.SchoolClassLevel.*
import com.indianservers.aiexplorer.curriculum.SchoolSubject
import com.indianservers.aiexplorer.curriculum.interaction.*
import kotlin.math.*

object BiologyInteractiveReference {
 private fun c(i:String,l:String,n:Double,x:Double,s:Double,v:Double,u:String)=ActivityControl(i,l,n,x,s,v,u)
 private fun ch(i:String,t:String,f:(VisualState)->Boolean)=ActivityChallenge(i,t,t,t,f)
 private fun vis(v:Map<String,Double>,u:Map<String,String>,l:Map<String,String>,p:List<PlotPoint>,steps:List<String>,e:String,part:String)=VisualState(v,u,l,p,steps,e,"${l.values.joinToString()}. $e",part)
 private fun a(id:String,title:String,concept:String,levels:Set<com.indianservers.aiexplorer.curriculum.SchoolClassLevel>,objective:String,process:String,controls:List<ActivityControl>,presets:List<ActivityPreset>,parts:List<DiagramPart>,assumptions:List<String>,compute:(Map<String,Double>)->VisualState,challenges:List<ActivityChallenge>)=ActivityDefinition(id,concept,SchoolSubject.BIOLOGY,levels,title,listOf(objective),listOf("Predict the structural or process response.","Manipulate the labelled 2D model and inspect the text pathway.","Record an observation and complete a target."),controls,presets,challenges,process,assumptions,parts,ActivityAccessibility("Every layer, selected structure, direction, stage, and quantitative output is available as ordered text; motion can be stepped."),compute)

 private val organelles=listOf("nucleus" to "stores DNA and coordinates gene expression","mitochondrion" to "transfers energy through aerobic respiration","ribosome" to "synthesises polypeptides","cell membrane" to "selectively regulates exchange","vacuole" to "stores cell sap and supports plant-cell turgor","chloroplast" to "captures light energy for photosynthesis")
 val cell=a("biology-cell-explorer","Layered Cell Structure Explorer","biology-cell-structure",setOf(CLASS_8,CLASS_9,CLASS_11),"Identify organelles by structure and connect each to a defensible function.","Select structure → highlight location → reveal function → compare plant and animal cells",listOf(c("organelle","Selected organelle",0.0,5.0,1.0,0.0,"index"),c("plant","Cell type: 0 animal, 1 plant",0.0,1.0,1.0,1.0,"mode"),c("labels","Labels: 0 hidden, 1 shown",0.0,1.0,1.0,1.0,"mode")),listOf(ActivityPreset("plant","Plant cell",mapOf("organelle" to 5.0,"plant" to 1.0,"labels" to 1.0)),ActivityPreset("animal","Animal cell",mapOf("organelle" to 1.0,"plant" to 0.0,"labels" to 1.0))),organelles.map{DiagramPart(it.first,it.first,it.second)},listOf("Rich 2D schematic; organelle sizes and positions are not to scale.","Chloroplast and large central vacuole are treated as plant-cell features in this comparison."),{q->val index=q.getValue("organelle").roundToInt();val selected=organelles[index];val plant=q.getValue("plant")>.5;val available=plant||selected.first !in setOf("chloroplast","vacuole");vis(q+mapOf("selectedAvailable" to if(available)1.0 else 0.0),mapOf("organelle" to "index","plant" to "mode","labels" to "mode","selectedAvailable" to "boolean"),mapOf("cell" to if(plant)"plant cell" else "animal cell","selection" to "${selected.first}: ${if(available)selected.second else "not shown in this animal-cell comparison"}","labels" to if(q.getValue("labels")>.5)"labels shown" else "labels hidden; screen-reader names remain available"),listOf(PlotPoint(index.toDouble(),if(available)1.0 else 0.0,"selected layer")),listOf("Choose cell type.","Select an organelle.","Toggle labels and explain the function without relying on colour."),"The explorer links a highlighted 2D part to function and explicitly flags structures absent from the chosen comparison.",selected.first)},listOf(ch("nucleus","Select the nucleus"){near(it.values["organelle"],0.0,.01)},ch("plantChloroplast","Show a plant chloroplast"){near(it.values["organelle"],5.0,.01)&&near(it.values["plant"],1.0,.01)},ch("hideLabels","Identify after hiding labels"){near(it.values["labels"],0.0,.01)}))

 val membrane=a("biology-membrane-transport","Membrane Transport Lab","biology-membrane-transport",setOf(CLASS_9,CLASS_11),"Predict net passive movement and distinguish it from energy-dependent transport.","Passive flux proxy = permeability × (Coutside − Cinside); active transport can oppose the gradient",listOf(c("outside","Outside concentration",0.0,100.0,1.0,80.0,"relative units"),c("inside","Inside concentration",0.0,100.0,1.0,20.0,"relative units"),c("permeability","Permeability",0.0,1.0,.05,.5,"fraction"),c("active","Active pump: 0 off, 1 on",0.0,1.0,1.0,0.0,"mode")),listOf(ActivityPreset("diffusion","Diffusion inward",mapOf("outside" to 80.0,"inside" to 20.0,"permeability" to .5,"active" to 0.0)),ActivityPreset("pump","Pump outward",mapOf("outside" to 30.0,"inside" to 60.0,"permeability" to .2,"active" to 1.0))),listOf(DiagramPart("outside","outside solution","extracellular concentration"),DiagramPart("membrane","membrane","selective barrier"),DiagramPart("inside","cytoplasm","intracellular concentration"),DiagramPart("pump","transport protein","energy-dependent outward proxy")),listOf("Flux is a qualitative proxy, not a calibrated membrane rate.","The active switch represents one outward pump and does not model a named transporter or coupled ion gradients."),{q->val passive=q.getValue("permeability")*(q.getValue("outside")-q.getValue("inside"));val active=if(q.getValue("active")>.5)-30.0 else 0.0;val net=passive+active;vis(q+mapOf("passiveFlux" to passive,"activeFlux" to active,"netFlux" to net),mapOf("outside" to "relative concentration","inside" to "relative concentration","permeability" to "fraction","active" to "mode","passiveFlux" to "relative flux","activeFlux" to "relative flux","netFlux" to "relative flux"),mapOf("direction" to when{net>1->"net inward";net< -1->"net outward";else->"approximately balanced"},"mechanism" to if(q.getValue("active")>.5)"passive pathway plus ATP-dependent pump proxy" else "passive transport only"),listOf(PlotPoint(0.0,q.getValue("outside"),"outside"),PlotPoint(1.0,q.getValue("inside"),"inside")),listOf("Predict net direction.","Change the gradient and permeability.","Switch the pump on and separate passive from active contributions."),"Passive net movement follows the concentration gradient; an active transporter may oppose it by using cellular energy.","membrane")},listOf(ch("equilibrium","Make net flux approximately zero"){near(it.values["netFlux"],0.0,1.0)},ch("inward","Produce inward net transport"){(it.values["netFlux"]?:0.0)>10},ch("outward","Produce outward net transport"){(it.values["netFlux"]?:0.0)<-10}))

 private val phases=listOf("interphase","prophase","metaphase","anaphase","telophase/cytokinesis")
 val division=a("biology-cell-division","Mitosis and Meiosis Process Explorer","biology-mitosis-meiosis",setOf(CLASS_9,CLASS_11,CLASS_12),"Sequence chromosome behaviour and compare mitosis with meiosis outcomes.","DNA replicates once; mitosis has one division, meiosis has two divisions and separates homologues before sister chromatids",listOf(c("process","Process: 0 mitosis, 1 meiosis",0.0,1.0,1.0,0.0,"mode"),c("phase","Stage",0.0,4.0,1.0,0.0,"index"),c("startingPairs","Starting homologous pairs",1.0,6.0,1.0,2.0,"pairs")),listOf(ActivityPreset("mitosisMeta","Mitosis metaphase",mapOf("process" to 0.0,"phase" to 2.0)),ActivityPreset("meiosisEnd","Meiosis completion",mapOf("process" to 1.0,"phase" to 4.0))),listOf(DiagramPart("chromosomes","chromosomes","condensed DNA structures"),DiagramPart("spindle","spindle","microtubule separation system"),DiagramPart("cells","daughter cells","outcome compartments")),listOf("Five controls stages compress several continuous sub-stages for comparison.","Chromosome drawings are symbolic and not to scale; crossing-over is not quantified."),{q->val meiosis=q.getValue("process")>.5;val stage=q.getValue("phase").roundToInt();val end=stage==4;val cells=if(end&&meiosis)4 else if(end)2 else 1;val ploidy=if(end&&meiosis)1 else 2;vis(q+mapOf("daughterCells" to cells.toDouble(),"ploidySets" to ploidy.toDouble(),"chromosomesPerEndCell" to q.getValue("startingPairs")*ploidy),mapOf("process" to "mode","phase" to "index","startingPairs" to "pairs","daughterCells" to "cells","ploidySets" to "sets","chromosomesPerEndCell" to "chromosomes"),mapOf("stage" to "${if(meiosis)"meiosis" else "mitosis"}: ${phases[stage]}","outcome" to "$cells cell(s), $ploidy chromosome set(s) at this simplified stage"),listOf(PlotPoint(stage.toDouble(),cells.toDouble(),if(meiosis)"meiosis" else "mitosis")),phases.mapIndexed{i,p->"${i+1}. $p"},"Mitosis preserves chromosome-set number in two daughter cells; meiosis halves it and produces four products after two divisions.","chromosomes")},listOf(ch("mitosisEnd","Finish mitosis with two cells"){near(it.values["daughterCells"],2.0,.01)&&near(it.values["ploidySets"],2.0,.01)},ch("meiosisEnd","Finish meiosis with four haploid cells"){near(it.values["daughterCells"],4.0,.01)&&near(it.values["ploidySets"],1.0,.01)},ch("metaphase","Select metaphase"){near(it.values["phase"],2.0,.01)}))

 val circulation=a("biology-circulation","Blood Circulation and Cardiac Output","biology-blood-circulation",setOf(CLASS_7,CLASS_10,CLASS_11),"Trace double circulation and connect heart rate and stroke volume to cardiac output.","Cardiac output = heart rate × stroke volume",listOf(c("heartRate","Heart rate",40.0,180.0,1.0,72.0,"beats/min"),c("strokeVolume","Stroke volume",30.0,120.0,1.0,70.0,"mL/beat"),c("routeStage","Flow step",0.0,7.0,1.0,0.0,"index")),listOf(ActivityPreset("rest","Resting example",mapOf("heartRate" to 72.0,"strokeVolume" to 70.0,"routeStage" to 0.0)),ActivityPreset("exercise","Exercise example",mapOf("heartRate" to 140.0,"strokeVolume" to 100.0,"routeStage" to 4.0))),listOf(DiagramPart("right-atrium","right atrium","receives systemic venous blood"),DiagramPart("right-ventricle","right ventricle","pumps to lungs"),DiagramPart("lungs","lungs","gas-exchange circulation"),DiagramPart("left-atrium","left atrium","receives pulmonary venous blood"),DiagramPart("left-ventricle","left ventricle","pumps to body"),DiagramPart("body","body tissues","systemic exchange")),listOf("Cardiac output is a calculated flow, not a diagnosis or individual health recommendation.","Route animation is a simplified double-circulation pathway; oxygen status is also stated by text/pattern."),{q->val route=listOf("body → venae cavae","right atrium","right ventricle → pulmonary artery","lungs: gas exchange","pulmonary veins → left atrium","left ventricle","aorta → body","systemic exchange");val i=q.getValue("routeStage").roundToInt();val output=q.getValue("heartRate")*q.getValue("strokeVolume")/1000;vis(q+mapOf("cardiacOutput" to output),mapOf("heartRate" to "beats/min","strokeVolume" to "mL/beat","routeStage" to "index","cardiacOutput" to "L/min"),mapOf("route" to "Step ${i+1}: ${route[i]}","output" to "cardiac output ${"%.2f".format(output)} L/min"),listOf(PlotPoint(q.getValue("heartRate"),output,"cardiac output")),route.mapIndexed{j,s->"${j+1}. $s"},"The right side supports pulmonary circulation and the left supports systemic circulation; rate × volume per beat gives volume per minute.",when(i){1->"right-atrium";2->"right-ventricle";3->"lungs";4->"left-atrium";5->"left-ventricle";else->"body"})},listOf(ch("five","Create cardiac output 5 L/min"){near(it.values["cardiacOutput"],5.0,.05)},ch("lungs","Trace to the lungs"){near(it.values["routeStage"],3.0,.01)},ch("ten","Create cardiac output 10 L/min"){near(it.values["cardiacOutput"],10.0,.08)}))

 val genetics=a("biology-mendelian-genetics","Mendelian Cross Explorer","biology-mendelian-genetics",setOf(CLASS_10,CLASS_12),"Build a monohybrid cross and distinguish genotype probabilities from phenotype probabilities.","Each parent contributes one allele; Punnett-cell probabilities multiply independent gamete probabilities",listOf(c("parent1A","Parent 1 probability of A",0.0,1.0,.5,.5,"probability"),c("parent2A","Parent 2 probability of A",0.0,1.0,.5,.5,"probability"),c("dominance","A dominant: 0 no, 1 yes",0.0,1.0,1.0,1.0,"mode")),listOf(ActivityPreset("heterozygous","Aa × Aa",mapOf("parent1A" to .5,"parent2A" to .5,"dominance" to 1.0)),ActivityPreset("testCross","Aa × aa",mapOf("parent1A" to .5,"parent2A" to 0.0,"dominance" to 1.0))),listOf(DiagramPart("gametes1","parent one gametes","A/a probabilities"),DiagramPart("gametes2","parent two gametes","A/a probabilities"),DiagramPart("punnett","Punnett grid","four genotype combinations")),listOf("Single autosomal locus with independent gamete formation and no viability or sampling effects.","The model predicts probabilities across many offspring, never a guaranteed sequence of births."),{q->val p=q.getValue("parent1A");val r=q.getValue("parent2A");val aaBig=p*r;val het=p*(1-r)+(1-p)*r;val aa=(1-p)*(1-r);val dominant=if(q.getValue("dominance")>.5)aaBig+het else aaBig;vis(q+mapOf("AA" to aaBig,"Aa" to het,"aa" to aa,"dominantPhenotype" to dominant,"recessivePhenotype" to 1-dominant),mapOf("parent1A" to "probability","parent2A" to "probability","dominance" to "mode","AA" to "probability","Aa" to "probability","aa" to "probability","dominantPhenotype" to "probability","recessivePhenotype" to "probability"),mapOf("genotypes" to "AA ${"%.2f".format(aaBig)}, Aa ${"%.2f".format(het)}, aa ${"%.2f".format(aa)}","phenotypes" to "displayed A phenotype ${"%.2f".format(dominant)}"),listOf(PlotPoint(0.0,aaBig,"AA"),PlotPoint(1.0,het,"Aa"),PlotPoint(2.0,aa,"aa")),listOf("Set each parent's gamete probabilities.","Fill the four combinations.","Sum genotype cells for the stated dominance model."),"A Punnett grid organises probabilities. It does not force a 3:1 count in a family of four.","punnett")},listOf(ch("threeOne","Create 3:1 phenotype probability"){near(it.values["dominantPhenotype"],.75,.01)},ch("oneOne","Create 1:1 phenotype probability"){near(it.values["dominantPhenotype"],.5,.01)},ch("allRecessive","Create all recessive offspring"){near(it.values["recessivePhenotype"],1.0,.01)}))

 val definitions=listOf(cell,membrane,division,circulation,genetics)
 fun create(id:String)=FunctionalInteractiveActivity(definitions.single{it.activityId==id})
}
