package com.indianservers.aiexplorer.chemistry.ncert.intelligence
import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.reference.*
object ChemistryLearningIntelligence{
 private val s=SchoolSubject.CHEMISTRY;private val levels=setOf(SchoolClassLevel.CLASS_9,SchoolClassLevel.CLASS_10,SchoolClassLevel.CLASS_11)
 private fun node(vararg k:String)=ReferenceCurriculumResolver.topic(s,*k)
 val concepts=listOf(
  ReferenceConceptFactory.create("chemistry-atomic-number-mass-number",node("Atom","Structure"),s,levels,emptyList(),"chemistry-atom-builder","atomic labels","chem-atomic-mass-same","Atomic number and mass number are the same","Atomic number counts protons; mass number counts protons plus neutrons.","Carbon-14 has Z=6 and A=14.","Every atom has equal atomic and mass numbers.",DiagnosticQuestionKind.CONCEPT,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.DIAGRAM_TASK)),
  ReferenceConceptFactory.create("chemistry-ions-isotopes",node("Atom","Structure"),s,levels,listOf("chemistry-atomic-number-mass-number"),"chemistry-atom-builder","element identity","chem-electrons-change-element","Changing electrons changes the element","Proton number fixes element identity; changing electrons changes charge.","Removing one electron forms an ion of the same element.","Removing one electron creates a new element.",DiagnosticQuestionKind.REASONING,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.APPLICATION_TASK)),
  ReferenceConceptFactory.create("chemistry-periodic-trends",node("Period"),s,levels,listOf("chemistry-atomic-number-mass-number"),"chemistry-periodic-trends","acid terminology","chem-strong-concentrated","Strong acid means concentrated acid","Strength describes ionisation; concentration describes amount per volume.","A dilute strong acid can be less concentrated than a concentrated weak acid.","Strong and concentrated are interchangeable.",DiagnosticQuestionKind.PREREQUISITE_DISCRIMINATION,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.DATA_INTERPRETATION)),
  ReferenceConceptFactory.create("chemistry-chemical-bonding",node("Bond"),s,levels,listOf("chemistry-periodic-trends"),"chemistry-bonding","chemical equilibrium","chem-equilibrium-stops","Equilibrium means the reaction stops","At dynamic equilibrium forward and reverse processes continue at equal rates.","Both reactions continue with no net composition change.","Particles stop reacting at equilibrium.",DiagnosticQuestionKind.VISUAL,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.DIAGRAM_TASK)),
  ReferenceConceptFactory.create("chemistry-acids-bases",node("Acid","Base"),s,levels,listOf("chemistry-ions-isotopes"),"chemistry-titration","catalyst and equilibrium","chem-catalyst-equilibrium","A catalyst changes equilibrium composition","A catalyst speeds forward and reverse reactions and does not change the equilibrium position.","A catalyst reaches the same equilibrium sooner.","A catalyst creates more equilibrium product.",DiagnosticQuestionKind.REASONING,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.EXPERIMENT_RESULT,MasteryEvidenceType.NUMERICAL_PROBLEM)),
  ReferenceConceptFactory.create("chemistry-gas-laws",node("Gas","States","Basic Concepts"),s,levels,listOf("chemistry-atomic-number-mass-number"),"chemistry-gas-laws","ideal gas variables","chem-gas-celsius-direct","Celsius temperature can be used directly in PV=nRT","Ideal-gas calculations require absolute kelvin temperature; particle speed and pressure follow the verified model state.","At fixed n and V, doubling kelvin temperature doubles ideal pressure.","At fixed volume, doubling 20 °C to 40 °C doubles pressure.",DiagnosticQuestionKind.REASONING,setOf(MasteryEvidenceType.NUMERICAL_PROBLEM,MasteryEvidenceType.SIMULATION_PREDICTION,MasteryEvidenceType.DATA_INTERPRETATION))
 )
}
