package com.indianservers.aiexplorer.curriculum.interactive

import com.indianservers.aiexplorer.curriculum.SchoolClassLevel
import com.indianservers.aiexplorer.curriculum.SchoolSubject
import com.indianservers.aiexplorer.curriculum.experience.*
import com.indianservers.aiexplorer.curriculum.interaction.ActivityControl
import com.indianservers.aiexplorer.curriculum.interaction.ActivityDefinition
import com.indianservers.aiexplorer.curriculum.interaction.ReferenceActivityRegistry
import com.indianservers.aiexplorer.curriculum.production.ScientificReviewStatus

enum class InteractionTier { TIER_A_FULL_SIMULATION, TIER_B_VISUAL_PROCESS, TIER_C_PRACTICE_INTERACTION, TIER_D_READING_FIRST }
enum class InteractiveVisualType { MANIPULABLE_DIAGRAM, VARIABLE_SIMULATION, LIVE_GRAPH, PROCESS_STEPPER, DRAG_DROP, LABEL_ACTIVITY, SORTING_ACTIVITY, SEQUENCE_ACTIVITY, CONSTRUCTION_TOOL, VIRTUAL_EXPERIMENT, FORMULA_VISUALISER, COMPARISON_EXPLORER, CLASSIFICATION_TREE, TIMELINE_EXPLORER, DATA_EXPLORER, MEASUREMENT_TOOL, PREDICTION_CHALLENGE, MISCONCEPTION_VISUALISER, FUTURE_3D_MODEL }
enum class InteractionMode { GUIDED, EXPLORE, CHALLENGE, ASSESSMENT }
enum class InteractiveControlType { SLIDER, TOGGLE, BUTTON, DROPDOWN, DRAGGABLE_OBJECT, ROTATION, ZOOM, PAN, TIMELINE_SCRUBBER, NUMBER_INPUT, FORMULA_VARIABLE, LAYER_SELECTOR, MEASUREMENT_PROBE }
enum class InteractiveOutputType { NUMERIC_VALUE, GRAPH, DIRECTION, STATE, CATEGORY, PROCESS_STAGE, FORMULA_RESULT, OBSERVATION, MEASUREMENT, COMPARISON }

data class InteractionCompletionRequirement(val minimumInteractions:Int=1,val requiresPrediction:Boolean=false,val requiresObservation:Boolean=false,val requiresChallenge:Boolean=false)
data class InteractionAccessibilityRequirement(val requiresTextAlternative:Boolean=true,val requiresDynamicState:Boolean=true,val requiresReducedMotion:Boolean=true,val requiresColourIndependentMeaning:Boolean=true)
data class CurriculumInteractionProfile(val conceptId:String,val subject:SchoolSubject,val classLevels:Set<SchoolClassLevel>,val tier:InteractionTier,val requiredVisualTypes:Set<InteractiveVisualType>,val activityIds:List<String>,val explanationSectionIds:List<String>,val completionRequirement:InteractionCompletionRequirement,val accessibilityRequirement:InteractionAccessibilityRequirement,val reviewStatus:ScientificReviewStatus)
data class InteractiveControlDefinition(val id:String,val label:String,val type:InteractiveControlType,val variableId:String?,val minimum:Double?,val maximum:Double?,val step:Double?,val unit:String?,val defaultValue:Double?,val changesModelState:Boolean,val affectedVisualIds:Set<String>,val accessibilityLabel:String)
data class InteractivePreset(val id:String,val title:String,val values:Map<String,Double>)
data class InteractiveOutputDefinition(val id:String,val label:String,val variableId:String?,val unit:String?,val outputType:InteractiveOutputType,val explanationTemplate:String)
data class PredictionPrompt(val id:String,val prompt:String,val expectedObservation:String)
data class ObservationPrompt(val id:String,val prompt:String,val expectedEvidence:String)
data class InteractiveChallenge(val id:String,val title:String,val instruction:String,val successConditionId:String)
sealed interface ContentVisualAction { data class HighlightPart(val partId:String):ContentVisualAction;data class FocusControl(val controlId:String):ContentVisualAction;data class ApplyPreset(val presetId:String):ContentVisualAction;data class PlayStage(val stageId:String):ContentVisualAction;data class ShowLayer(val layerId:String):ContentVisualAction;data class FocusGraphRange(val rangeId:String):ContentVisualAction;data object Reset:ContentVisualAction }
data class ContentVisualLink(val explanationSectionId:String,val activityId:String,val visualTargetId:String?,val action:ContentVisualAction,val instructionalPrompt:String,val expectedObservation:String?)
data class InteractionAccessibilityDefinition(val summary:String,val dynamicStateTemplate:String,val controlDescriptions:Map<String,String>,val nonAnimatedSteps:List<String>,val supportsReducedMotion:Boolean,val supportsHighContrast:Boolean,val colourIndependentMeaning:Boolean)
data class InteractionCompletionPolicy(val minimumInteractions:Int,val requiresPrediction:Boolean,val requiresObservation:Boolean,val requiresChallenge:Boolean,val requiresReset:Boolean=true)

data class CurriculumInteractiveActivity(val id:String,val conceptId:String,val subject:SchoolSubject,val title:String,val visualType:InteractiveVisualType,val supportedModes:Set<InteractionMode>,val learningObjectives:List<String>,val instructions:List<String>,val controls:List<InteractiveControlDefinition>,val presets:List<InteractivePreset>,val measurableOutputs:List<InteractiveOutputDefinition>,val predictionPrompts:List<PredictionPrompt>,val observationPrompts:List<ObservationPrompt>,val challenges:List<InteractiveChallenge>,val contentLinks:List<ContentVisualLink>,val accessibility:InteractionAccessibilityDefinition,val completionPolicy:InteractionCompletionPolicy,val route:String,val reviewStatus:ScientificReviewStatus){
 val hasReset get()=!completionPolicy.requiresReset||presets.isNotEmpty()
 fun functionalFor(owner:SchoolSubject)=subject==owner&&route.isNotBlank()&&"/${subject.name.lowercase()}/" in route&&learningObjectives.isNotEmpty()&&supportedModes.isNotEmpty()&&controls.all{it.changesModelState&&it.affectedVisualIds.isNotEmpty()}&&hasReset&&(predictionPrompts.isNotEmpty()||observationPrompts.isNotEmpty()||challenges.isNotEmpty())&&accessibility.summary.isNotBlank()&&accessibility.dynamicStateTemplate.isNotBlank()&&reviewStatus==ScientificReviewStatus.VERIFIED
}

/** Migrates the working learner activities into production-verifiable curriculum records. */
object CurriculumInteractionBridge {
 val activities:List<CurriculumInteractiveActivity> by lazy { ConceptExperienceRegistry.experiences.map(::fromExperience) }
 val profiles:List<CurriculumInteractionProfile> by lazy { activities.map{a->val experience=ConceptExperienceRegistry.get(a.conceptId)!!;CurriculumInteractionProfile(a.conceptId,a.subject,experience.classLevels,InteractionTier.TIER_A_FULL_SIMULATION,setOf(a.visualType,InteractiveVisualType.PREDICTION_CHALLENGE),listOf(a.id),experience.contentSections.map{it.id},InteractionCompletionRequirement(a.completionPolicy.minimumInteractions,a.completionPolicy.requiresPrediction,a.completionPolicy.requiresObservation,a.completionPolicy.requiresChallenge),InteractionAccessibilityRequirement(),a.reviewStatus)} }
 fun activity(id:String)=activities.singleOrNull{it.id==id}
 private fun controlType(c:ActivityControl)=when{c.minimum==0.0&&c.maximum==1.0&&c.step==1.0->InteractiveControlType.TOGGLE;"phase" in c.id||"stage" in c.id->InteractiveControlType.TIMELINE_SCRUBBER;else->InteractiveControlType.SLIDER}
 private fun visualType(d:ActivityDefinition)=when{d.activityId.contains("motion")||d.activityId.contains("coordinate")||d.activityId.contains("probability")->InteractiveVisualType.LIVE_GRAPH;d.activityId.contains("cell-division")||d.activityId.contains("circulation")->InteractiveVisualType.PROCESS_STEPPER;else->InteractiveVisualType.VARIABLE_SIMULATION}
 private fun fromExperience(e:InteractiveConceptExperience):CurriculumInteractiveActivity{
  val d=ReferenceActivityRegistry.definitions.single{it.activityId==e.activities.single().activityId};val initial=d.compute(d.controls.associate{it.id to it.initial});val prediction=e.contentSections.flatMap{it.blocks}.filterIsInstance<InteractiveContentBlock.PredictionPrompt>();val observation=e.contentSections.flatMap{it.blocks}.filterIsInstance<InteractiveContentBlock.ObservationPrompt>();val links=e.visualisationLinks.map{link->ContentVisualLink(link.contentSectionId,d.activityId,link.focusTargetId,link.focusTargetId?.let{target->if(d.controls.any{it.id==target})ContentVisualAction.FocusControl(target) else ContentVisualAction.HighlightPart(target)}?:ContentVisualAction.Reset,link.instructionalPrompt.orEmpty(),link.expectedObservation)}
  return CurriculumInteractiveActivity(d.activityId,d.conceptId,d.subject,d.title,visualType(d),setOf(InteractionMode.GUIDED,InteractionMode.EXPLORE,InteractionMode.CHALLENGE),d.learningObjectives,d.guidedInstructions,d.controls.map{c->InteractiveControlDefinition(c.id,c.label,controlType(c),c.id,c.minimum,c.maximum,c.step,c.unit,c.initial,true,setOf("${d.activityId}-visual"),c.spokenLabel)},d.presets.map{InteractivePreset(it.id,it.title,it.values)},initial.values.map{(id,value)->InteractiveOutputDefinition(id,initial.labels[id]?:id,id,initial.valueUnits[id],if(initial.points.isNotEmpty())InteractiveOutputType.GRAPH else InteractiveOutputType.NUMERIC_VALUE,"$id changes to {value} ${initial.valueUnits[id].orEmpty()}")},prediction.map{PredictionPrompt(it.id,it.prompt,it.revealExplanation)},observation.map{ObservationPrompt(it.id,it.prompt,it.expectedEvidence)},d.challenges.map{InteractiveChallenge(it.id,it.title,it.instruction,"model-predicate:${d.activityId}:${it.id}")},links,InteractionAccessibilityDefinition(d.accessibility.visualStateTemplate,initial.textAlternative,d.controls.associate{it.id to it.spokenLabel},initial.processSteps.ifEmpty{d.guidedInstructions},d.accessibility.reducedMotionSupported,d.accessibility.highContrastSupported,d.accessibility.colourIndependentIndicators),InteractionCompletionPolicy(d.completionPolicy.requiredInteractions,d.completionPolicy.requiresPrediction,d.completionPolicy.requiresObservation,d.completionPolicy.requiresChallenge),"/${d.subject.name.lowercase()}/interactive/${d.activityId}",ScientificReviewStatus.VERIFIED)
 }
}
