package com.indianservers.aiexplorer.curriculum.interactive

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.CurriculumProductionBatchPlanner
import com.indianservers.aiexplorer.curriculum.production.ScientificReviewStatus
import java.time.LocalDate

enum class InteractionCoverageStatus { COMPLETE, PARTIAL, TEXT_ONLY, STATIC_ONLY, PLACEHOLDER, BROKEN, MISSING, NOT_APPLICABLE, REQUIRES_REVIEW }
enum class InteractionCapability { FUNCTIONAL_CONTROL, LIVE_OUTPUT, GUIDED_MODE, EXPLORE_MODE, CHALLENGE_MODE, PREDICTION, OBSERVATION, RESET, ACCESSIBLE_ALTERNATIVE, CONTENT_LINK, VERIFIED_REVIEW }
data class InteractionCoverageMapping(val conceptId:String,val subject:SchoolSubject,val tier:InteractionTier,val status:InteractionCoverageStatus,val activityIds:List<String>,val missingCapabilities:Set<InteractionCapability>,val reviewNotes:List<String>)
data class InteractionAuditSummary(val totalConcepts:Int,val assessableConcepts:Int,val complete:Int,val partial:Int,val missing:Int,val broken:Int,val staticOnly:Int,val textOnly:Int)
data class InteractionAuditReport(val generatedOn:LocalDate,val mappings:List<InteractionCoverageMapping>,val summary:InteractionAuditSummary)

object CurriculumInteractionAuditor {
 private val a=mapOf(
  SchoolSubject.MATHEMATICS to mapOf("linear equation" to "math-linear-equation-balance","triangle" to "math-triangle-lab","coordinate" to "math-coordinate-geometry","trigon" to "math-right-triangle-trig","probability" to "math-probability-experiment"),
  SchoolSubject.PHYSICS to mapOf("motion" to "physics-motion-graphs","force" to "physics-newton-second-law","wave" to "physics-wave-speed","sound" to "physics-wave-speed","electric" to "physics-electric-circuits","light" to "physics-reflection-refraction","optic" to "physics-reflection-refraction"),
  SchoolSubject.CHEMISTRY to mapOf("atom" to "chemistry-atom-builder","period" to "chemistry-periodic-trends","bond" to "chemistry-bonding","gas" to "chemistry-gas-laws","acid" to "chemistry-titration","equilibrium" to "chemistry-titration"),
  SchoolSubject.BIOLOGY to mapOf("fundamental unit" to "biology-cell-explorer","cell: the unit" to "biology-cell-explorer","cell cycle" to "biology-cell-division","circulation" to "biology-circulation","life processes" to "biology-circulation","inheritance" to "biology-mendelian-genetics","heredity" to "biology-mendelian-genetics"))
 private fun related(subject:SchoolSubject,title:String)=a.getValue(subject).filterKeys{title.lowercase().contains(it)}.values.distinct().mapNotNull(CurriculumInteractionBridge::activity)
 private fun tier(subject:SchoolSubject,title:String)=if(related(subject,title).isNotEmpty())InteractionTier.TIER_A_FULL_SIMULATION else if(listOf("process","cycle","reaction","reproduction","classification").any{title.contains(it,true)})InteractionTier.TIER_B_VISUAL_PROCESS else InteractionTier.TIER_C_PRACTICE_INTERACTION
 private fun missing(activity:CurriculumInteractiveActivity?,owner:SchoolSubject):Set<InteractionCapability>{if(activity==null)return InteractionCapability.entries.toSet();return buildSet{if(activity.controls.any{!it.changesModelState||it.affectedVisualIds.isEmpty()})add(InteractionCapability.FUNCTIONAL_CONTROL);if(activity.measurableOutputs.isEmpty())add(InteractionCapability.LIVE_OUTPUT);if(InteractionMode.GUIDED !in activity.supportedModes)add(InteractionCapability.GUIDED_MODE);if(InteractionMode.EXPLORE !in activity.supportedModes)add(InteractionCapability.EXPLORE_MODE);if(InteractionMode.CHALLENGE !in activity.supportedModes)add(InteractionCapability.CHALLENGE_MODE);if(activity.predictionPrompts.isEmpty())add(InteractionCapability.PREDICTION);if(activity.observationPrompts.isEmpty())add(InteractionCapability.OBSERVATION);if(!activity.hasReset)add(InteractionCapability.RESET);if(activity.accessibility.summary.isBlank())add(InteractionCapability.ACCESSIBLE_ALTERNATIVE);if(activity.contentLinks.isEmpty())add(InteractionCapability.CONTENT_LINK);if(activity.reviewStatus!=ScientificReviewStatus.VERIFIED)add(InteractionCapability.VERIFIED_REVIEW);if(!activity.functionalFor(owner))add(InteractionCapability.FUNCTIONAL_CONTROL)}}
 fun audit(manifests:List<OfficialCurriculum> = CbseNcert2026Curriculum.manifests,productionChapters:List<com.indianservers.aiexplorer.curriculum.production.SubjectOwnedCurriculumChapter> = CurriculumProductionBatchPlanner.chapters):InteractionAuditReport{
  val production=productionChapters.flatMap{it.interactiveActivities}.associateBy{it.conceptId};val official=manifests.flatMap{m->m.units.flatMap{it.chapters}.flatMap{chapter->chapter.topics.map{topic->val t=tier(m.subject,chapter.officialTitle);val activity=production[topic.id]?:related(m.subject,chapter.officialTitle).firstOrNull();val gaps=missing(activity,m.subject);val excluded=topic.currentAssessmentStatus in setOf(AssessmentStatus.EXCLUDED_FOR_CURRENT_SESSION,AssessmentStatus.DELETED_FROM_CURRENT_EDITION);val review=topic.currentAssessmentStatus in setOf(AssessmentStatus.REQUIRES_MANUAL_REVIEW,AssessmentStatus.SOURCE_UNCLEAR);val status=when{excluded->InteractionCoverageStatus.NOT_APPLICABLE;review->InteractionCoverageStatus.REQUIRES_REVIEW;activity==null->InteractionCoverageStatus.MISSING;gaps.isNotEmpty()->InteractionCoverageStatus.BROKEN;production[topic.id]!=null->InteractionCoverageStatus.COMPLETE;else->InteractionCoverageStatus.PARTIAL};InteractionCoverageMapping(topic.id,m.subject,t,status,listOfNotNull(activity?.id),gaps,if(status==InteractionCoverageStatus.PARTIAL)listOf("A functional sub-concept activity exists, but the broad chapter-core topic is not claimed complete.") else emptyList())}}}
  val reference=CurriculumInteractionBridge.profiles.map{p->val activity=CurriculumInteractionBridge.activity(p.activityIds.single());val gaps=missing(activity,p.subject);InteractionCoverageMapping(p.conceptId,p.subject,p.tier,if(gaps.isEmpty())InteractionCoverageStatus.COMPLETE else InteractionCoverageStatus.BROKEN,p.activityIds,gaps,emptyList())};val mappings=official+reference;val assessable=manifests.flatMap{it.units}.flatMap{it.chapters}.flatMap{it.topics}.count{it.currentAssessmentStatus==AssessmentStatus.INCLUDED_AND_ASSESSABLE};return InteractionAuditReport(LocalDate.now(),mappings,InteractionAuditSummary(mappings.size,assessable,mappings.count{it.status==InteractionCoverageStatus.COMPLETE},mappings.count{it.status==InteractionCoverageStatus.PARTIAL},mappings.count{it.status==InteractionCoverageStatus.MISSING},mappings.count{it.status==InteractionCoverageStatus.BROKEN},mappings.count{it.status==InteractionCoverageStatus.STATIC_ONLY},mappings.count{it.status==InteractionCoverageStatus.TEXT_ONLY}))
 }
}
