package com.indianservers.aiexplorer

import androidx.lifecycle.SavedStateHandle
import com.indianservers.aiexplorer.core.*
import com.indianservers.aiexplorer.spatial.*
import com.indianservers.aiexplorer.workspace.*
import com.indianservers.aiexplorer.arengine.interaction.*
import org.junit.Assert.*
import org.junit.Test

class ArCadPhaseTwoTest {
    private val zero=Vec3(0.0,0.0,0.0)
    private fun scene(vm:ExplorerViewModel)=ArCadSceneCompiler().build(SpatialRenderScene("test",emptyList()),vm.state)
    private fun node(vm:ExplorerViewModel,id:String,type:ArCadType,params:Map<String,String> = arCadDefaults(type),deps:List<String> = emptyList()) { vm.upsertArCadNode(ArCadNode(id,type,params,deps)) }
    private fun cube():SpatialGeometry { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"box",ArCadType.Cuboid); return scene(vm).primitives.single().geometry }
    @Test fun expressionsAreExactAndSafe() { assertEquals(Math.PI/2,ArCadTopology.number("\u03c0/2"),1e-12); assertEquals(kotlin.math.sqrt(2.0),ArCadTopology.number("sqrt(2)"),1e-12); assertEquals(.75,ArCadTopology.number("3/4"),0.0); assertTrue(runCatching { ArCadTopology.number("1/0") }.isFailure) }
    @Test fun cubeFaceIsConnectedQuadAndMovesOnlySharedVertices() {
        val g=cube(); val ids=ArCadTopology.vertices(g,ArSubObjectKind.Face,0); assertEquals(4,ids.size)
        val moved=ArCadTopology.move(g,ArSubObjectKind.Face,0,Vec3(0.0,.1,.2)); assertEquals(g.vertices.size,moved.vertices.size); assertEquals(g.triangles,moved.triangles)
        g.vertices.indices.forEach { i -> assertEquals(g.vertices[i]+if(i in ids) Vec3(0.0,.1,.2) else zero,moved.vertices[i]) }
    }
    @Test fun edgeMoveSharesVerticesAndInspectorMeasuresExactLength() { val g=cube(); val ids=ArCadTopology.vertices(g,ArSubObjectKind.Edge,0); assertEquals(2,ids.size); val moved=ArCadTopology.move(g,ArSubObjectKind.Edge,0,Vec3(.1,.1,.1)); assertEquals(g.triangles,moved.triangles); assertEquals(ArCadTopology.inspector(g,ArSubObjectKind.Edge,0)["Length"],ArCadTopology.inspector(moved,ArSubObjectKind.Edge,0)["Length"]) }
    @Test fun invalidCollapsedFaceIsRejected() { val g=cube(); assertTrue(runCatching { ArCadTopology.move(g,ArSubObjectKind.Face,0,zero,scale=0.0) }.isFailure) }
    @Test fun meshAndNodesRoundTrip() { val g=cube(); assertEquals(g.copy(pointRadius=.05),ArCadTopology.decode(ArCadTopology.encode(g))); val n=ArCadNode("a",ArCadType.FunctionSurface,mapOf("expressionZ" to "a*(x^2+y^2)+c"),listOf("p")); assertEquals(n,ArCadNode.decode("a",n.encode())) }
    @Test fun dependenciesPropagateTransformAndDirectPointEdit() {
        val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Point); node(vm,"b",ArCadType.Point,mapOf("x" to "2","y" to "0","z" to "0")); node(vm,"line",ArCadType.Segment,deps=listOf("a","b")); node(vm,"m",ArCadType.Midpoint,deps=listOf("a","b")); node(vm,"sphere",ArCadType.Sphere,deps=listOf("m"))
        vm.updateArGraphObject("a","Move A") { it.copy(position=Vec3(0.0,2.0,0.0)) }
        assertEquals(Vec3(1.0,1.0,0.0),scene(vm).primitives.first { it.id=="m" }.geometry.vertices[0])
        vm.commitArCadGeometry("b",SpatialGeometry(listOf(Vec3(4.0,0.0,0.0))),"Move B")
        val s=scene(vm); assertEquals(Vec3(2.0,1.0,0.0),s.primitives.first { it.id=="m" }.geometry.vertices[0]); assertEquals(Vec3(4.0,0.0,0.0),s.primitives.first { it.id=="line" }.geometry.vertices[1])
        vm.undo(); assertEquals(Vec3(1.0,1.0,0.0),scene(vm).primitives.first { it.id=="m" }.geometry.vertices[0])
    }
    @Test fun cyclesAreRejectedWithoutChangingWorkspace() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Point); node(vm,"b",ArCadType.Point,deps=listOf("a")); val before=vm.state; assertTrue(runCatching { node(vm,"a",ArCadType.Point,deps=listOf("b")) }.isFailure); assertEquals(before,vm.state) }
    @Test fun domainsAreValidatedBeforeCommit() { val vm=ExplorerViewModel(SavedStateHandle()); assertTrue(runCatching { node(vm,"s",ArCadType.FunctionSurface,arCadDefaults(ArCadType.FunctionSurface)+mapOf("uMin" to "5","uMax" to "1")) }.isFailure); assertTrue(vm.state.arCadNodes().isEmpty()) }
    @Test fun allCorePrimitivesProduceFiniteGeometry() { ArCadType.entries.filter { it !in setOf(ArCadType.Midpoint,ArCadType.Intersection) }.forEach { type -> val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"object",type); val g=scene(vm).primitives.first().geometry; assertTrue("$type",g.vertices.isNotEmpty()); ArCadTopology.validate(g) } }
    @Test fun cachedUnchangedNodeReusesGeometry() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"s",ArCadType.Sphere); val compiler=ArCadSceneCompiler(); val src=SpatialRenderScene("test",emptyList()); val a=compiler.build(src,vm.state).primitives.single().geometry; vm.updateArGraphObject("s","Move") { it.copy(position=Vec3(1.0,0.0,0.0)) }; assertSame(a,compiler.build(src,vm.state).primitives.single().geometry) }
    @Test fun fixedLengthAndParallelAreRealPersistentConstraints() { val g=SpatialGeometry(listOf(zero,Vec3(2.0,1.0,0.0),Vec3(0.0,2.0,0.0),Vec3(0.0,4.0,0.0)),lines=listOf(0 to 1,2 to 3)); val c=listOf(ArCadConstraint("p",ArCadConstraintKind.Parallel,listOf(0,1),listOf(2,3)),ArCadConstraint("l",ArCadConstraintKind.FixedLength,listOf(0,1),value=3.0)); val solved=ArCadConstraintSolver.solve(g,c); assertEquals(Vec3(0.0,3.0,0.0),solved.vertices[1]) }
    @Test fun perpendicularAndEqualLengthSolve() { val g=SpatialGeometry(listOf(zero,Vec3(1.0,1.0,0.0),Vec3(0.0,2.0,0.0),Vec3(0.0,4.0,0.0))); val result=ArCadConstraintSolver.solve(g,listOf(ArCadConstraint("p",ArCadConstraintKind.Perpendicular,listOf(0,1),listOf(2,3)),ArCadConstraint("e",ArCadConstraintKind.EqualLength,listOf(0,1),listOf(2,3)))); assertEquals(0.0,result.vertices[1].y,1e-8); assertEquals(2.0,result.vertices[1].magnitude(),1e-8) }
    @Test fun lockedVerticesCannotDrift() { val baseline=SpatialGeometry(listOf(zero,Vec3(1.0,0.0,0.0))); val moved=baseline.copy(vertices=listOf(Vec3(4.0,3.0,2.0),baseline.vertices[1])); assertEquals(zero,ArCadConstraintSolver.solve(moved,listOf(ArCadConstraint("l",ArCadConstraintKind.Locked,listOf(0))),baseline).vertices[0]) }
    @Test fun constraintAddRemoveAndMeshEditUndo() { val vm=ExplorerViewModel(SavedStateHandle()); val g=SpatialGeometry(listOf(zero,Vec3(2.0,0.0,0.0)),lines=listOf(0 to 1)); vm.addArCadConstraint("s",g,ArCadConstraint("l",ArCadConstraintKind.FixedLength,listOf(0,1),value=1.0)); assertEquals(1.0,ArCadTopology.decode(vm.state.labSessionValues.getValue("arCad.mesh.s")).vertices[1].x,0.0); vm.removeArCadConstraint("s","l"); assertTrue(vm.arCadConstraints("s").isEmpty()); vm.undo(); assertEquals(1,vm.arCadConstraints("s").size); vm.undo(); assertNull(vm.state.labSessionValues["arCad.mesh.s"]); vm.redo(); assertEquals(1,vm.arCadConstraints("s").size) }
    @Test fun snapsUseActualVertexMidpointPlaneAndIntersection() { val segment=SpatialGeometry(listOf(Vec3(1.0,1.0,1.0),Vec3(3.0,1.0,1.0)),lines=listOf(0 to 1)); assertEquals(Vec3(1.0,1.0,1.0),ArCadSnapping.snap(Vec3(1.01,1.01,1.01),listOf(segment))!!.point); assertEquals("MIDPOINT",ArCadSnapping.snap(Vec3(2.0,1.0,1.0),listOf(segment),grid=.37)!!.label); val crossing=SpatialGeometry(listOf(Vec3(2.0,0.0,1.0),Vec3(2.0,2.0,1.0)),lines=listOf(0 to 1)); assertEquals(Vec3(2.0,1.0,1.0),ArCadSnapping.snap(Vec3(2.0,1.0,1.0),listOf(segment,crossing))!!.point) }
    @Test fun vectorCalculationsAndAnglesAreExact() { val a=Vec3(1.0,0.0,0.0); val b=Vec3(0.0,1.0,0.0); assertEquals(Vec3(0.0,0.0,1.0),ArCadVectorMath.calculate(a,b)["Cross product"]); assertEquals(Math.PI/2,ArCadVectorMath.angle(a,b),1e-12); assertEquals(zero,ArCadVectorMath.calculate(a,b)["Projection"]) }
    @Test fun sphereAndPlaneMeasurementsTrackPose() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"s",ArCadType.Sphere); val g=scene(vm).primitives.single().geometry; val values=arCadEquationAndMeasurements(vm.state.arCadNodes().getValue("s"),g,ArGraphObjectState(position=Vec3(2.0,0.0,0.0),scale=2.0)); assertEquals("2.0",values["Radius"]); assertTrue(values.getValue("Sphere equation").contains("=4.0")); assertFalse(arCadEquationAndMeasurements(vm.state.arCadNodes().getValue("s"),g,ArGraphObjectState(),analytic=false).containsKey("Sphere equation")) }
    @Test fun equalRadiusRelationshipPropagatesAndTangencyIsReal() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Sphere,arCadDefaults(ArCadType.Sphere)+("radius" to "2")); node(vm,"b",ArCadType.Sphere,arCadDefaults(ArCadType.Sphere)+mapOf("radiusReference" to "a","tangentReference" to "a")); val s=scene(vm); val a=s.primitives.first { it.id=="a" }; val b=s.primitives.first { it.id=="b" }; assertEquals(a.metadata.getValue("radius").toDouble(),b.metadata.getValue("radius").toDouble(),0.0); val center=(b.geometry.vertices.minOf { it.x }+b.geometry.vertices.maxOf { it.x })*.5; assertEquals(4.0,center,1e-8) }
    @Test fun movingCurvePointUsesTheParameter() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"c",ArCadType.Curve,arCadDefaults(ArCadType.Curve)+("parameterT" to "pi")); val p=scene(vm).primitives.first { it.id.endsWith("parameter-point") }.geometry.vertices.single(); assertEquals(-1.0,p.x,1e-12); assertEquals(Math.PI/4,p.z,1e-12) }

    @Test fun radiusHandleIsOneUndoCommandAndUpdatesEquation() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"s",ArCadType.Sphere); vm.beginArGraphObjectGesture(); vm.previewArCadRadius("s",.5); vm.previewArCadRadius("s",1.0); vm.endArGraphObjectGesture(); assertEquals("2.0",vm.state.arCadNodes().getValue("s").parameters["radius"]); vm.undo(); assertEquals("1",vm.state.arCadNodes().getValue("s").parameters["radius"]); vm.redo(); assertEquals("2.0",vm.state.arCadNodes().getValue("s").parameters["radius"]) }
    @Test fun duplicateKeepsEditedMeshAndIsAtomicUndo() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"box",ArCadType.Cuboid); val g=scene(vm).primitives.single().geometry; vm.commitArCadGeometry("box",ArCadTopology.move(g,ArSubObjectKind.Vertex,0,Vec3(.1,.1,.1)),"Reshape"); val copy=vm.duplicateArCadObject("box"); assertEquals(vm.state.labSessionValues["arCad.mesh.box"],vm.state.labSessionValues["arCad.mesh.$copy"]); vm.undo(); assertFalse(vm.state.arCadNodes().containsKey(copy)); assertNotNull(vm.state.labSessionValues["arCad.mesh.box"]) }
    @Test fun groupMovePreservesDependenciesAndUndo() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Point); node(vm,"b",ArCadType.Point,mapOf("x" to "2","y" to "0","z" to "0")); node(vm,"m",ArCadType.Midpoint,deps=listOf("a","b")); val nodes=vm.state.arCadNodes(); val source=scene(vm); vm.executeArCadValues("Group") { it+("arCad.group.test" to "a,b,m") }; vm.executeArCadValues("Move group") { arCadGroupTransforms(source,nodes,it,setOf("a","b","m"),Vec3(0.0,2.0,0.0),zero,1.0) }; assertEquals(Vec3(1.0,2.0,0.0),scene(vm).primitives.first { it.id=="m" }.geometry.vertices.single()); assertEquals(listOf("a","b"),vm.state.arCadNodes().getValue("m").dependencies); vm.undo(); assertEquals(Vec3(1.0,0.0,0.0),scene(vm).primitives.first { it.id=="m" }.geometry.vertices.single()) }
    @Test fun dependentObjectsDisappearWhenAncestorIsDeleted() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Point); node(vm,"b",ArCadType.Point,deps=listOf("a")); node(vm,"s",ArCadType.Sphere,deps=listOf("b")); vm.updateArGraphObject("a","Delete") { it.copy(deleted=true) }; assertTrue(scene(vm).withArGraphObjects(vm.state,ArGraphGeometryCache()).primitives.none { it.visible }); vm.undo(); assertTrue(scene(vm).withArGraphObjects(vm.state,ArGraphGeometryCache()).primitives.all { it.visible }) }
    @Test fun pointOnPlaneAndLineConstraintsProjectExactly() { val g=SpatialGeometry(listOf(Vec3(1.0,2.0,3.0),zero,Vec3(2.0,0.0,0.0),Vec3(0.0,2.0,0.0))); val plane=ArCadConstraintSolver.solve(g,listOf(ArCadConstraint("p",ArCadConstraintKind.PointOnPlane,listOf(0),listOf(1,2,3)))); assertEquals(Vec3(1.0,2.0,0.0),plane.vertices[0]); val line=ArCadConstraintSolver.solve(g,listOf(ArCadConstraint("l",ArCadConstraintKind.PointOnLine,listOf(0),listOf(1,2)))); assertEquals(Vec3(1.0,0.0,0.0),line.vertices[0]) }
    @Test fun conflictingLockedAndLengthConstraintIsRejected() { val g=SpatialGeometry(listOf(zero,Vec3(1.0,0.0,0.0))); assertTrue(runCatching { ArCadConstraintSolver.solve(g,listOf(ArCadConstraint("k",ArCadConstraintKind.Locked,listOf(0,1)),ArCadConstraint("l",ArCadConstraintKind.FixedLength,listOf(0,1),value=2.0))) }.isFailure) }
    @Test fun exactPlaneNormalRemainsUnitLengthAfterRotation() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"p",ArCadType.Plane); val g=scene(vm).primitives.single().geometry; val values=arCadEquationAndMeasurements(vm.state.arCadNodes().getValue("p"),g,ArGraphObjectState(position=Vec3(0.0,0.0,2.0),rotation=Vec3(20.0,30.0,10.0))); val normal=values.getValue("Plane normal").split(',').map { it.trim().toDouble() }; assertEquals(1.0,Vec3(normal[0],normal[1],normal[2]).magnitude(),1e-12) }
    @Test fun actualFaceHighlightContainsOnlySelectedFaceTriangles() { val g=cube(); val obj=SpatialPrimitive("box",SpatialPrimitiveKind.Solid,g,com.indianservers.aiexplorer.spatial.SpatialMaterial("box",listOf(1f,1f,1f,1f))); val select=ArSelectionEngine.select(ArSelectionState(),ArPickHit("box",ArSubObjectKind.Face,0,0.0,com.indianservers.aiexplorer.arengine.contract.ArVector3.Zero),false); val highlighted=arCadHighlight(SpatialRenderScene("scene",listOf(obj)),select).primitives.last(); assertEquals(6,highlighted.geometry.triangles.size); assertFalse(highlighted.selectable); assertEquals(g.vertices,highlighted.geometry.vertices) }
    @Test fun liveDistanceMeasurementUpdatesAfterMovingPoint() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Point); node(vm,"b",ArCadType.Point,mapOf("x" to "2","y" to "0","z" to "0")); val measure=ArCadMeasurement(ArCadMeasureKind.Distance,listOf("a","b")); assertEquals(2.0,measure.value(scene(vm).withArGraphObjects(vm.state,ArGraphGeometryCache())),0.0); vm.updateArGraphObject("b","Move") { it.copy(position=Vec3(1.0,0.0,0.0)) }; assertEquals(3.0,measure.value(scene(vm).withArGraphObjects(vm.state,ArGraphGeometryCache())),0.0) }

    @Test fun groupsRotateAndScaleBothDerivedPointsAndSphereRadius() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"a",ArCadType.Point); node(vm,"b",ArCadType.Point,mapOf("x" to "2","y" to "0","z" to "0")); node(vm,"m",ArCadType.Midpoint,deps=listOf("a","b")); node(vm,"s",ArCadType.Sphere,deps=listOf("m")); val nodes=vm.state.arCadNodes(); val source=scene(vm); vm.executeArCadValues("Transform group") { arCadGroupTransforms(source,nodes,it,nodes.keys,zero,Vec3(0.0,0.0,90.0),2.0) }; val result=scene(vm).withArGraphObjects(vm.state,ArGraphGeometryCache()); val m=result.primitives.first { it.id=="m" }.geometry.vertices.single(); val point=arCadWorldGeometry(SpatialGeometry(listOf(m)),vm.state.arGraphObject("m")).vertices.single(); assertEquals(1.0,point.x,1e-8); assertEquals(0.0,point.y,1e-8); val sphere=result.primitives.first { it.id=="s" }; val values=arCadEquationAndMeasurements(nodes.getValue("s"),sphere.geometry,vm.state.arGraphObject("s")); assertEquals("2.0",values["Radius"]) }
    @Test fun projectPersistenceRetainsCADRelationshipsGroupsAndMeshes() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"box",ArCadType.Cuboid); val g=scene(vm).primitives.single().geometry; vm.commitArCadGeometry("box",ArCadTopology.move(g,ArSubObjectKind.Vertex,0,Vec3(.1,.1,.1)),"Edit"); vm.executeArCadValues("Group") { it+("arCad.group.test" to "box,other")+("arCad.measure.test" to ArCadMeasurement(ArCadMeasureKind.Distance,listOf("box","other")).encode()) }; val recovered=WorkspaceSnapshotCodec.decode(WorkspaceSnapshotCodec.encode(vm.state)).state!!; assertEquals(vm.state.labSessionValues,recovered.labSessionValues); assertEquals(vm.state.arCadNodes(),recovered.arCadNodes()) }

    @Test fun numericVectorEndpointEditRebuildsArrowheadAndKeepsUndo() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"v",ArCadType.Vector); val original=scene(vm).primitives.single().geometry; val edited=original.copy(vertices=original.vertices.mapIndexed { i,p -> if(i==1) Vec3(0.0,0.0,3.0) else p }); vm.commitArCadGeometry("v",edited,"Set vector endpoint"); assertEquals("3.0",vm.state.arCadNodes().getValue("v").parameters["end.z"]); val g=scene(vm).primitives.single().geometry; assertEquals(Vec3(0.0,0.0,3.0),g.vertices[1]); assertNotEquals(original.vertices[2],g.vertices[2]); vm.undo(); assertEquals(original,scene(vm).primitives.single().geometry) }
    @Test fun liveSliderDragIsOneUndoStep() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"s",ArCadType.FunctionSurface); val params=vm.state.arCadNodes().getValue("s").parameters; vm.previewArCadParameters("s",params+("parameter.a" to "2")); vm.previewArCadParameters("s",params+("parameter.a" to "3")); vm.endArGraphObjectGesture(); assertEquals("3",vm.state.arCadNodes().getValue("s").parameters["parameter.a"]); vm.undo(); assertEquals("1",vm.state.arCadNodes().getValue("s").parameters["parameter.a"]) }
    @Test fun movingCurvePointDoesNotRegenerateCurveMesh() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"c",ArCadType.Curve); val compiler=ArCadSceneCompiler(); val source=SpatialRenderScene("s",emptyList()); val first=compiler.build(source,vm.state).primitives.first().geometry; val n=vm.state.arCadNodes().getValue("c"); vm.upsertArCadNode(n.copy(parameters=n.parameters+("parameterT" to "1"))); assertSame(first,compiler.build(source,vm.state).primitives.first().geometry) }

    @Test fun selectionTapDoesNotCreateAnUndoEntry() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"box",ArCadType.Cuboid); val before=vm.state; val g=scene(vm).primitives.single().geometry; vm.beginArGraphObjectGesture(); vm.previewArCadSubObject("box",g,ArSubObjectKind.Vertex,0,Vec3(0.0,-0.0,0.0),zero,1.0); vm.endArGraphObjectGesture(); assertEquals(before,vm.state); vm.undo(); assertTrue(vm.state.arCadNodes().isEmpty()) }
    @Test fun wireOnlySurfaceRetainsSelectableFaces() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"s",ArCadType.FunctionSurface,arCadDefaults(ArCadType.FunctionSurface)+("filled" to "false")); val obj=scene(vm).primitives.single(); assertTrue(obj.geometry.triangles.isNotEmpty()); assertTrue(obj.geometry.lines.isNotEmpty()); assertEquals("false",obj.metadata["filled"]); assertTrue(obj.visible) }

    @Test fun extrusionUsesOutwardNormalAndPreservesClosedSolidVolume() { val g=cube(); val result=SpatialMeshEditor.extrude(EditableSpatialMesh(g.vertices,g.triangles),ArCadTopology.face(g,0),1.0); val edited=SpatialGeometry(result.mesh.vertices,result.mesh.triangles); ArCadTopology.validate(edited); assertEquals(-2.0,edited.vertices.minOf { it.z },1e-8); val signed=edited.triangles.chunked(3).sumOf { f -> edited.vertices[f[0]].dot(AnalyticGeometry3D.cross(edited.vertices[f[1]],edited.vertices[f[2]]))/6.0 }; assertEquals(12.0,signed,1e-8) }

    @Test fun legacyEquationEditRebuildsGeometryAndUndoRestoresMeshEdits() { val vm=ExplorerViewModel(SavedStateHandle()); val id=vm.state.surfaceLayers.first().id; val g=ArMathWorkspaceBridge.build(ArMathWorkspaceMode.Graph3D,vm.state).scene.primitives.first { it.id==id }.geometry; vm.commitArCadGeometry(id,ArCadTopology.move(g,ArSubObjectKind.Vertex,0,Vec3(.01,.01,.1)),"Reshape surface"); val old=vm.state.labSessionValues.getValue("arCad.mesh.$id"); vm.setSurfaceExpression("x+y"); assertNull(vm.state.labSessionValues["arCad.mesh.$id"]); vm.undo(); assertEquals(old,vm.state.labSessionValues["arCad.mesh.$id"]); vm.redo(); assertNull(vm.state.labSessionValues["arCad.mesh.$id"]) }
    @Test fun opacityChangePreservesMeshEdits() { val vm=ExplorerViewModel(SavedStateHandle()); val id=vm.state.surfaceLayers.first().id; vm.commitArCadGeometry(id,SpatialGeometry(listOf(zero)),"Edit"); val old=vm.state.labSessionValues["arCad.mesh.$id"]; vm.replaceSurfaceLayers(vm.state.surfaceLayers.map { it.copy(opacity=.5) }); assertEquals(old,vm.state.labSessionValues["arCad.mesh.$id"]) }

    @Test fun objectLockAlsoBlocksNumericAndAnalyticEdits() { val vm=ExplorerViewModel(SavedStateHandle()); node(vm,"s",ArCadType.Sphere); val n=vm.state.arCadNodes().getValue("s"); val g=scene(vm).primitives.single().geometry; vm.updateArGraphObject("s","Lock") { it.copy(locked=true) }; val before=vm.state; vm.updateArGraphObject("s","Move") { it.copy(position=Vec3(1.0,2.0,3.0)) }; assertEquals(before,vm.state); assertTrue(runCatching { vm.upsertArCadNode(n.copy(parameters=n.parameters+("radius" to "3"))) }.isFailure); assertTrue(runCatching { vm.commitArCadGeometry("s",g,"Edit") }.isFailure); assertEquals(before,vm.state) }
}
