package com.indianservers.aiexplorer

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.interaction.FunctionalInteractiveActivity
import com.indianservers.aiexplorer.curriculum.interaction.ReferenceActivityRegistry
import com.indianservers.aiexplorer.curriculum.interactive.*
import com.indianservers.aiexplorer.curriculum.production.*
import org.junit.Assert.*
import org.junit.Test

class CurriculumInteractionProductionTest {
 private val manifests=CbseNcert2026Curriculum.manifests
 private val activities=CurriculumInteractionBridge.activities
 private val profiles=CurriculumInteractionBridge.profiles
 private val official=manifests.flatMap{it.units}.flatMap{it.chapters}.associateBy{it.id}

 @Test fun everyAssessableConceptHasInteractionProfile(){val report=CurriculumInteractionAuditor.audit();val expected=manifests.flatMap{it.units}.flatMap{it.chapters}.flatMap{it.topics}.filter{it.currentAssessmentStatus==AssessmentStatus.INCLUDED_AND_ASSESSABLE}.map{it.id}.toSet();assertTrue(report.mappings.map{it.conceptId}.toSet().containsAll(expected));assertEquals(175,report.summary.assessableConcepts)}
 @Test fun everyTierAConceptHasFunctionalInteractiveActivity(){val report=CurriculumInteractionAuditor.audit();report.mappings.filter{it.tier==InteractionTier.TIER_A_FULL_SIMULATION&&it.status !in setOf(InteractionCoverageStatus.REQUIRES_REVIEW,InteractionCoverageStatus.NOT_APPLICABLE)}.forEach{mapping->assertTrue(mapping.activityIds.isNotEmpty());mapping.activityIds.forEach{id->assertTrue(CurriculumInteractionBridge.activity(id)!!.functionalFor(mapping.subject))}}}
 @Test fun everyVerifiedControlChangesModelState(){activities.forEach{record->val definition=ReferenceActivityRegistry.definitions.single{it.activityId==record.id};record.controls.forEach{control->assertTrue(control.changesModelState);val engine=FunctionalInteractiveActivity(definition);val before=engine.snapshot.visual.values;val changed=if(control.defaultValue!=control.maximum)control.maximum!! else control.minimum!!;engine.setControl(control.id,changed);assertNotEquals("${record.id}/${control.id}",before,engine.snapshot.visual.values)}}}
 @Test fun everyInteractiveActivityHasObjectiveModesAndExplanationLinks(){activities.forEach{activity->assertTrue(activity.learningObjectives.isNotEmpty());assertTrue(activity.supportedModes.containsAll(setOf(InteractionMode.GUIDED,InteractionMode.EXPLORE,InteractionMode.CHALLENGE)));assertTrue(activity.contentLinks.isNotEmpty());assertTrue(activity.contentLinks.all{it.instructionalPrompt.isNotBlank()})}}
 @Test fun everySimulationHasResetAndEveryChallengeHasPredicate(){activities.forEach{activity->assertTrue(activity.hasReset);val source=ReferenceActivityRegistry.definitions.single{it.activityId==activity.id};activity.challenges.forEach{challenge->assertTrue(challenge.successConditionId.startsWith("model-predicate:${activity.id}:"));source.challenges.single{it.id==challenge.id}.isSatisfied(source.compute(source.controls.associate{it.id to it.initial}))}}}
 @Test fun predictionObservationAndAccessibilityAreComplete(){activities.forEach{activity->assertTrue(activity.predictionPrompts.all{it.expectedObservation.isNotBlank()});assertTrue(activity.observationPrompts.all{it.expectedEvidence.isNotBlank()});assertTrue(activity.accessibility.summary.isNotBlank());assertTrue(activity.accessibility.dynamicStateTemplate.isNotBlank());assertTrue(activity.accessibility.nonAnimatedSteps.isNotEmpty())}}
 @Test fun staticDiagramAndTitleOnlyActivityDoNotSatisfyInteractiveRequirement(){val chapter=CurriculumProductionBatchPlanner.chapters.first();val required=chapter.copy(activities=listOf("A plausible title"),interactiveActivities=emptyList(),interactionProfiles=emptyList(),requirements=chapter.requirements.copy(requiresInteractiveVisual=true));assertFalse(RequiredAssetType.INTERACTIVE_VISUAL in required.completedAssetTypes);val readiness=DerivedChapterCompletion.evaluate(required,official.getValue(required.curriculumNodeId));assertFalse(readiness.complete);assertTrue(RequiredAssetType.INTERACTIVE_VISUAL in readiness.missing)}
 @Test fun brokenControlsLinksAndOwnershipBlockReadiness(){val chapter=CurriculumProductionBatchPlanner.chapters.single{it.curriculumNodeId=="cbse-2026-c9-physics-c1"};val activity=chapter.interactiveActivities.single();val broken=activity.copy(subject=SchoolSubject.CHEMISTRY,controls=activity.controls.mapIndexed{i,c->if(i==0)c.copy(changesModelState=false)else c},contentLinks=activity.contentLinks.map{it.copy(explanationSectionId="missing")});val result=DerivedChapterCompletion.evaluate(chapter.copy(interactiveActivities=listOf(broken)),official.getValue(chapter.curriculumNodeId));assertFalse(result.complete);assertTrue(result.issues.any{"not subject-owned" in it});assertTrue(result.issues.any{"disconnected control" in it});assertTrue(result.issues.any{"missing explanation" in it})}
 @Test fun interactionRoutesRemainInsideOwningSubjectAndValidatorPasses(){assertTrue(activities.all{it.route.startsWith("/${it.subject.name.lowercase()}/")});val validation=CurriculumValidator.validateInteractions(manifests,activities);assertTrue(validation.errors.joinToString("\n"),validation.valid)}
 @Test fun diagramsRemainBackwardCompatibleAndSupportInteractiveMetadata(){val legacy=CurriculumProductionBatchPlanner.chapters.first().diagrams.first();assertTrue(legacy.supportsZoom&&legacy.supportsPan);assertTrue(legacy.selectableParts.isEmpty());val upgraded=legacy.copy(selectableParts=listOf(InteractiveDiagramPart("part","Part","Description","Function",legacy.conceptId)),layers=listOf(InteractiveDiagramLayer("labels","Labels",true)),linkedExplanationSectionIds=listOf(legacy.conceptId));assertEquals("part",upgraded.selectableParts.single().id);assertTrue(upgraded.layers.single().defaultVisible)}
 @Test fun productionChaptersAwardOnlyVerifiedFunctionalInteractionAssets(){val attached=CurriculumProductionBatchPlanner.chapters.filter{it.interactiveActivities.isNotEmpty()};assertEquals(4,attached.size);attached.forEach{chapter->assertTrue(RequiredAssetType.INTERACTIVE_VISUAL in chapter.completedAssetTypes);assertTrue(RequiredAssetType.PREDICTION_ACTIVITY in chapter.completedAssetTypes);assertTrue(RequiredAssetType.CHALLENGE_ACTIVITY in chapter.completedAssetTypes);assertTrue(RequiredAssetType.ACCESSIBLE_VISUAL_ALTERNATIVE in chapter.completedAssetTypes)}}
 @Test fun interactionCoverageImprovesAndGeneratedBatchIsDeterministic(){val before=CurriculumInteractionAuditor.audit(productionChapters=emptyList());val after=CurriculumInteractionAuditor.audit();assertEquals(4,after.summary.complete-before.summary.complete);val curriculum=CurriculumCoverageAuditor.audit(manifests,ProjectCurriculumInventory.build());val one=CurriculumProductionBatchPlanner.selectInteractionProductionBatch(curriculum,after,2);val two=CurriculumProductionBatchPlanner.selectInteractionProductionBatch(curriculum,after,2);assertEquals(one,two);assertTrue(one.subjectItems.values.all{it.size<=2});println("INTERACTION_COVERAGE=${before.summary}->${after.summary}")}
 @Test fun dashboardExposesInteractionReleaseEvidence(){val rows=CurriculumProductionDashboard.rows();val interactive=rows.filter{it.interactiveAssetCount>0};assertEquals(4,interactive.size);assertTrue(interactive.all{it.guidedModeAvailable&&it.exploreModeAvailable&&it.challengeModeAvailable&&it.predictionAvailable&&it.accessibilityAvailable&&it.brokenControls==0&&it.brokenVisualLinks==0&&it.interactionReleaseReady})}
}
