package com.indianservers.aiexplorer

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.LearnerCurriculumProgress
import com.indianservers.aiexplorer.learningintelligence.engine.*
import com.indianservers.aiexplorer.learningintelligence.learner.LocalLearningIntelligenceService
import com.indianservers.aiexplorer.learningintelligence.migration.LearningProgressMigration
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.persistence.*
import com.indianservers.aiexplorer.learningintelligence.reference.LearningIntelligenceCatalog
import com.indianservers.aiexplorer.learningintelligence.testing.LearningIntelligenceValidator
import com.indianservers.aiexplorer.learningintelligence.validation.*
import org.junit.Assert.*
import org.junit.Test
import java.time.Instant

class LearningIntelligencePhase1Test {
 private val now=Instant.parse("2026-07-19T10:00:00Z");private val mastery=DeterministicMasteryEngine();private val validator=LocalAnswerValidationEngine()
 private fun state(id:String="math-linear-equations")=LearningIntelligenceCatalog.concepts.single{it.conceptId==id}.let{LearnerConceptState(it.conceptId,setOf(it.curriculumNodeId),it.subject)}
 private fun policy(id:String="math-linear-equations")=LearningIntelligenceCatalog.policies.getValue(id)

 @Test fun pageCompletionDoesNotCreateMastery(){val s=mastery.process(state(),LearnerEvent.LessonCompleted("math-linear-equations",now),policy());assertEquals(ConceptMasteryState.INTRODUCED,s.masteryState);assertTrue(s.masteryEvidence.isEmpty())}
 @Test fun independentDelayedRetrievalCanCreateMastery(){val p=MasteryPolicy("x",setOf(MasteryEvidenceType.CONCEPT_QUESTION),2,1,.7,.4,false);var s=LearnerConceptState("x",setOf("node"),SchoolSubject.MATHEMATICS,rollingAccuracy=.9);repeat(2){i->s=s.copy(masteryEvidence=s.masteryEvidence+MasteryEvidence("e$i","x",MasteryEvidenceType.CONCEPT_QUESTION,1.0,1.0,0.0,null,now.plusSeconds(i.toLong()),null))};s=s.copy(masteryEvidence=s.masteryEvidence+MasteryEvidence("r","x",MasteryEvidenceType.DELAYED_RETRIEVAL,1.0,1.0,0.0,null,now.plusSeconds(10),null));assertEquals(ConceptMasteryState.MASTERED,mastery.derive(s,p))}
 @Test fun fullSolutionHintReducesEvidenceIndependence(){val event=LearnerEvent.PracticeAnswered("math-linear-equations","q",ValidationResult(true,1.0,null,null,"ok"),1000,EvidenceIndependence.FULL_SOLUTION,LearnerConfidence.VERY_SURE,now);val s=mastery.process(state(),event,policy());assertEquals(0.0,s.masteryEvidence.single().effectiveScore,0.0);assertNotEquals(ConceptMasteryState.MASTERED,s.masteryState)}
 @Test fun confidentWrongAnswerRaisesReviewPriority(){val review=DeterministicSpacedReviewEngine().schedule(state().copy(retentionState=RetentionState(intervalDays=8)),now,false,true,true);assertEquals(ReviewUrgency.URGENT_REPAIR,review.urgency);assertEquals(now.plusSeconds(86400),review.scheduledAt)}
 @Test fun oneWrongAnswerDoesNotConfirmMisconception(){val d=LearningIntelligenceCatalog.misconceptions.first();val e=MisconceptionEvidence(d.id,d.conceptId,"q",1.0,LearnerConfidence.UNSURE,now);assertEquals(MisconceptionConfidence.POSSIBLE,DeterministicMisconceptionEngine().assess(d,listOf(e)).confidence)}
 @Test fun repeatedPatternCanConfirmMisconception(){val d=LearningIntelligenceCatalog.misconceptions.first();val ev=(0..1).map{MisconceptionEvidence(d.id,d.conceptId,"q$it",1.0,LearnerConfidence.VERY_SURE,now.plusSeconds(it.toLong()))};assertEquals(MisconceptionConfidence.CONFIRMED,DeterministicMisconceptionEngine().assess(d,ev).confidence)}
 @Test fun missingPrerequisiteIsRecommendedBeforeAdvancedConcept(){val index=KnowledgeGraphIndex(LearningIntelligenceCatalog.graph);val states=LearningIntelligenceCatalog.concepts.associate{it.conceptId to state(it.conceptId)};val r=DeterministicNextLessonEngine().recommend(states,index,LearningIntelligenceCatalog.activities,10,emptyList(),now)!!;assertEquals(RecommendationReason.MISSING_PREREQUISITE,r.reason);assertTrue(r.explanation.contains("mandatory prerequisite"))}
 @Test fun diagnosticResultIsExplainable(){val engine=DeterministicDiagnosticEngine();val qs=LearningIntelligenceCatalog.diagnosticQuestions.filter{it.subject==SchoolSubject.PHYSICS};val responses=qs.take(3).mapIndexed{i,q->DiagnosticResponse(q.id,if(i==2)1 else 0,i!=2,LearnerConfidence.VERY_SURE,1000,now.plusSeconds(i.toLong()))};val session=DiagnosticSession("d",SchoolSubject.PHYSICS,SchoolClassLevel.CLASS_9,now,responses);val result=engine.result(session,qs,DeterministicConfidenceCalibrationEngine().calibrate(responses.map{ConfidenceObservation(it.questionId,it.confidence!!,it.correct,it.occurredAt)})){id->KnowledgeGraphIndex(LearningIntelligenceCatalog.graph).mandatoryPrerequisites(id)};assertTrue(result.evidenceSummary.all{it.isNotBlank()});assertTrue(result.evidenceSummary.last().contains("recommendation"))}
 @Test fun reviewIntervalExpandsAfterSuccessfulRetrieval(){val r=DeterministicSpacedReviewEngine().schedule(state().copy(retentionState=RetentionState(intervalDays=4)),now,true,true,false);assertEquals(now.plusSeconds(8*86400),r.scheduledAt);assertTrue(r.reason.contains("expanded"))}
 @Test fun failedReviewShortensInterval(){val r=DeterministicSpacedReviewEngine().schedule(state().copy(retentionState=RetentionState(intervalDays=8)),now,false,true,false);assertEquals(now.plusSeconds(4*86400),r.scheduledAt);assertTrue(r.reason.contains("shortened"))}
 @Test fun equivalentFractionIsAccepted(){assertTrue(validator.validate(ValidationRequest.Fraction(1,2,"3/6")).valid)}
 @Test fun algebraicEquivalentExpressionIsAccepted(){assertTrue(validator.validate(ValidationRequest.Algebraic("2*x+2","2*(x+1)")).valid)}
 @Test fun physicsAnswerWithoutRequiredUnitIsIncomplete(){val r=validator.validate(ValidationRequest.Physics(10.0,"10","m/s",null));assertFalse(r.valid);assertEquals(LearnerErrorType.UNIT_MISSING,r.errorType)}
 @Test fun balancedChemicalEquationPreservesAtoms(){assertTrue(validator.validate(ValidationRequest.ChemicalEquation(mapOf("H" to 4,"O" to 2),mapOf("H" to 4,"O" to 2))).valid);assertEquals(LearnerErrorType.ATOM_CONSERVATION,validator.validate(ValidationRequest.ChemicalEquation(mapOf("H" to 2),mapOf("H" to 4))).errorType)}
 @Test fun geneticsProbabilityValidationAcceptsEquivalentRatio(){assertTrue(validator.validate(ValidationRequest.GeneticsRatio(listOf(3,1),"6:2")).valid)}
 @Test fun previousProgressSurvivesDatabaseMigration(){val old=LearnerCurriculumProgress(setOf("legacy-linear"),mapOf("legacy-linear" to "note"),setOf("legacy-linear"),mapOf("q" to 2));val c=LearningIntelligenceCatalog.concepts.single{it.conceptId=="math-linear-equations"};val migrated=LearningProgressMigration.migrate(old,mapOf("legacy-linear" to c.conceptId),mapOf(c.conceptId to c.subject),mapOf(c.conceptId to setOf(c.curriculumNodeId)));assertEquals(ConceptMasteryState.INTRODUCED,migrated.getValue(c.conceptId).masteryState);assertTrue(migrated.getValue(c.conceptId).masteryEvidence.isEmpty())}
 @Test fun versionedSnapshotMigrationPreservesRecords(){val old=LocalLearningSnapshot(1,listOf(PersistenceRecord("concept-state","x",mapOf("exposure" to "2"))));val migrated=LearningPersistenceMigration.migrate(old);assertEquals(2,migrated.schemaVersion);assertEquals("2",migrated.records.single().fields["exposure"])}
 @Test fun allReferencePathsAreValid(){assertEquals(22,LearningIntelligenceCatalog.concepts.size);assertEquals(6,LearningIntelligenceCatalog.concepts.count{it.subject==SchoolSubject.MATHEMATICS});assertEquals(6,LearningIntelligenceCatalog.concepts.count{it.subject==SchoolSubject.CHEMISTRY});assertEquals(5,LearningIntelligenceCatalog.concepts.count{it.subject==SchoolSubject.PHYSICS});assertEquals(5,LearningIntelligenceCatalog.concepts.count{it.subject==SchoolSubject.BIOLOGY});assertTrue(LearningIntelligenceValidator.validate().errors.joinToString(),LearningIntelligenceValidator.validate().valid)}
 @Test fun everyReferencePathHasFullLocalIntelligence(){LearningIntelligenceCatalog.concepts.forEach{c->assertTrue(c.diagnosticQuestions.isNotEmpty());assertTrue(c.misconceptions.isNotEmpty());assertEquals(HintLevel.entries.toSet(),c.hints.map{it.level}.toSet());assertEquals(FadeStage.entries,c.workedExample.supportedFadeStages);assertTrue(c.policy.minimumIndependentEvidence>1)}}
 @Test fun localEnginesRemainFast(){val start=System.nanoTime();repeat(10_000){mastery.derive(state().copy(rollingAccuracy=.8),policy())};val ms=(System.nanoTime()-start)/1_000_000;println("LEARNING_INTELLIGENCE_10000_DERIVATIONS_MS=$ms");assertTrue(ms<1500)}
}
