package com.indianservers.aiexplorer.gamifymaths

import androidx.compose.ui.graphics.Color

internal val expandedMathsGameIds = listOf(
    "number-bonds",
    "times-table",
    "decimal-harbor",
    "math-market",
    "integer-expedition",
    "ratio-rangers",
    "percent-studio",
    "data-story",
    "function-machine",
    "geometry-proof",
    "calculus-climber",
    "matrix-mission",
    "number-theory",
    "combinatorics",
    "optimization-arena",
)

internal fun expandedMathsGames(): List<MathsGame> = listOf(
    MathsGame(
        id = "number-bonds",
        title = "Number Bond Garden",
        currentTopic = "Flexible Addition",
        icon = "10",
        accent = Color(0xFF65E6A7),
        subtopics = listOf("Number bonds", "Doubles", "Missing addends", "Compensation", "Mental strategies"),
        mechanic = "Grow each number flower by connecting values that complete the target.",
        difficulty = GameDifficulty.Beginner,
        missions = listOf(
            GameMission("Make ten", "Which number completes 6 + ? = 10?", listOf("2", "3", "4", "5"), "4", "Six and four are number partners because they combine to make exactly ten."),
            GameMission("Double bloom", "What is double 7?", listOf("12", "13", "14", "16"), "14", "Doubling means adding the same amount twice, so 7 + 7 equals 14."),
            GameMission("Near double", "Use a near double to solve 8 + 9.", listOf("15", "16", "17", "18"), "17", "Double 8 is 16, and the extra one in 9 increases the total to 17."),
            GameMission("Missing petal", "Complete 23 + ? = 40.", listOf("7", "13", "17", "63"), "17", "Count from 23 to 40 or subtract 23 from 40; both strategies give 17."),
            GameMission("Compensation path", "Choose an equivalent calculation for 38 + 27.", listOf("40 + 25", "40 + 27", "38 + 30", "35 + 27"), "40 + 25", "Moving two from 27 to 38 keeps the total unchanged and creates the friendly number 40."),
        ),
    ),
    MathsGame(
        id = "times-table",
        title = "Times Table Galaxy",
        currentTopic = "Multiplication Patterns",
        icon = "x",
        accent = Color(0xFF5CC8FF),
        subtopics = listOf("Arrays", "Times tables", "Missing factors", "Distributive law", "Square numbers"),
        mechanic = "Power planets by building arrays and discovering multiplication shortcuts.",
        difficulty = GameDifficulty.Beginner,
        missions = listOf(
            GameMission("Array launch", "Six rows of seven stars contain how many stars?", listOf("36", "40", "42", "48"), "42", "An array with six rows of seven has 6 x 7 elements, which equals 42."),
            GameMission("Ninth orbit", "Calculate 8 x 9.", listOf("63", "70", "72", "81"), "72", "Eight groups of nine total 72; it is also eight less than 8 x 10."),
            GameMission("Missing thruster", "Complete ? x 6 = 54.", listOf("7", "8", "9", "10"), "9", "Use the inverse operation: 54 divided by 6 equals 9, so the factor is 9."),
            GameMission("Split strategy", "Use 7 x 13 = 7 x 10 + 7 x 3. What is the result?", listOf("70", "84", "91", "101"), "91", "The distributive law gives 70 + 21, so the complete product is 91."),
            GameMission("Square satellite", "Which value is 12 squared?", listOf("24", "124", "144", "164"), "144", "Twelve squared means twelve multiplied by itself, and 12 x 12 equals 144."),
        ),
    ),
    MathsGame(
        id = "decimal-harbor",
        title = "Decimal Harbor",
        currentTopic = "Place Value Navigation",
        icon = "0.1",
        accent = Color(0xFF57DFC8),
        subtopics = listOf("Place value", "Comparing decimals", "Decimal operations", "Powers of ten", "Estimation"),
        mechanic = "Dock decimal ships in order and align place-value columns to unload cargo.",
        difficulty = GameDifficulty.Beginner,
        missions = listOf(
            GameMission("Place-value dock", "What value does the 5 represent in 4.507?", listOf("5", "0.5", "0.05", "0.005"), "0.5", "The 5 is immediately after the decimal point, so it represents five tenths or 0.5."),
            GameMission("Harbor order", "Which is the greatest decimal?", listOf("0.56", "0.506", "0.65", "0.605"), "0.65", "Compare tenths first: six tenths is greater than five tenths, then 0.65 exceeds 0.605."),
            GameMission("Cargo total", "Calculate 3.75 + 1.6.", listOf("4.35", "5.15", "5.35", "19.75"), "5.35", "Align decimal points: 3.75 + 1.60 gives a total of 5.35."),
            GameMission("Tiny product", "Calculate 0.4 x 0.3.", listOf("0.012", "0.12", "1.2", "12"), "0.12", "Four tenths times three tenths makes twelve hundredths, which is 0.12."),
            GameMission("Channel division", "Calculate 3.6 divided by 0.6.", listOf("0.6", "3", "6", "60"), "6", "Scale both numbers by ten: 36 divided by 6 equals 6, preserving the quotient."),
        ),
    ),
    MathsGame(
        id = "math-market",
        title = "Math Market",
        currentTopic = "Money Decisions",
        icon = "$",
        accent = Color(0xFFFFC857),
        subtopics = listOf("Money", "Change", "Unit prices", "Budgets", "Best buys"),
        mechanic = "Shop to a budget, calculate change, and compare deals before checkout.",
        difficulty = GameDifficulty.Beginner,
        missions = listOf(
            GameMission("Exact change", "An item costs $6.75. What change comes from $10?", listOf("$2.25", "$3.15", "$3.25", "$4.25"), "$3.25", "Subtract the cost from the payment: 10.00 - 6.75 leaves $3.25."),
            GameMission("Basket total", "Three notebooks cost $2.40 each. What is the total?", listOf("$5.20", "$6.20", "$7.20", "$8.40"), "$7.20", "Three equal prices give 3 x $2.40, so the basket total is $7.20."),
            GameMission("Unit-price scan", "Four drinks cost $6. What is the price per drink?", listOf("$1.00", "$1.25", "$1.50", "$2.00"), "$1.50", "Divide the total cost equally among four drinks: $6 divided by 4 is $1.50."),
            GameMission("Budget builder", "You have $25 and spend $8.50 and $6.25. How much remains?", listOf("$9.25", "$10.25", "$10.75", "$11.25"), "$10.25", "The spending totals $14.75, and $25.00 - $14.75 leaves $10.25."),
            GameMission("Best-buy badge", "Which is cheaper per pen?", listOf("3 for $6", "5 for $9", "4 for $8", "2 for $5"), "5 for $9", "The unit prices are $2.00, $1.80, $2.00 and $2.50, making five for $9 the best buy."),
        ),
    ),
    MathsGame(
        id = "integer-expedition",
        title = "Integer Expedition",
        currentTopic = "Below Zero",
        icon = "-5",
        accent = Color(0xFF75A7FF),
        subtopics = listOf("Negative numbers", "Number lines", "Integer operations", "Absolute value", "Order of operations"),
        mechanic = "Move an expedition marker across hot and cold regions of the number line.",
        difficulty = GameDifficulty.Intermediate,
        missions = listOf(
            GameMission("Temperature rise", "The temperature is -5 C and rises 8 C. What is it now?", listOf("-13 C", "-3 C", "3 C", "13 C"), "3 C", "Starting at -5 and moving eight steps right on the number line lands at 3."),
            GameMission("Cave descent", "Calculate -4 - 7.", listOf("-11", "-3", "3", "11"), "-11", "Subtracting seven moves seven places left from -4, so the result is -11."),
            GameMission("Sign shield", "Calculate (-6) x (-5).", listOf("-30", "-11", "11", "30"), "30", "The product of two negative numbers is positive, and 6 x 5 equals 30."),
            GameMission("Distance from zero", "What is the absolute value of -17?", listOf("-17", "0", "7", "17"), "17", "Absolute value measures distance from zero, so the distance of -17 is 17 units."),
            GameMission("Operation ridge", "Calculate 6 - 3 x 4.", listOf("-6", "12", "18", "24"), "-6", "Multiplication comes first: 3 x 4 is 12, then 6 - 12 equals -6."),
        ),
    ),
    MathsGame(
        id = "ratio-rangers",
        title = "Ratio Rangers",
        currentTopic = "Scale & Share",
        icon = "3:2",
        accent = Color(0xFFFF8D70),
        subtopics = listOf("Simplifying ratios", "Scaling", "Unit rates", "Sharing", "Recipes"),
        mechanic = "Restore maps by scaling supplies and sharing resources in exact ratios.",
        difficulty = GameDifficulty.Intermediate,
        missions = listOf(
            GameMission("Simplify supplies", "Simplify the ratio 18:24.", listOf("2:3", "3:4", "6:8", "9:12"), "3:4", "Divide both parts by their greatest common factor, 6, to obtain the simplest ratio 3:4."),
            GameMission("Scale the map", "A map scale is 1:50,000. What does 2 cm represent?", listOf("100 m", "500 m", "1 km", "10 km"), "1 km", "Two centimetres represent 100,000 centimetres, which converts to exactly one kilometre."),
            GameMission("Share the crystals", "Share 40 in the ratio 3:2. What is the larger share?", listOf("16", "20", "24", "30"), "24", "There are five equal ratio parts; each is 8, so three parts make the larger share of 24."),
            GameMission("Recipe rescue", "Flour:sugar is 5:2. If flour is 300 g, how much sugar is needed?", listOf("60 g", "100 g", "120 g", "150 g"), "120 g", "The scale factor from 5 to 300 is 60, so sugar is 2 x 60 = 120 grams."),
            GameMission("Unit-rate trail", "A cyclist covers 54 km in 3 hours. What is the unit rate?", listOf("16 km/h", "18 km/h", "27 km/h", "57 km/h"), "18 km/h", "Divide total distance by total time: 54 divided by 3 gives 18 kilometres per hour."),
        ),
    ),
    MathsGame(
        id = "percent-studio",
        title = "Percent Studio",
        currentTopic = "Change & Comparison",
        icon = "%",
        accent = Color(0xFFFF6FAE),
        subtopics = listOf("Percent of a quantity", "Discounts", "Percentage change", "Reverse percentages", "Simple interest"),
        mechanic = "Mix percentage layers to price products and explain changes accurately.",
        difficulty = GameDifficulty.Intermediate,
        missions = listOf(
            GameMission("Paint a percent", "Find 15% of 80.", listOf("8", "12", "15", "20"), "12", "Ten percent is 8 and five percent is 4; combining them gives 12."),
            GameMission("Discount design", "A $60 item has a 25% discount. What is the sale price?", listOf("$15", "$35", "$45", "$75"), "$45", "A quarter of $60 is $15, so subtracting the discount leaves a sale price of $45."),
            GameMission("Growth layer", "Increase 120 by 10%.", listOf("122", "130", "132", "140"), "132", "Ten percent of 120 is 12, and adding that increase gives the new value 132."),
            GameMission("Reverse canvas", "After a 20% discount, a game costs $40. What was the original price?", listOf("$48", "$50", "$60", "$80"), "$50", "The sale price is 80% of the original; dividing 40 by 0.8 gives $50."),
            GameMission("Interest mural", "Find one year of 5% simple interest on $400.", listOf("$5", "$20", "$40", "$420"), "$20", "Simple interest for one year is principal times rate: $400 x 0.05 equals $20."),
        ),
    ),
    MathsGame(
        id = "data-story",
        title = "Data Story Lab",
        currentTopic = "Evidence & Claims",
        icon = "AVG",
        accent = Color(0xFF67D4FF),
        subtopics = listOf("Mean", "Median", "Outliers", "Weighted averages", "Interpreting charts"),
        mechanic = "Investigate datasets, choose a fair summary, and expose misleading claims.",
        difficulty = GameDifficulty.Intermediate,
        missions = listOf(
            GameMission("Mean machine", "Find the mean of 6, 8, 9 and 13.", listOf("8", "9", "10", "12"), "9", "The values total 36, and dividing by the four observations gives a mean of 9."),
            GameMission("Median message", "Find the median of 2, 4, 7, 9 and 20.", listOf("4", "7", "8.4", "9"), "7", "The values are already ordered, and the central third value is 7."),
            GameMission("Outlier alert", "Which value is an outlier in 12, 13, 13, 14, 48?", listOf("12", "13", "14", "48"), "48", "The value 48 lies far away from the cluster between 12 and 14, so it is the clear outlier."),
            GameMission("Fair summary", "For incomes 20, 22, 24, 25 and 200, which center is more representative?", listOf("Mean", "Median", "Range", "Maximum"), "Median", "The extreme income pulls the mean upward, while the median remains representative of the typical values."),
            GameMission("Weighted score", "A test worth 60% scores 80; a project worth 40% scores 90. Find the final score.", listOf("82", "84", "85", "86"), "84", "Compute 0.6 x 80 + 0.4 x 90 = 48 + 36, giving a weighted score of 84."),
        ),
    ),
    MathsGame(
        id = "function-machine",
        title = "Function Machine",
        currentTopic = "Inputs & Outputs",
        icon = "f(x)",
        accent = Color(0xFF9B7BFF),
        subtopics = listOf("Evaluation", "Composition", "Inverse functions", "Domain", "Transformations"),
        mechanic = "Route inputs through connected machines and predict every output.",
        difficulty = GameDifficulty.Advanced,
        missions = listOf(
            GameMission("Input scan", "If f(x) = 3x - 2, find f(5).", listOf("10", "13", "15", "17"), "13", "Substitute 5 for x: 3 x 5 - 2 equals 15 - 2, which is 13."),
            GameMission("Machine chain", "Let f(x)=x+1 and g(x)=2x. Find g(f(3)).", listOf("6", "7", "8", "9"), "8", "The inner machine gives f(3)=4, then the outer machine gives g(4)=8."),
            GameMission("Reverse gear", "If f(x)=2x+6, which formula is its inverse?", listOf("(x-6)/2", "(x+6)/2", "2x-6", "6-2x"), "(x-6)/2", "Undo addition by subtracting six, then undo multiplication by dividing the result by two."),
            GameMission("Domain gate", "What is the domain restriction for f(x)=1/(x-4)?", listOf("x > 4", "x < 4", "x != 4", "x != 0"), "x != 4", "The denominator cannot be zero, so x - 4 cannot equal zero and x cannot be 4."),
            GameMission("Transformation code", "How does y=(x-3)^2 move the graph of y=x^2?", listOf("Left 3", "Right 3", "Up 3", "Down 3"), "Right 3", "Replacing x by x - 3 shifts every point of the base parabola three units to the right."),
        ),
    ),
    MathsGame(
        id = "geometry-proof",
        title = "Geometry Proof Lab",
        currentTopic = "Reasoned Geometry",
        icon = "QED",
        accent = Color(0xFF45D6B5),
        subtopics = listOf("Congruence", "Similarity", "Circle theorems", "Proof", "Coordinate geometry"),
        mechanic = "Assemble statements and reasons to complete geometric proof circuits.",
        difficulty = GameDifficulty.Advanced,
        missions = listOf(
            GameMission("Congruence circuit", "Two triangles have three matching side lengths. Which test proves congruence?", listOf("AAA", "SAS", "SSS", "RHS"), "SSS", "Three corresponding equal sides satisfy the side-side-side condition, proving the triangles congruent."),
            GameMission("Similarity beam", "Corresponding sides are 3 and 6. What is the scale factor from the first shape to the second?", listOf("1/2", "2", "3", "9"), "2", "Divide a second-shape side by its corresponding first-shape side: 6 divided by 3 equals 2."),
            GameMission("Cyclic signal", "Opposite angles of a cyclic quadrilateral sum to what?", listOf("90 degrees", "180 degrees", "270 degrees", "360 degrees"), "180 degrees", "A standard circle theorem states that opposite angles in any cyclic quadrilateral are supplementary."),
            GameMission("Tangent lock", "What angle does a radius make with a tangent at the point of contact?", listOf("30 degrees", "45 degrees", "90 degrees", "180 degrees"), "90 degrees", "A radius drawn to the point of tangency is perpendicular to the tangent, forming a right angle."),
            GameMission("Converse test", "Sides 5, 12 and 13 form what type of triangle?", listOf("Acute", "Right", "Obtuse", "Equilateral"), "Right", "Because 5 squared plus 12 squared equals 13 squared, the converse of Pythagoras proves a right triangle."),
        ),
    ),
    MathsGame(
        id = "calculus-climber",
        title = "Calculus Climber",
        currentTopic = "Rates & Accumulation",
        icon = "dx",
        accent = Color(0xFFFF7A75),
        subtopics = listOf("Limits", "Derivatives", "Stationary points", "Integrals", "Fundamental theorem"),
        mechanic = "Climb a changing curve by matching slopes, limits, and accumulated areas.",
        difficulty = GameDifficulty.Advanced,
        missions = listOf(
            GameMission("Limit ledge", "Find lim x->2 of (x^2 + 1).", listOf("3", "4", "5", "Undefined"), "5", "Polynomials are continuous, so direct substitution gives 2 squared plus 1, which equals 5."),
            GameMission("Slope rope", "Differentiate f(x)=3x^2+4x.", listOf("3x+4", "6x+4", "6x", "6x^2+4"), "6x+4", "Apply the power rule term by term: the derivative of 3x squared is 6x and of 4x is 4."),
            GameMission("Summit point", "For f(x)=x^2-6x, at which x is the stationary point?", listOf("-3", "0", "3", "6"), "3", "Set the derivative 2x - 6 equal to zero; solving gives the stationary x-coordinate 3."),
            GameMission("Area ascent", "Evaluate the integral of 2x from 0 to 3.", listOf("3", "6", "9", "18"), "9", "An antiderivative is x squared; evaluating from zero to three gives 9 - 0 = 9."),
            GameMission("Motion bridge", "If position is s(t)=t^3, what is velocity at t=2?", listOf("4", "6", "8", "12"), "12", "Velocity is the derivative 3t squared; substituting t=2 gives 3 x 4 = 12."),
        ),
    ),
    MathsGame(
        id = "matrix-mission",
        title = "Matrix Mission",
        currentTopic = "Linear Transformations",
        icon = "[ ]",
        accent = Color(0xFF6D9CFF),
        subtopics = listOf("Matrix operations", "Determinants", "Inverses", "Transformations", "Systems"),
        mechanic = "Configure matrix panels to transform coordinates and unlock linear systems.",
        difficulty = GameDifficulty.Advanced,
        missions = listOf(
            GameMission("Panel addition", "Add [1,2] and [3,4] as row matrices.", listOf("[2,6]", "[3,8]", "[4,6]", "[4,8]"), "[4,6]", "Matrix addition combines corresponding entries, giving 1+3=4 and 2+4=6."),
            GameMission("Determinant door", "Find det [[2,1],[3,4]].", listOf("2", "5", "8", "11"), "5", "For a two by two matrix, ad-bc gives 2 x 4 - 1 x 3 = 5."),
            GameMission("Identity key", "Which matrix is the 2x2 identity?", listOf("[[0,1],[1,0]]", "[[1,0],[0,1]]", "[[1,1],[1,1]]", "[[2,0],[0,2]]"), "[[1,0],[0,1]]", "The identity has ones on the main diagonal and zeros elsewhere, leaving vectors unchanged."),
            GameMission("Vector transform", "Apply [[2,0],[0,3]] to vector (1,2).", listOf("(2,3)", "(2,6)", "(3,4)", "(3,6)"), "(2,6)", "Matrix-vector multiplication scales the x-coordinate by 2 and the y-coordinate by 3."),
            GameMission("Singular scan", "A 2x2 matrix is non-invertible when its determinant is what?", listOf("-1", "0", "1", "2"), "0", "A zero determinant collapses area and prevents a unique inverse transformation from existing."),
        ),
    ),
    MathsGame(
        id = "number-theory",
        title = "Number Theory Crypt",
        currentTopic = "Prime Structures",
        icon = "mod",
        accent = Color(0xFFC27BFF),
        subtopics = listOf("GCD", "Congruences", "Prime theorems", "Euler phi", "Diophantine equations"),
        mechanic = "Crack modular codes by combining divisibility facts and prime structures.",
        difficulty = GameDifficulty.Expert,
        missions = listOf(
            GameMission("GCD cipher", "Find gcd(84, 126).", listOf("14", "21", "42", "63"), "42", "The Euclidean algorithm gives 126-84=42 and 84 is divisible by 42, so the greatest common divisor is 42."),
            GameMission("Remainder rune", "What is 47 mod 6?", listOf("1", "3", "5", "7"), "5", "Six fits into 47 seven times with 5 remaining, so the residue modulo 6 is 5."),
            GameMission("Fermat key", "For prime p=5 and a not divisible by 5, a^4 is congruent to what mod 5?", listOf("0", "1", "4", "5"), "1", "Fermat's little theorem gives a^(p-1) congruent to 1 modulo p under the stated condition."),
            GameMission("Totient vault", "How many positive integers at most 9 are coprime to 9?", listOf("3", "5", "6", "8"), "6", "The coprime values are 1, 2, 4, 5, 7 and 8, so Euler's totient phi(9) equals 6."),
            GameMission("Integer solution", "Which pair solves 3x + 5y = 1?", listOf("(2,-1)", "(-2,1)", "(1,1)", "(5,-3)"), "(2,-1)", "Substitution verifies 3 x 2 + 5 x (-1) = 6 - 5 = 1 exactly."),
        ),
    ),
    MathsGame(
        id = "combinatorics",
        title = "Combinatorics Command",
        currentTopic = "Counting Without Listing",
        icon = "nCr",
        accent = Color(0xFFFF6FCF),
        subtopics = listOf("Permutations", "Combinations", "Pigeonhole principle", "Inclusion-exclusion", "Lattice paths"),
        mechanic = "Command a fleet by counting configurations efficiently instead of listing them.",
        difficulty = GameDifficulty.Expert,
        missions = listOf(
            GameMission("Order the fleet", "How many orders are possible for 5 distinct ships?", listOf("25", "60", "120", "625"), "120", "Five distinct objects can be arranged in 5 factorial ways, and 5 x 4 x 3 x 2 x 1 = 120."),
            GameMission("Choose a crew", "How many groups of 3 can be chosen from 7 people?", listOf("21", "35", "42", "210"), "35", "Use combinations because order does not matter: 7 choose 3 equals 35."),
            GameMission("Pigeonhole alarm", "With 13 people, at least two must share which feature?", listOf("Birth month", "Birth day", "Exact age", "First name"), "Birth month", "There are only 12 months, so placing 13 people among them forces one month to contain at least two."),
            GameMission("Union scanner", "If |A|=20, |B|=15 and |A intersect B|=5, find |A union B|.", listOf("25", "30", "35", "40"), "30", "Inclusion-exclusion adds both sets and subtracts the five elements counted twice: 20+15-5=30."),
            GameMission("Grid routes", "How many shortest paths use 3 right moves and 2 up moves?", listOf("5", "8", "10", "12"), "10", "Choose the two positions for up moves among five total moves, giving 5 choose 2 = 10."),
        ),
    ),
    MathsGame(
        id = "optimization-arena",
        title = "Optimization Arena",
        currentTopic = "Best Possible Choice",
        icon = "MAX",
        accent = Color(0xFFFF9A52),
        subtopics = listOf("Quadratic extrema", "Linear programming", "Calculus optimization", "AM-GM", "Decision models"),
        mechanic = "Tune constraints and objective functions to discover and justify the best solution.",
        difficulty = GameDifficulty.Expert,
        missions = listOf(
            GameMission("Parabola minimum", "Find the minimum value of x^2 - 6x + 11.", listOf("1", "2", "3", "11"), "2", "Completing the square gives (x-3)^2 + 2, whose smallest possible value is 2."),
            GameMission("Vertex principle", "A linear objective over a bounded polygon reaches an optimum where?", listOf("At a vertex", "Only at the center", "Outside the region", "At every point"), "At a vertex", "In linear programming, an attainable optimum occurs at one or more vertices of the feasible region."),
            GameMission("Maximum product", "Two positive numbers sum to 20. What is their maximum product?", listOf("20", "50", "100", "200"), "100", "For a fixed sum, equal positive parts maximize the product, so 10 x 10 gives 100."),
            GameMission("Open-top box", "For volume V(x)=x(12-2x)^2, what equation identifies interior extrema?", listOf("V(x)=0", "V'(x)=0", "V''(x)=0 only", "x=0 only"), "V'(x)=0", "Differentiable interior maxima and minima must occur at critical points where the first derivative is zero."),
            GameMission("Expected payoff", "A choice wins $30 with probability 0.4 and loses $10 otherwise. What is its expected value?", listOf("-$2", "$0", "$6", "$12"), "$6", "The weighted payoff is 0.4 x 30 + 0.6 x (-10) = 12 - 6 = $6."),
        ),
    ),
)
