package com.indianservers.aiexplorer.gamifymaths

import androidx.compose.ui.graphics.Color

internal val expandedMathsGameIds = listOf(
    "number-bonds",
    "times-table",
    "decimal-harbor",
    "math-market",
    "integer-expedition",
    "ratio-rangers",
    "percent-studio",
    "data-story",
    "function-machine",
    "geometry-proof",
    "calculus-climber",
    "matrix-mission",
    "number-theory",
    "combinatorics",
    "optimization-arena",
)

internal fun expandedMathsGames(): List<MathsGame> = listOf(
    MathsGame(
        id = "number-bonds",
        title = "Number Bond Garden",
        currentTopic = "Flexible Addition",
        icon = "10",
        accent = Color(0xFF65E6A7),
        subtopics = listOf("Number bonds", "Doubles", "Missing addends", "Compensation", "Mental strategies"),
        mechanic = "Grow each number flower by connecting values that complete the target.",
        difficulty = GameDifficulty.Beginner,
    ),
    MathsGame(
        id = "times-table",
        title = "Times Table Galaxy",
        currentTopic = "Multiplication Patterns",
        icon = "x",
        accent = Color(0xFF5CC8FF),
        subtopics = listOf("Arrays", "Times tables", "Missing factors", "Distributive law", "Square numbers"),
        mechanic = "Power planets by building arrays and discovering multiplication shortcuts.",
        difficulty = GameDifficulty.Beginner,
    ),
    MathsGame(
        id = "decimal-harbor",
        title = "Decimal Harbor",
        currentTopic = "Place Value Navigation",
        icon = "0.1",
        accent = Color(0xFF57DFC8),
        subtopics = listOf("Place value", "Comparing decimals", "Decimal operations", "Powers of ten", "Estimation"),
        mechanic = "Dock decimal ships in order and align place-value columns to unload cargo.",
        difficulty = GameDifficulty.Beginner,
    ),
    MathsGame(
        id = "math-market",
        title = "Math Market",
        currentTopic = "Money Decisions",
        icon = "$",
        accent = Color(0xFFFFC857),
        subtopics = listOf("Money", "Change", "Unit prices", "Budgets", "Best buys"),
        mechanic = "Shop to a budget, calculate change, and compare deals before checkout.",
        difficulty = GameDifficulty.Beginner,
    ),
    MathsGame(
        id = "integer-expedition",
        title = "Integer Expedition",
        currentTopic = "Below Zero",
        icon = "-5",
        accent = Color(0xFF75A7FF),
        subtopics = listOf("Negative numbers", "Number lines", "Integer operations", "Absolute value", "Order of operations"),
        mechanic = "Move an expedition marker across hot and cold regions of the number line.",
        difficulty = GameDifficulty.Intermediate,
    ),
    MathsGame(
        id = "ratio-rangers",
        title = "Ratio Rangers",
        currentTopic = "Scale & Share",
        icon = "3:2",
        accent = Color(0xFFFF8D70),
        subtopics = listOf("Simplifying ratios", "Scaling", "Unit rates", "Sharing", "Recipes"),
        mechanic = "Restore maps by scaling supplies and sharing resources in exact ratios.",
        difficulty = GameDifficulty.Intermediate,
    ),
    MathsGame(
        id = "percent-studio",
        title = "Percent Studio",
        currentTopic = "Change & Comparison",
        icon = "%",
        accent = Color(0xFFFF6FAE),
        subtopics = listOf("Percent of a quantity", "Discounts", "Percentage change", "Reverse percentages", "Simple interest"),
        mechanic = "Mix percentage layers to price products and explain changes accurately.",
        difficulty = GameDifficulty.Intermediate,
    ),
    MathsGame(
        id = "data-story",
        title = "Data Story Lab",
        currentTopic = "Evidence & Claims",
        icon = "AVG",
        accent = Color(0xFF67D4FF),
        subtopics = listOf("Mean", "Median", "Outliers", "Weighted averages", "Interpreting charts"),
        mechanic = "Investigate datasets, choose a fair summary, and expose misleading claims.",
        difficulty = GameDifficulty.Intermediate,
    ),
    MathsGame(
        id = "function-machine",
        title = "Function Machine",
        currentTopic = "Inputs & Outputs",
        icon = "f(x)",
        accent = Color(0xFF9B7BFF),
        subtopics = listOf("Evaluation", "Composition", "Inverse functions", "Domain", "Transformations"),
        mechanic = "Route inputs through connected machines and predict every output.",
        difficulty = GameDifficulty.Advanced,
    ),
    MathsGame(
        id = "geometry-proof",
        title = "Geometry Proof Lab",
        currentTopic = "Reasoned Geometry",
        icon = "QED",
        accent = Color(0xFF45D6B5),
        subtopics = listOf("Congruence", "Similarity", "Circle theorems", "Proof", "Coordinate geometry"),
        mechanic = "Assemble statements and reasons to complete geometric proof circuits.",
        difficulty = GameDifficulty.Advanced,
    ),
    MathsGame(
        id = "calculus-climber",
        title = "Calculus Climber",
        currentTopic = "Rates & Accumulation",
        icon = "dx",
        accent = Color(0xFFFF7A75),
        subtopics = listOf("Limits", "Derivatives", "Stationary points", "Integrals", "Fundamental theorem"),
        mechanic = "Climb a changing curve by matching slopes, limits, and accumulated areas.",
        difficulty = GameDifficulty.Advanced,
    ),
    MathsGame(
        id = "matrix-mission",
        title = "Matrix Mission",
        currentTopic = "Linear Transformations",
        icon = "[ ]",
        accent = Color(0xFF6D9CFF),
        subtopics = listOf("Matrix operations", "Determinants", "Inverses", "Transformations", "Systems"),
        mechanic = "Configure matrix panels to transform coordinates and unlock linear systems.",
        difficulty = GameDifficulty.Advanced,
    ),
    MathsGame(
        id = "number-theory",
        title = "Number Theory Crypt",
        currentTopic = "Prime Structures",
        icon = "mod",
        accent = Color(0xFFC27BFF),
        subtopics = listOf("GCD", "Congruences", "Prime theorems", "Euler phi", "Diophantine equations"),
        mechanic = "Crack modular codes by combining divisibility facts and prime structures.",
        difficulty = GameDifficulty.Expert,
    ),
    MathsGame(
        id = "combinatorics",
        title = "Combinatorics Command",
        currentTopic = "Counting Without Listing",
        icon = "nCr",
        accent = Color(0xFFFF6FCF),
        subtopics = listOf("Permutations", "Combinations", "Pigeonhole principle", "Inclusion-exclusion", "Lattice paths"),
        mechanic = "Command a fleet by counting configurations efficiently instead of listing them.",
        difficulty = GameDifficulty.Expert,
    ),
    MathsGame(
        id = "optimization-arena",
        title = "Optimization Arena",
        currentTopic = "Best Possible Choice",
        icon = "MAX",
        accent = Color(0xFFFF9A52),
        subtopics = listOf("Quadratic extrema", "Linear programming", "Calculus optimization", "AM-GM", "Decision models"),
        mechanic = "Tune constraints and objective functions to discover and justify the best solution.",
        difficulty = GameDifficulty.Expert,
    ),
)
