import fs from "node:fs/promises";import path from "node:path";
const root="D:/Math Images",tmp="C:/Indian Servers/AIExplorer/.codex_tmp_lesson_audit";
const lessons=JSON.parse(await fs.readFile(path.join(tmp,"lessons_591_690.json"),"utf8")).slice(0,71);
const names=["generated_591_600_v2.json","generated_601_620_v2.json","generated_621_640_v2.json","generated_641_650_v2.json","generated_651_660_v2.json","generated_661_v2.json"];
let generated=[];for(const n of names)generated.push(...JSON.parse(await fs.readFile(path.join(tmp,n),"utf8")));
generated.sort((a,b)=>a.ordinal-b.ordinal);const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const src=s=>{const m=String(s).match(/exec-[0-9a-f-]+\.png/ig);return m?path.join("C:/Users/saisa/.codex/generated_images/01a0032b-d6bc-7f91-bb33-355182f94655",m.at(-1)):s};
for(let i=0;i<lessons.length;i++){const r=lessons[i],g=generated[i];if(!g||g.ordinal!==r.ordinal)throw new Error(`mapping ${r.ordinal}`);const source=src(g.source);await fs.access(source);const dir=path.join(root,r.className,r.chapter,r.topic);await fs.mkdir(dir,{recursive:true});const fileName=r.lessonId+"_"+slug(r.subtopic)+".png";await fs.copyFile(source,path.join(dir,fileName));const mp=path.join(dir,"metadata.json");let p={schemaVersion:"1.0",class:r.className,chapter:r.chapter,topic:r.topic,images:[]};try{p=JSON.parse((await fs.readFile(mp,"utf8")).replace(/^\uFEFF/,""))}catch{}p.images=(p.images||[]).filter(x=>x.lessonId!==r.lessonId);p.images.push({lessonId:r.lessonId,class:r.className,chapter:r.chapter,topic:r.topic,subtopic:r.subtopic,imageType:"inline concept visual",fileName,relativePath:path.relative(path.join(root,r.className),path.join(dir,fileName)).replaceAll("\\","/"),description:`A lesson-specific visual for ${r.subtopic}, using a mathematically checkable diagram or worked model.`,learningObjective:`Help learners understand ${r.subtopic} through a concrete-to-symbolic visual explanation.`,altText:`Educational illustration explaining ${r.subtopic}.`,promptType:"scientific-educational",qaStatus:"needs_review"});p.images.sort((a,b)=>a.lessonId.localeCompare(b.lessonId));p.imageCount=p.images.length;p.generatedAt=new Date().toISOString();await fs.writeFile(mp,JSON.stringify(p,null,2),"utf8")}
console.log(JSON.stringify({copied:lessons.length,first:lessons[0].lessonId,last:lessons.at(-1).lessonId},null,2));
