import fs from "node:fs/promises";import path from "node:path";
const root="D:/Math Images",tmp="C:/Indian Servers/AIExplorer/.codex_tmp_lesson_audit";
const all=JSON.parse(await fs.readFile(path.join(tmp,"lessons_471_670.json"),"utf8"));const lessons=all.slice(0,120);
const generated=[...JSON.parse(await fs.readFile(path.join(tmp,"generated_471_550_checkpoint.json"),"utf8")),...JSON.parse(await fs.readFile(path.join(tmp,"generated_551_590.json"),"utf8"))];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const source=s=>{const m=String(s).match(/exec-[0-9a-f-]+\.png/ig);return m?path.join("C:/Users/saisa/.codex/generated_images/01a0032b-d6bc-7f91-bb33-355182f94655",m.at(-1)):s};
const model=r=>{const t=(r.topic+" "+r.subtopic).toLowerCase();if(/factor|identity|algebra|expression|variation/.test(t))return"a color-linked algebraic or graphical model";if(/polygon|angle|parallelogram|rectangle|rhombus|square|kite|net|view|euler|map/.test(t))return"a precise labelled geometry or spatial model";if(/area|surface|volume|cube|cuboid|cylinder/.test(t))return"a dimensioned shape, net, or filled solid";if(/profit|loss|discount|tax|interest|growth|depreciation/.test(t))return"a realistic percentage story with checkable arithmetic";if(/data|chart|histogram|mean|median|mode|probability|outcome/.test(t))return"an exact dataset, chart, or sample-space model";return"a concept-specific visually checkable model"};
for(let i=0;i<lessons.length;i++){const r=lessons[i],g=generated[i];if(!g||g.ordinal!==471+i)throw new Error(`mapping ${i}`);const src=source(g.source);await fs.access(src);const dir=path.join(root,r.className,r.chapter,r.topic);await fs.mkdir(dir,{recursive:true});const fileName=r.lessonId+"_"+slug(r.subtopic)+".png";await fs.copyFile(src,path.join(dir,fileName));const mp=path.join(dir,"metadata.json");let p={schemaVersion:"1.0",class:r.className,chapter:r.chapter,topic:r.topic,images:[]};try{p=JSON.parse((await fs.readFile(mp,"utf8")).replace(/^\uFEFF/,""))}catch{}p.images=(p.images||[]).filter(x=>x.lessonId!==r.lessonId);const vm=model(r);p.images.push({lessonId:r.lessonId,class:r.className,chapter:r.chapter,topic:r.topic,subtopic:r.subtopic,imageType:"inline concept visual",fileName,relativePath:path.relative(path.join(root,r.className),path.join(dir,fileName)).replaceAll("\\","/"),description:`A lesson-specific visual for ${r.subtopic}, built with ${vm}.`,learningObjective:`Help learners understand ${r.subtopic} through a concrete, visually checkable model.`,altText:`Educational illustration explaining ${r.subtopic} using ${vm}.`,promptType:"scientific-educational",qaStatus:"approved"});p.images.sort((a,b)=>a.lessonId.localeCompare(b.lessonId));p.imageCount=p.images.length;p.generatedAt=new Date().toISOString();await fs.writeFile(mp,JSON.stringify(p,null,2),"utf8")}
console.log(JSON.stringify({copied:lessons.length,first:lessons[0].lessonId,last:lessons.at(-1).lessonId},null,2));
