package com.indianservers.aiexplorer.learning.ncert.experience

import com.indianservers.aiexplorer.curriculum.experience.*
import com.indianservers.aiexplorer.learning.ncert.interaction.MathematicsInteractiveReference

object MathematicsConceptExperiences {
 private fun v(s:String,m:String,u:String,t:String,r:String)=FormulaVariableLink(s,m,u,t,r)
 private fun build(id:String,copy:AuthoredExperienceCopy)=ConceptExperienceAuthoring.build(MathematicsInteractiveReference.definitions.single{it.activityId==id},copy)
 val linear=build("math-linear-equation-balance",AuthoredExperienceCopy("Algebra · Linear equations","An equation states that two expressions have equal value. The balance model makes legal transformations visible.",listOf("integer operations","meaning of a variable"),"To isolate x, perform the same operation on both sides. Subtracting b removes equal unit blocks from both pans; dividing into a equal groups preserves equality.","A term never changes side by magic: the apparent sign change abbreviates adding its opposite to both sides.","For 3x − 6 = 9, add 6 to both sides and divide both sides by 3, giving x = 5.","If b increases while a and c stay fixed, how will x change?","The computed solution and intersection move because x=(c−b)/a, while both pans remain equal at the solution.","A term can simply jump across the equals sign and change sign.","Increase b without changing c, then inspect the solution and the two balance stages.","The solution changes only because an equal subtraction is applied to both sides; no term physically jumps.","Solve 4x + 3 = 19.","x = 4","Subtract 3 from both sides to get 4x=16, then divide both sides by 4.","Equality is preserved only by applying an equivalent operation to both sides.","left-pan",listOf(v("a","coefficient of x","coefficient","a","inverse effect on x when the numerator is fixed"),v("b","left constant","units","b","subtracted from c"),v("c","right value","units","c","direct contribution to the numerator"),v("x","solution","units","left-pan","result"))))
 val triangles=build("math-triangle-lab",AuthoredExperienceCopy("Geometry · Triangles","A draggable Euclidean triangle links side lengths, altitude, area, and the invariant 180° angle sum.",listOf("angles","perpendicular height","area of a rectangle"),"The altitude is perpendicular distance from the apex to the base line. Sliding the apex parallel to the base changes side lengths and angles but preserves base, height, and therefore area.","Every non-degenerate Euclidean triangle has interior-angle sum 180°, regardless of its appearance.","A triangle with base 8 cm and height 6 cm has area 24 cm², wherever the apex lies along the parallel line.","What remains unchanged when only the apex offset changes?","Area and angle sum remain fixed; individual side lengths and angles usually change.","A wider-looking triangle must always have greater area.","Keep base and height fixed, slide the apex, and compare the live area.","The outline changes, but equal base and perpendicular height give equal area.","Construct a triangle of area 24 cm² and explain two possible base-height pairs.","For example, base 8 cm and height 6 cm.","One half of 8×6 is 24; many pairs with bh=48 work.","Shape can change while an invariant such as area or angle sum remains fixed.","c",listOf(v("b","base","cm","base","direct"),v("h","perpendicular height","cm","altitude","direct"),v("A","area","cm²","altitude","proportional to both base and height")),comparisonLabels="same base and height" to "different apex position"))
 val coordinate=build("math-coordinate-geometry",AuthoredExperienceCopy("Coordinate geometry · Distance, midpoint and slope","Two movable points create a slope triangle connecting coordinates to distance, midpoint, and gradient.",listOf("Cartesian coordinates","Pythagoras"),"Horizontal change is run Δx and vertical change is rise Δy. Their ratio gives slope when Δx is non-zero, while their right triangle gives distance by Pythagoras.","A vertical line has undefined slope because its run is zero; it does not have slope zero.","From (−2,1) to (4,5), rise=4 and run=6, so slope=2/3 and distance=√52.","If both points move upward by the same amount, which results change?","Slope and distance stay fixed; the midpoint y-coordinate moves upward.","A vertical line has slope zero.","Make x₁=x₂ and inspect the slope label, then make y₁=y₂ for comparison.","Zero run makes division undefined; zero rise gives slope zero.","Find a second point that is 10 units from (0,0).","For example (6,8).","√(6²+8²)=10.","Rise, run, midpoint, and distance are different views of the same pair of coordinates.","slope-triangle",listOf(v("Δx","run","coordinate units","slope-triangle","denominator of slope"),v("Δy","rise","coordinate units","slope-triangle","numerator of slope"),v("m","slope","unit per unit","slope-triangle","ratio"),v("d","distance","coordinate units","p1","Pythagorean combination"))))
 val trig=build("math-right-triangle-trig",AuthoredExperienceCopy("Trigonometry · Right-triangle ratios","A scalable right triangle shows that sine, cosine, and tangent depend on angle rather than overall size.",listOf("right triangles","ratio","degrees"),"For a chosen acute angle θ, name the sides relative to θ. Scaling the hypotenuse scales both legs by the same factor, so each ratio stays unchanged.","Opposite and adjacent are relative names: changing the reference angle can exchange them.","At 30°, sin θ=1/2, so a 10 cm hypotenuse gives a 5 cm opposite side.","If the hypotenuse doubles while θ is fixed, what happens to sin θ?","Both relevant side lengths double, so their ratio and sin θ remain unchanged.","Sine is the length of the opposite side.","Keep θ fixed and change hypotenuse; compare the opposite length with the sine value.","Opposite length changes, but sine is a dimensionless ratio and stays fixed.","Find an angle for which the legs are equal.","45°","A right isosceles triangle has opposite=adjacent, so tan θ=1.","Trigonometric ratios encode shape, not scale.","hypotenuse",listOf(v("θ","reference angle","degrees","angle","controls triangle shape"),v("sin θ","opposite/hypotenuse","","opposite","dimensionless ratio"),v("cos θ","adjacent/hypotenuse","","adjacent","dimensionless ratio"),v("tan θ","opposite/adjacent","","opposite","dimensionless ratio"))))
 val probability=build("math-probability-experiment",AuthoredExperienceCopy("Probability · Experimental and theoretical probability","A sample-space model compares theoretical probability, expected frequency, and reproducible trial frequency.",listOf("fractions","equally likely outcomes"),"For equally likely outcomes, probability is favourable outcomes divided by total outcomes. Expected frequency is a long-run centre, not a promised result for one experiment.","Increasing trials usually reduces relative fluctuation, but never guarantees exact agreement with theory.","For one marked face of a fair die, P=1/6; in 120 rolls the expected count is 20.","Will doubling the trial count necessarily double the observed successes exactly?","Expected count doubles, but an individual experimental count can fluctuate.","A probability of 1/2 means every two trials contain exactly one success.","Choose probability 1/2 and compare small and large trial counts.","Short sequences vary; the probability describes a long-run model, not a fixed alternating pattern.","Build an event with probability 1/4 and expected count 100.","Choose favourable/total=1/4 and 400 trials.","400×1/4=100 expected successes.","Theory predicts a distribution of possible results, not a compulsory short-run pattern.","sample-space",listOf(v("P(E)","event probability","","sample-space","favourable/total"),v("n","trials","trials","trials","direct effect on expected count"),v("nP(E)","expected successes","successes","frequency-bar","product")),comparisonLabels="theoretical probability" to "experimental relative frequency"))
 val all=listOf(linear,triangles,coordinate,trig,probability)
}
