package com.indianservers.aiexplorer.chemistry.ncert

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.*

object ChemistryNcertBatch02Content {
    private const val cid="cbse-2026-c10-chemistry-c2"; private const val tid="$cid-core"
    private fun q(id:String,t:CurriculumQuestionType,c:CompetencyType,p:String,a:String,e:String,s:String)=CurriculumQuestion("chem-acid-$id",SchoolSubject.CHEMISTRY,SchoolClassLevel.CLASS_10,cid,listOf(tid),c,QuestionDifficulty.STANDARD,t,p,answer=AnswerDefinition(a),explanation=e,commonErrorTags=listOf("acid-base reasoning"),remediationSectionId=s)
    val acidsBasesSalts=SubjectOwnedCurriculumChapter(
        "chemistry-ncert-c10-acids-production",cid,SchoolSubject.CHEMISTRY,SchoolClassLevel.CLASS_10,"Acids, Bases and Salts","Chemical Substances – Nature and Behaviour",120,"chemistry/ncert/10/acids-bases-salts",listOf(tid),
        listOf("Use indicators and pH as evidence rather than taste.","Represent acid/base behaviour in aqueous solution.","Write balanced neutralisation and carbonate equations with states.","Relate common salts to preparation, properties and safe applications."),
        listOf("Ions and aqueous solutions","Chemical equations and state symbols","Concentration as a qualitative variable"),
        linkedMapOf(
            "aqueous-behaviour" to "Acidic and basic behaviour depends on ions in water. Dry substances may not show the same indicator behaviour because ion formation and movement require an aqueous medium.",
            "indicators-ph" to "Indicators change colour over characteristic ranges. pH orders hydrogen-ion conditions on a logarithmic scale; a one-unit change represents a tenfold change, so pH values must not be treated as ordinary linear distances.",
            "reactions" to "Acid plus base gives salt and water. Acids with suitable carbonates produce salt, water and carbon dioxide. Equations must use verified formulas, state symbols and conditions.",
            "salts" to "A salt's properties depend on its ions and preparation. Common school examples such as sodium hydrogen carbonate and hydrated salts need correct names, formulas, water-of-crystallisation notation and safe use contexts.",
            "safety" to "Never identify acids or bases by tasting or touching. Dilution and neutralisation can release heat; only teacher-approved dilute reagents are used with eye protection."
        ),
        linkedMapOf("indicator" to "A substance showing a visible response over an acidity range.","pH" to "A logarithmic measure related to hydrogen-ion conditions.","neutralisation" to "Reaction of acid and base forming salt and water.","water of crystallisation" to "Fixed water molecules incorporated in a crystalline salt."),
        listOf(WorkedExample("Write the equation for hydrochloric acid neutralising sodium hydroxide.",listOf("Products are sodium chloride and water.","Use states for dilute solutions.","Check H, Cl, Na and O counts."),"HCl(aq)+NaOH(aq)→NaCl(aq)+H₂O(l)","Atoms and net charge are conserved."),WorkedExample("A solution changes from pH 3 to pH 5. Compare hydrogen-ion conditions.",listOf("The pH rises by 2 units.","Each unit is a factor of 10.","Hydrogen-ion concentration is 10² times lower."),"100 times lower hydrogen-ion concentration.","The logarithmic direction is checked: higher pH means lower hydrogen-ion concentration.")),
        listOf(CurriculumDiagramSpecification("chem-c10-ph-scale",SchoolSubject.CHEMISTRY,SchoolClassLevel.CLASS_10,tid,"pH scale with indicator evidence",DiagramType.TABLE,listOf(DiagramLabelRequirement("acidic","pH below 7","acidic region"),DiagramLabelRequirement("neutral","pH 7","neutral reference"),DiagramLabelRequirement("basic","pH above 7","basic region"),DiagramLabelRequirement("log","tenfold per unit","logarithmic meaning")),"Connect measured indicator evidence to a non-linear scale.",listOf("The scale is labelled logarithmic.","Colours are supplemented by text for accessibility.","Universal-indicator estimates are not presented as exact meter readings."),DiagramInteractionMode.LABEL_HIDE_AND_QUIZ,"A numbered pH scale from 0 to 14 marks acidic, neutral and basic regions, with a tenfold-change annotation between adjacent values and text indicator descriptions.",ScientificReviewStatus.VERIFIED)),
        emptyList(),listOf("Use safe household-context data cards to order solutions by pH without handling or tasting them.","Model neutralisation with equal H⁺ and OH⁻ counters, leaving spectator-ion salt counters visible."),
        listOf(CurriculumPracticalContent("chem-c10-indicator-practical",PracticalSupportType.PHYSICAL_LAB_GUIDANCE,"Classify teacher-approved dilute samples using indicators and record evidence.",listOf("spotting tile/test tubes","droppers","pH paper or approved indicators","eye protection"),listOf("teacher-labelled dilute samples","indicator chart"),listOf("Read labels and hazards before use.","Place separate small samples in labelled wells.","Add the specified indicator with a clean dropper.","Record observed colour before consulting the chart.","Estimate a range, not false exact precision; dispose as instructed."),listOf("sample code","indicator","observed colour","estimated acidic/basic/neutral range"),emptyList(),"Sample ______ is classified as ______ because ______.",listOf("Use a separate dropper for each sample.","Do not return samples to stock containers.","Record ambiguous colours honestly."),listOf("Wear eye protection.","Never taste or directly touch samples.","Teacher supervision and approved dilute reagents are mandatory."),listOf("Why use sample codes?","Why can indicator paper give a range rather than exact pH?","Why must droppers remain separate?"),true)),
        linkedMapOf("Strong means concentrated." to "Strength concerns ionisation; concentration concerns amount per volume.","pH 4 is twice as acidic as pH 8." to "The scale is logarithmic, not linear.","Neutralisation always ends at pH 7." to "That depends on reactants and endpoint conditions; do not generalise beyond the stated school case."),
        listOf(q("mcq",CurriculumQuestionType.MULTIPLE_CHOICE,CompetencyType.UNDERSTANDING,"Which is safe evidence for acidity?","An approved indicator response.","Taste and touch are unsafe and invalid methods.","indicators-ph"),q("numeric",CurriculumQuestionType.NUMERIC_INPUT,CompetencyType.APPLYING,"How many times does hydrogen-ion concentration change from pH 2 to pH 5?","1000 times lower","Three pH units correspond to 10³.","indicators-ph"),q("assert",CurriculumQuestionType.ASSERTION_REASON,CompetencyType.ANALYSING,"Assertion: dry HCl gas does not change dry indicator paper. Reason: acidic behaviour requires ions formed in water.","Both true; the reason explains the assertion.","Aqueous ion formation is required for the indicator response.","aqueous-behaviour"),q("case",CurriculumQuestionType.CASE_BASED,CompetencyType.EVALUATING,"Two colour-blind learners must compare indicator results. Improve the record design.","Record indicator name, sample code and textual colour/range; do not rely on colour alone.","Accessible redundant encoding preserves evidence.","indicators-ph"),q("experiment",CurriculumQuestionType.EXPERIMENTAL_REASONING,CompetencyType.ANALYSING,"A dropper touches one sample then another. Why repeat the test?","Cross-contamination can change the second sample and its indicator response.","A clean separate dropper controls contamination.","safety")),
        CurriculumRevisionResource(listOf("Acid/base evidence is obtained safely in water.","pH is logarithmic.","Balance equations with states.","Salt properties depend on ions and hydration."),listOf("acid+base→salt+water","acid+carbonate→salt+water+CO₂"),listOf("pH scale uses text plus colour and tenfold annotations."),listOf("strength versus concentration","indicator estimate versus exact pH","coefficient versus subscript"),listOf("chem-acid-mcq","chem-acid-assert")),
        listOf("Chemical Reactions and Equations","Metals and Non-metals","Class XI Equilibrium"),CurriculumCompletionRequirements(true,true,false,true,true,true,true,true,true),ScientificReviewStatus.VERIFIED)
    val chapters=listOf(acidsBasesSalts)
}
