package com.indianservers.aiexplorer.chemistry.ncert

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.*

object ChemistryNcertProductionContent {
    private const val chapterId = "cbse-2026-c10-chemistry-c1"
    private const val topicId = "$chapterId-core"
    private fun q(id: String, type: CurriculumQuestionType, competency: CompetencyType, prompt: String, answer: String, explanation: String, error: String, section: String) = CurriculumQuestion("chem-reaction-$id", SchoolSubject.CHEMISTRY, SchoolClassLevel.CLASS_10, chapterId, listOf(topicId), competency, QuestionDifficulty.STANDARD, type, prompt, answer = AnswerDefinition(answer), explanation = explanation, commonErrorTags = listOf(error), remediationSectionId = section)

    val chemicalReactions = SubjectOwnedCurriculumChapter(
        id = "chemistry-ncert-c10-reactions-production", curriculumNodeId = chapterId, subject = SchoolSubject.CHEMISTRY, classLevel = SchoolClassLevel.CLASS_10,
        officialChapterTitle = "Chemical Reactions and Equations", unitTitle = "Chemical Substances – Nature and Behaviour", estimatedMinutes = 120, route = "chemistry/ncert/10/chemical-reactions-and-equations",
        topicIds = listOf(topicId),
        learningObjectives = listOf("Identify evidence for chemical change without treating one observation as conclusive in every case.", "Write and balance equations while preserving formulas.", "Include state symbols and stated conditions.", "Classify common reactions and connect oxidation-reduction with everyday effects."),
        prerequisites = listOf("Elements, compounds and mixtures", "Chemical symbols and formula writing", "Conservation of mass"),
        explanationSections = linkedMapOf(
            "evidence" to "A chemical reaction rearranges atoms into new substances. Useful evidence includes sustained colour change, gas formation, precipitate formation, temperature change, light or a new odour. Evidence must be interpreted with context because a physical change can share an observation such as temperature change.",
            "equations" to "A word equation names substances; a chemical equation uses correct formulas. State symbols are (s), (l), (g) and (aq). Conditions such as heat, light or a catalyst belong near the arrow and must not be invented.",
            "balancing" to "Balancing changes only whole-number coefficients, never the subscripts inside a correct formula. Count atoms of every element on both sides and reduce coefficients to the smallest whole-number ratio.",
            "types" to "Combination forms fewer products; decomposition splits a compound using energy; displacement depends on relative reactivity; double displacement exchanges ions and may form a precipitate. Classification follows the actual equation and observations.",
            "redox" to "Oxidation and reduction occur together as electron transfer or changes in oxygen/hydrogen under the school model. Corrosion is a slow environmental redox process; rancidity involves oxidation of fats and oils."
        ),
        keyTerms = linkedMapOf("reactant" to "A starting substance in a reaction.", "product" to "A substance formed.", "coefficient" to "A whole-number multiplier placed before a formula.", "precipitate" to "An insoluble solid formed from solution.", "oxidation" to "Loss of electrons or, in the introductory model, gain of oxygen/loss of hydrogen.", "reduction" to "Gain of electrons or, in the introductory model, loss of oxygen/gain of hydrogen."),
        workedExamples = listOf(
            WorkedExample("Balance aluminium reacting with oxygen to form aluminium oxide.", listOf("Skeleton: Al(s)+O₂(g)→Al₂O₃(s).", "Use 2Al₂O₃ to make six oxygen atoms on the product side.", "Use 3O₂ for six oxygen atoms and 4Al for four aluminium atoms."), "4Al(s)+3O₂(g)→2Al₂O₃(s)", "Al:4=4; O:6=6. Formulas and states are unchanged."),
            WorkedExample("Classify Zn(s)+CuSO₄(aq)→ZnSO₄(aq)+Cu(s).", listOf("Zinc replaces copper in its compound.", "The equation is already balanced 1:1:1:1.", "The reaction is single displacement and also redox."), "Displacement reaction; zinc is oxidised and copper ions are reduced.", "Atoms and net charge are conserved.")
        ),
        diagrams = listOf(
            CurriculumDiagramSpecification("chem-c10-reaction-conservation-model", SchoolSubject.CHEMISTRY, SchoolClassLevel.CLASS_10, topicId, "Particle accounting during equation balancing", DiagramType.PARTICLE_MODEL, listOf(DiagramLabelRequirement("reactants", "reactant particles", "before reaction"), DiagramLabelRequirement("products", "product particles", "after reaction"), DiagramLabelRequirement("count", "same atom count", "conservation invariant")), "Show that balancing conserves each atom type without changing molecular formulas.", listOf("Colour and shape legend identifies elements.", "Particles are schematic and not to scale.", "Coefficients duplicate complete particles; subscripts remain fixed."), DiagramInteractionMode.LABEL_HIDE_AND_QUIZ, "Two panels show four aluminium atoms and three oxygen molecules rearranged into two formula units of aluminium oxide; equal atom counts are listed.", ScientificReviewStatus.VERIFIED),
            CurriculumDiagramSpecification("chem-c10-reaction-apparatus", SchoolSubject.CHEMISTRY, SchoolClassLevel.CLASS_10, topicId, "Gas-evolution observation setup", DiagramType.APPARATUS, listOf(DiagramLabelRequirement("tube", "test tube", "reaction vessel"), DiagramLabelRequirement("delivery", "delivery tube", "gas path"), DiagramLabelRequirement("collector", "collection/test arrangement", "observation")), "Relate apparatus to safe observation rather than unsupported identification.", listOf("No sealed heating system.", "Gas tests require teacher-approved reagents and supervision.", "Diagram does not imply smelling directly."), DiagramInteractionMode.STATIC_WITH_LABELS, "A supported test tube connected by a delivery tube to a labelled collection or test arrangement, with safety screen and no direct inhalation.", ScientificReviewStatus.VERIFIED)
        ),
        formulaLinks = emptyList(),
        activities = listOf("Balance equation cards by adding whole reactant/product groups; reject any move that changes a formula subscript.", "Sort observation cards into direct evidence, supporting evidence, and insufficient evidence, and defend each choice."),
        practicals = listOf(CurriculumPracticalContent("chem-c10-reaction-types-practical", PracticalSupportType.PHYSICAL_LAB_GUIDANCE, "Observe teacher-approved examples of combination, decomposition, displacement and double-displacement reactions and connect observations to balanced equations.", listOf("test tubes and stand", "droppers", "spatula", "heat source only when explicitly approved", "eye protection"), listOf("Only school-laboratory reagents selected and labelled by the teacher", "distilled water where directed"), listOf("Read reagent-specific hazard guidance before starting.", "Record initial appearance and temperature qualitatively or quantitatively as instructed.", "Combine only the directed quantities; never substitute a reagent.", "Record colour, gas, precipitate and temperature observations without tasting or direct smelling.", "Write a word equation, then a formula equation with states and verified conditions.", "Dispose of products using the laboratory's waste procedure."), listOf("initial and final appearance", "gas/precipitate evidence", "temperature reading if required", "balanced equation with state symbols", "reaction classification with reason"), emptyList(), "The observed change ______ supports a ______ reaction represented by ______.", listOf("Do not change formula subscripts while balancing.", "Do not return unused reagent to stock bottles.", "Use clean droppers to prevent contamination."), listOf("Eye protection and teacher supervision are mandatory.", "Never heat a closed vessel.", "Do not directly inhale gases.", "Follow local chemical disposal instructions."), listOf("Why are state symbols useful?", "Why can a colour change alone be insufficient?", "What does a precipitate show?", "Why must equations be balanced?"), true)),
        misconceptions = linkedMapOf("Balancing means changing subscripts." to "Changing a subscript changes the substance; adjust coefficients only.", "Every temperature change proves a reaction." to "Dissolving and phase changes can also change temperature.", "Oxidation always requires oxygen gas." to "The broader electron-transfer definition includes reactions without oxygen gas."),
        questions = listOf(
            q("mcq", CurriculumQuestionType.MULTIPLE_CHOICE, CompetencyType.UNDERSTANDING, "Which edit correctly balances H₂+O₂→H₂O?", "2H₂+O₂→2H₂O", "Coefficients give four H and two O atoms on each side.", "balancing", "balancing"),
            q("match", CurriculumQuestionType.MATCH_FOLLOWING, CompetencyType.APPLYING, "Match: CaO+H₂O→Ca(OH)₂; 2AgCl→2Ag+Cl₂; Fe+CuSO₄→FeSO₄+Cu with combination, decomposition, displacement.", "combination; decomposition; displacement", "The number and identity of reactants/products determine the school-level types.", "reaction type", "types"),
            q("assert", CurriculumQuestionType.ASSERTION_REASON, CompetencyType.ANALYSING, "Assertion: coefficients may be changed to balance an equation. Reason: coefficients change the ratio of complete particles without changing substance identity.", "Both are true and the reason explains the assertion.", "Subscripts define formula identity; coefficients count formula units.", "balancing", "balancing"),
            q("case", CurriculumQuestionType.CASE_BASED, CompetencyType.EVALUATING, "An iron nail in blue copper sulfate develops a brown coating and the solution colour weakens. Interpret the observations and write the equation.", "Fe(s)+CuSO₄(aq)→FeSO₄(aq)+Cu(s); displacement/redox.", "More reactive iron displaces copper; deposited copper forms the coating.", "reactivity", "types"),
            q("experiment", CurriculumQuestionType.EXPERIMENTAL_REASONING, CompetencyType.ANALYSING, "A group sees bubbles after mixing two liquids. What evidence is still needed before naming the gas?", "A safe, teacher-approved characteristic test; bubbles alone do not identify the gas.", "Observation establishes gas evolution but not chemical identity.", "observation inference", "evidence")
        ),
        revision = CurriculumRevisionResource(listOf("New substances form by atom rearrangement.", "Balance with coefficients, not subscripts.", "Write verified states and conditions.", "Classify using equation pattern plus evidence.", "Oxidation and reduction are coupled."), listOf("No universal calculation formula; conserve atom count and charge."), listOf("Particle model preserves atom counts.", "Apparatus layouts must show safe gas handling."), listOf("coefficient versus subscript", "gas evolution versus gas identification", "oxidation versus combustion"), listOf("chem-reaction-mcq", "chem-reaction-assert", "chem-reaction-experiment")),
        relationships = listOf("Acids, Bases and Salts", "Metals and Non-metals", "Carbon and its Compounds"),
        requirements = CurriculumCompletionRequirements(true, true, false, true, true, true, true, true, true), reviewStatus = ScientificReviewStatus.VERIFIED
    )
    val chapters = listOf(chemicalReactions)
}
