package com.indianservers.aiexplorer.core

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.acos
import kotlin.math.cos
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin
import kotlin.math.sqrt

sealed interface ExactSolidNode { data class Primitive(val solid:Solid):ExactSolidNode;data class Boolean(val operation:BooleanMeshOperation,val first:ExactSolidNode,val second:ExactSolidNode):ExactSolidNode }
data class HybridSolid(val exact:ExactSolidNode,val displayMesh:SolidMesh,val closed:Boolean,val diagnostic:String)
data class SpatialBounds(val minimum:Vec3,val maximum:Vec3){init{require(minimum.x<maximum.x&&minimum.y<maximum.y&&minimum.z<maximum.z)}}
object HybridExactSolidEngine { fun primitive(solid:Solid)=HybridSolid(ExactSolidNode.Primitive(solid),SolidMeshFactory.create(solid),true,"Exact primitive with tessellated display mesh.");fun combine(a:HybridSolid,b:HybridSolid,operation:BooleanMeshOperation):HybridSolid{val result=BooleanMeshEngine.apply(a.displayMesh,b.displayMesh,operation);return HybridSolid(ExactSolidNode.Boolean(operation,a.exact,b.exact),result.mesh,result.verified,"Exact CSG tree retained; ${result.diagnostic}")} }

data class AdaptiveSurfaceSample(val vertices:List<Vec3>,val resolutionLevels:Map<Int,Int>,val clippedCells:Int)
object AdaptiveImplicitSurfaceEngine { fun sample(function:(Double,Double,Double)->Double,bounds:SpatialBounds,base:Int=12,maxDepth:Int=3,focus:Vec3?=null):AdaptiveSurfaceSample{val vertices=mutableListOf<Vec3>();val levels=mutableMapOf<Int,Int>();var clipped=0;fun cell(minimum:Vec3,maximum:Vec3,depth:Int){val corners=listOf(Vec3(minimum.x,minimum.y,minimum.z),Vec3(maximum.x,minimum.y,minimum.z),Vec3(minimum.x,maximum.y,minimum.z),Vec3(maximum.x,maximum.y,minimum.z),Vec3(minimum.x,minimum.y,maximum.z),Vec3(maximum.x,minimum.y,maximum.z),Vec3(minimum.x,maximum.y,maximum.z),Vec3(maximum.x,maximum.y,maximum.z));val values=corners.map{function(it.x,it.y,it.z)};if(values.any{!it.isFinite()}){clipped++;return};if(values.min() > 0 || values.max() < 0)return;val center=(minimum+maximum)*.5;val nearFocus=focus?.let{(it-center).magnitude()<(maximum-minimum).magnitude()*2}?:false;if(depth<maxDepth&&(nearFocus||values.max()-values.min()>1.0)){levels[depth]=(levels[depth]?:0)+1;val mid=center;for(ix in 0..1)for(iy in 0..1)for(iz in 0..1)cell(Vec3(if(ix==0)minimum.x else mid.x,if(iy==0)minimum.y else mid.y,if(iz==0)minimum.z else mid.z),Vec3(if(ix==0)mid.x else maximum.x,if(iy==0)mid.y else maximum.y,if(iz==0)mid.z else maximum.z),depth+1)}else vertices+=center};val d=bounds.maximum-bounds.minimum;for(i in 0 until base)for(j in 0 until base)for(k in 0 until base){val lo=Vec3(bounds.minimum.x+d.x*i/base,bounds.minimum.y+d.y*j/base,bounds.minimum.z+d.z*k/base);val hi=Vec3(bounds.minimum.x+d.x*(i+1)/base,bounds.minimum.y+d.y*(j+1)/base,bounds.minimum.z+d.z*(k+1)/base);cell(lo,hi,0)};return AdaptiveSurfaceSample(vertices,levels,clipped)} }

enum class SurfaceSingularityKind { CriticalPoint, DegenerateGradient, Undefined, SelfIntersectionCandidate }
data class SurfaceSingularity(val point:Vec3,val kind:SurfaceSingularityKind,val gradient:Vec3,val determinantHint:Double,val explanation:String)
object SurfaceSingularityAnalyzer { fun analyse(function:(Double,Double,Double)->Double,candidates:List<Vec3>,h:Double=1e-4):List<SurfaceSingularity>{return candidates.mapNotNull{p->val f=runCatching{function(p.x,p.y,p.z)}.getOrNull();if(f==null||!f.isFinite())SurfaceSingularity(p,SurfaceSingularityKind.Undefined,Vec3(0.0,0.0,0.0),Double.NaN,"Surface is undefined.")else{val gx=(function(p.x+h,p.y,p.z)-function(p.x-h,p.y,p.z))/(2*h);val gy=(function(p.x,p.y+h,p.z)-function(p.x,p.y-h,p.z))/(2*h);val gz=(function(p.x,p.y,p.z+h)-function(p.x,p.y,p.z-h))/(2*h);val g=Vec3(gx,gy,gz);if(g.magnitude()<1e-5)SurfaceSingularity(p,SurfaceSingularityKind.DegenerateGradient,g,0.0,"Implicit-function theorem fails at this point.")else null}}} }

enum class MechanicalJointKind { Hinge, Slider, Gear, Rigid, Collision }
data class MechanicalJoint(val id:String,val kind:MechanicalJointKind,val first:Int,val second:Int,val axis:Vec3=Vec3(0.0,1.0,0.0),val ratio:Double=1.0,val minimum:Double=-Double.MAX_VALUE,val maximum:Double=Double.MAX_VALUE)
data class MechanismState(val values:Map<String,Double>,val collisions:Set<Pair<Int,Int>>,val satisfied:Boolean)
object MechanicalConstraintEngine { fun solve(joints:List<MechanicalJoint>,drivers:Map<String,Double>):MechanismState{val values=joints.associate{j->val raw=drivers[j.id]?:0.0;j.id to raw.coerceIn(j.minimum,j.maximum)}.toMutableMap();joints.filter{it.kind==MechanicalJointKind.Gear}.forEach{j->values[j.id]=(values[j.id]?:0.0)*j.ratio};return MechanismState(values,joints.filter{it.kind==MechanicalJointKind.Collision&&drivers[it.id]?.let{v->v>0}==true}.map{it.first to it.second}.toSet(),values.values.all{it.isFinite()})} }

data class ClipPlane3D(val id:String,val point:Vec3,val normal:Vec3,val keepPositive:Boolean=true)
data class ClippingVolume(val planes:List<ClipPlane3D>){fun contains(p:Vec3)=planes.all{val side=(p-it.point).dot(it.normal);if(it.keepPositive)side>=-1e-10 else side<=1e-10};fun clip(mesh:SolidMesh)=mesh.copy(faces=mesh.faces.filter{face->face.mapNotNull(mesh.vertices::getOrNull).any(::contains)})}
object ClippingVolumeFactory { fun box(minimum:Vec3,maximum:Vec3)=ClippingVolume(listOf(ClipPlane3D("left",minimum,Vec3(1.0,0.0,0.0)),ClipPlane3D("right",maximum,Vec3(-1.0,0.0,0.0)),ClipPlane3D("bottom",minimum,Vec3(0.0,1.0,0.0)),ClipPlane3D("top",maximum,Vec3(0.0,-1.0,0.0)),ClipPlane3D("near",minimum,Vec3(0.0,0.0,1.0)),ClipPlane3D("far",maximum,Vec3(0.0,0.0,-1.0)))) }

data class SpatialIntegralResult(val estimate:Double,val sampleCount:Int,val regionMeasure:Double,val errorEstimate:Double,val unit:String)
object InteractiveSpatialIntegralEngine { fun volume(bounds:SpatialBounds,samples:Int=40,inside:(Vec3)->Boolean,integrand:(Vec3)->Double={1.0}):SpatialIntegralResult{val d=bounds.maximum-bounds.minimum;val cell=d.x*d.y*d.z/(samples*samples*samples);var sum=0.0;var accepted=0;for(i in 0 until samples)for(j in 0 until samples)for(k in 0 until samples){val p=Vec3(bounds.minimum.x+d.x*(i+.5)/samples,bounds.minimum.y+d.y*(j+.5)/samples,bounds.minimum.z+d.z*(k+.5)/samples);if(inside(p)){sum+=integrand(p);accepted++}};val estimate=sum*cell;return SpatialIntegralResult(estimate,samples*samples*samples,accepted*cell,abs(estimate)/sqrt(max(1,accepted).toDouble()),"u^3")};fun surface(mesh:SolidMesh,integrand:(Vec3)->Double={1.0}):SpatialIntegralResult{var total=0.0;var weighted=0.0;var triangles=0;mesh.faces.forEach{f->val ps=f.mapNotNull(mesh.vertices::getOrNull);for(i in 1 until ps.lastIndex){val center=(ps[0]+ps[i]+ps[i+1])*(1.0/3);val area=AnalyticGeometry3D.cross(ps[i]-ps[0],ps[i+1]-ps[0]).magnitude()*.5;total+=area;weighted+=area*integrand(center);triangles++}};return SpatialIntegralResult(weighted,triangles,total,0.0,"u^2")} }

data class FlowPath3D(val seed:Vec3,val points:List<Vec3>,val divergenceSamples:List<Double>)
object SpatialFluxFlowEngine { fun trace(seed:Vec3,field:(Vec3)->Vec3,step:Double=.03,count:Int=1000):FlowPath3D{val points=mutableListOf(seed);val divergence=mutableListOf<Double>();val h=1e-4;repeat(count){val p=points.last();val v=field(p);val m=v.magnitude();if(m<1e-12||!m.isFinite())return@repeat;points+=p+v*(step/m);val dx=(field(p+Vec3(h,0.0,0.0)).x-field(p-Vec3(h,0.0,0.0)).x)/(2*h);val dy=(field(p+Vec3(0.0,h,0.0)).y-field(p-Vec3(0.0,h,0.0)).y)/(2*h);val dz=(field(p+Vec3(0.0,0.0,h)).z-field(p-Vec3(0.0,0.0,h)).z)/(2*h);divergence+=dx+dy+dz};return FlowPath3D(seed,points,divergence)} }

data class MeshTopologyReport(val components:Int,val boundaryLoops:Int,val eulerCharacteristic:Int,val genus:Int?,val manifold:Boolean,val nonManifoldEdges:List<Pair<Int,Int>>)
object MeshTopologyInspector { fun inspect(mesh:SolidMesh):MeshTopologyReport{val edgeFaces=mutableMapOf<Pair<Int,Int>,Int>();mesh.faces.forEach{f->f.indices.forEach{i->val e=listOf(f[i],f[(i+1)%f.size]).sorted().let{it[0] to it[1]};edgeFaces[e]=(edgeFaces[e]?:0)+1}};val adjacency=mesh.vertices.indices.associateWith{mutableSetOf<Int>()};mesh.edges.forEach{(a,b)->adjacency[a]?.add(b);adjacency[b]?.add(a)};val unseen=mesh.vertices.indices.toMutableSet();var components=0;while(unseen.isNotEmpty()){components++;val stack=mutableListOf(unseen.first());while(stack.isNotEmpty()){val v=stack.removeLast();if(unseen.remove(v))stack+=adjacency[v].orEmpty()}};val boundary=edgeFaces.filterValues{it==1}.keys;val non=edgeFaces.filterValues{it>2}.keys.toList();val euler=mesh.vertices.size-edgeFaces.size+mesh.faces.size;val closed=boundary.isEmpty()&&non.isEmpty();val genus=if(closed)(2*components-euler)/2 else null;return MeshTopologyReport(components,countBoundaryLoops(boundary),euler,genus,non.isEmpty(),non)};private fun countBoundaryLoops(edges:Set<Pair<Int,Int>>):Int{val unseen=edges.toMutableSet();var loops=0;while(unseen.isNotEmpty()){loops++;val vertices=mutableSetOf<Int>();var changed=true;vertices+=unseen.first().toList();while(changed){changed=false;unseen.filter{it.first in vertices||it.second in vertices}.toList().forEach{unseen-=it;changed=vertices.add(it.first)||vertices.add(it.second)||changed}}};return loops} }

data class FabricationIssue(val severity:String,val code:String,val location:Vec3?,val explanation:String)
data class FabricationReport(val ready:Boolean,val issues:List<FabricationIssue>,val minimumThickness:Double,val dimensions:Vec3)
object FabricationReadinessEngine { fun inspect(mesh:SolidMesh,minimumWall:Double=.8,scaleMillimetres:Double=10.0,buildDirection:Vec3=Vec3(0.0,1.0,0.0)):FabricationReport{val topology=MeshTopologyInspector.inspect(mesh);val bounds=AnalyticGeometry3D.bounds(mesh.vertices)?:return FabricationReport(false,listOf(FabricationIssue("error","empty",null,"Mesh has no vertices.")),0.0,Vec3(0.0,0.0,0.0));val dims=(bounds.maximum-bounds.minimum)*scaleMillimetres;val thickness=min(dims.x,min(dims.y,dims.z));val issues=mutableListOf<FabricationIssue>();if(!topology.manifold)issues+=FabricationIssue("error","non-manifold",null,"Repair non-manifold edges.");if(topology.boundaryLoops>0)issues+=FabricationIssue("error","open-shell",null,"Close boundary loops.");if(thickness<minimumWall)issues+=FabricationIssue("warning","thin-wall",null,"Minimum dimension is below $minimumWall mm.");mesh.faces.forEach{f->val p=f.mapNotNull(mesh.vertices::getOrNull);if(p.size>=3){val n=AnalyticGeometry3D.cross(p[1]-p[0],p[2]-p[0]).normalized();if(n.dot(buildDirection)<-cos(Math.toRadians(45.0)))issues+=FabricationIssue("warning","support",p.reduce(Vec3::plus)*(1.0/p.size),"Down-facing region may require support.")}};return FabricationReport(issues.none{it.severity=="error"},issues,thickness,dims)} }

data class ArCalibration(val mathPoints:List<Vec3>,val physicalPointsMetres:List<Vec3>,val scaleMetresPerUnit:Double,val translationMetres:Vec3,val rmsErrorMetres:Double)
object CalibratedArWorkspace { fun calibrate(math:List<Vec3>,physical:List<Vec3>):ArCalibration{require(math.size==physical.size&&math.size>=2);val mathDistances=math.indices.flatMap{i->(i+1 until math.size).map{j->(math[i]-math[j]).magnitude()}};val physicalDistances=physical.indices.flatMap{i->(i+1 until physical.size).map{j->(physical[i]-physical[j]).magnitude()}};val scale=physicalDistances.zip(mathDistances).map{it.first/it.second.coerceAtLeast(1e-12)}.average();val mc=math.reduce(Vec3::plus)*(1.0/math.size);val pc=physical.reduce(Vec3::plus)*(1.0/physical.size);val translation=pc-mc*scale;val rms=sqrt(math.indices.sumOf{i->((math[i]*scale+translation)-physical[i]).magnitude().let{it*it}}/math.size);return ArCalibration(math,physical,scale,translation,rms)};fun toPhysical(point:Vec3,calibration:ArCalibration)=point*calibration.scaleMetresPerUnit+calibration.translationMetres }
