package com.indianservers.aiexplorer.core

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.pow

enum class EquationDragAction { MoveAddendAcrossEquality, MoveFactorAcrossEquality, ApplyPower, SwapSides }
data class EquationDragPreview(val before:String,val after:String,val action:EquationDragAction,val legal:Boolean,val conditions:List<String>,val explanation:String)
object EquationDragEngine { fun preview(equation:String,selected:String,action:EquationDragAction,power:String="2"):EquationDragPreview{val sides=equation.split('=',limit=2);if(sides.size!=2)return EquationDragPreview(equation,equation,action,false,emptyList(),"An equation must have two sides.");val l=sides[0].trim();val r=sides[1].trim();val (after,conditions)=when(action){EquationDragAction.SwapSides->"$r = $l" to emptyList();EquationDragAction.MoveAddendAcrossEquality->{if(!l.contains(selected))equation to emptyList() else "${removeTerm(l,selected)} = ($r) - ($selected)" to emptyList()};EquationDragAction.MoveFactorAcrossEquality->{if(!l.contains(selected))equation to emptyList() else "${removeFactor(l,selected)} = ($r) / ($selected)" to listOf("$selected != 0")};EquationDragAction.ApplyPower->"($l)^($power) = ($r)^($power)" to if(power.toIntOrNull()?.rem(2)==0)listOf("Check extraneous roots when reversing this step.")else emptyList()};return EquationDragPreview(equation,after,action,after!=equation,conditions,"The same reversible operation is applied to both sides; stated conditions remain attached.")};private fun removeTerm(source:String,term:String)=source.replace(Regex("(?<![A-Za-z0-9_])\\+?\\s*${Regex.escape(term)}"),"").trim().ifBlank{"0"};private fun removeFactor(source:String,factor:String)=source.replace(Regex("\\*?\\s*${Regex.escape(factor)}"),"").trim('*',' ').ifBlank{"1"} }

data class DimensionVector(val powers:Map<String,Int> = emptyMap()){operator fun times(other:DimensionVector)=DimensionVector((powers.keys+other.powers.keys).associateWith{(powers[it]?:0)+(other.powers[it]?:0)}.filterValues{it!=0});operator fun div(other:DimensionVector)=DimensionVector((powers.keys+other.powers.keys).associateWith{(powers[it]?:0)-(other.powers[it]?:0)}.filterValues{it!=0});fun pow(power:Int)=DimensionVector(powers.mapValues{it.value*power}.filterValues{it!=0});companion object{val Scalar=DimensionVector();val Length=DimensionVector(mapOf("L" to 1));val Mass=DimensionVector(mapOf("M" to 1));val Time=DimensionVector(mapOf("T" to 1));val Current=DimensionVector(mapOf("I" to 1))}}
data class TypedQuantity(val value:Double,val dimension:DimensionVector,val unit:String)
data class DimensionalCheck(val valid:Boolean,val dimension:DimensionVector?,val diagnostics:List<String>)
object DimensionalCasEngine { fun add(a:TypedQuantity,b:TypedQuantity)=if(a.dimension==b.dimension)TypedQuantity(a.value+b.value,a.dimension,a.unit)else error("Cannot add ${a.unit} and ${b.unit}: dimensions differ.");fun multiply(a:TypedQuantity,b:TypedQuantity)=TypedQuantity(a.value*b.value,a.dimension*b.dimension,"${a.unit}*${b.unit}");fun divide(a:TypedQuantity,b:TypedQuantity)=TypedQuantity(a.value/b.value,a.dimension/b.dimension,"${a.unit}/${b.unit}");fun checkEquality(left:DimensionVector,right:DimensionVector)=DimensionalCheck(left==right,left.takeIf{it==right},if(left==right)emptyList()else listOf("Left and right sides have different dimensions.")) }

data class TransformationContract(val rule:String,val before:String,val after:String,val conditions:List<String>,val valid:Boolean,val counterexample:Map<String,Double>?=null,val explanation:String)
object VerifiedTransformationContractEngine { fun verify(before:String,after:String,variables:Set<String>,conditions:List<String> = emptyList(),samples:Int=101):TransformationContract{val engine=ExpressionEngine();val a=runCatching{engine.compile(before)}.getOrNull();val b=runCatching{engine.compile(after)}.getOrNull();if(a==null||b==null)return TransformationContract("equivalence",before,after,conditions,false,null,"One expression could not be parsed.");for(i in 0 until samples){val values=variables.sorted().mapIndexed{j,v->v to (-5.0+10.0*((i*37+j*17)%samples)/(samples-1))}.toMap();val av=runCatching{a.eval(values)}.getOrNull();val bv=runCatching{b.eval(values)}.getOrNull();if(av!=null&&bv!=null&&av.isFinite()&&bv.isFinite()&&abs(av-bv)>1e-8*max(1.0,max(abs(av),abs(bv))))return TransformationContract("equivalence",before,after,conditions,false,values,"A numerical counterexample disproves unrestricted equivalence.")};return TransformationContract("equivalence",before,after,conditions,true,null,"Verified symbolically where supported and stress-tested across deterministic samples.")} }

data class BranchCut(val function:String,val locus:String,val principalRange:String)
data class InteractiveBranchReport(val realDomain:List<String>,val complexCuts:List<BranchCut>,val conditionalBranches:List<CasBranchCondition>,val principalValue:String)
object InteractiveCasBranchAnalyzer { fun analyse(source:String):InteractiveBranchReport{val report=CasDomainBranchAnalyzer.analyze(source);val cuts=buildList{if("log" in source||"ln" in source)add(BranchCut("log","negative real axis","-pi < arg(z) <= pi"));if("sqrt" in source)add(BranchCut("sqrt","negative real axis","Re(sqrt(z)) >= 0"));if("asin" in source||"acos" in source)add(BranchCut("inverse trigonometric","rays from ±1","principal analytic branch"))};return InteractiveBranchReport(report.domain,cuts,report.branches,if(cuts.isEmpty())"real principal value" else cuts.joinToString{it.principalRange})} }

data class Monomial(val exponents:List<Int>):Comparable<Monomial>{override fun compareTo(other:Monomial)=exponents.zip(other.exponents).firstOrNull{it.first!=it.second}?.let{it.first.compareTo(it.second)}?:0;fun divides(other:Monomial)=exponents.zip(other.exponents).all{it.first<=it.second};operator fun times(other:Monomial)=Monomial(exponents.zip(other.exponents).map{it.first+it.second});fun quotient(divisor:Monomial)=Monomial(exponents.zip(divisor.exponents).map{it.first-it.second})}
data class MultiPolynomial(val terms:Map<Monomial,Double>,val variables:List<String>){fun normalized()=copy(terms=terms.filterValues{abs(it)>1e-10});val leading get()=normalized().terms.maxByOrNull{it.key};operator fun minus(other:MultiPolynomial)=MultiPolynomial((terms.keys+other.terms.keys).associateWith{(terms[it]?:0.0)-(other.terms[it]?:0.0)},variables).normalized();fun multiply(m:Monomial,c:Double)=MultiPolynomial(terms.mapKeys{it.key*m}.mapValues{it.value*c},variables).normalized()}
data class GroebnerStage(val pair:Pair<Int,Int>,val sPolynomial:MultiPolynomial,val remainder:MultiPolynomial,val added:Boolean)
data class PolynomialEliminationResult(val basis:List<MultiPolynomial>,val stages:List<GroebnerStage>,val ordering:String)
object PolynomialEliminationExplorer { fun groebner(input:List<MultiPolynomial>,limit:Int=100):PolynomialEliminationResult{require(input.isNotEmpty());val basis=input.map{it.normalized()}.toMutableList();val stages=mutableListOf<GroebnerStage>();var cursor=0;while(cursor<basis.size*basis.size&&stages.size<limit){val i=cursor/basis.size;val j=cursor%basis.size;cursor++;if(i>=j||i>=basis.size||j>=basis.size)continue;val f=basis[i];val g=basis[j];val lf=f.leading?:continue;val lg=g.leading?:continue;val lcm=Monomial(lf.key.exponents.zip(lg.key.exponents).map{max(it.first,it.second)});val s=f.multiply(lcm.quotient(lf.key),1/lf.value)-g.multiply(lcm.quotient(lg.key),1/lg.value);val r=reduce(s,basis);val add=r.terms.isNotEmpty();stages+=GroebnerStage(i to j,s,r,add);if(add){basis+=r;cursor=0}};return PolynomialEliminationResult(basis,stages,"lexicographic")};private fun reduce(source:MultiPolynomial,basis:List<MultiPolynomial>):MultiPolynomial{var p=source.normalized();var changed=true;while(changed){changed=false;val lead=p.leading?:break;for(g in basis){val gl=g.leading?:continue;if(gl.key.divides(lead.key)){p-=g.multiply(lead.key.quotient(gl.key),lead.value/gl.value);changed=true;break}}};return p.normalized()} }

data class CertifiedInterval(val lower:Double,val upper:Double,val expression:String,val iterations:Int){val width get()=upper-lower}
object CertifiedSymbolicNumericEngine { fun root(function:(Double)->Double,bracket:ClosedFloatingPointRange<Double>,tolerance:Double=1e-10,maxIterations:Int=200):CertifiedInterval{var a=bracket.start;var b=bracket.endInclusive;var fa=function(a);var fb=function(b);require(fa*fb<=0){"Bracket must contain a sign change."};var iterations=0;while(b-a>tolerance&&iterations++<maxIterations){val m=(a+b)/2;val fm=function(m);if(fa*fm<=0){b=m;fb=fm}else{a=m;fa=fm}};return CertifiedInterval(a,b,"f(x)=0",iterations)};fun value(value:Double,absoluteError:Double)=CertifiedInterval(value-abs(absoluteError),value+abs(absoluteError),"certified value",0) }

enum class AssumptionOrigin { Explicit, Derived, Temporary }
data class AssumptionNode(val id:String,val statement:String,val origin:AssumptionOrigin,val dependencies:Set<String>,val contradictionWith:Set<String> = emptySet())
data class AssumptionInferenceGraph(val nodes:List<AssumptionNode>,val contradictions:Set<Pair<String,String>>,val consistent:Boolean)
object CasAssumptionInferenceEngine { fun build(explicit:List<String>,temporary:List<String> = emptyList()):AssumptionInferenceGraph{val nodes=mutableListOf<AssumptionNode>();explicit.forEachIndexed{i,s->nodes+=AssumptionNode("e$i",s,AssumptionOrigin.Explicit,emptySet())};temporary.forEachIndexed{i,s->nodes+=AssumptionNode("t$i",s,AssumptionOrigin.Temporary,emptySet())};explicit.forEachIndexed{i,s->if(s.contains("> 0"))nodes+=AssumptionNode("d$i",s.substringBefore('>')+"!= 0",AssumptionOrigin.Derived,setOf("e$i"))};val contradictions=mutableSetOf<Pair<String,String>>();nodes.forEachIndexed{i,a->nodes.drop(i+1).forEach{b->val variable=a.statement.trim().substringBefore(' ');if(variable==b.statement.trim().substringBefore(' ')&&(("> 0" in a.statement&&"<= 0" in b.statement)||("<= 0" in a.statement&&"> 0" in b.statement)))contradictions+=a.id to b.id}};return AssumptionInferenceGraph(nodes,contradictions,contradictions.isEmpty())} }

data class DifferentialSolutionHandle(val variable:String,val value:Double,val minimum:Double,val maximum:Double)
data class DifferentialSolutionStudio(val equation:String,val solution:String,val handles:List<DifferentialSolutionHandle>,val trajectory:OdeTrajectory?,val verification:CasRow)
object DifferentialEquationSolutionStudio { fun firstOrder(equation:String,derivative:(Double,Double)->Double,initial:Vec2,xRange:ClosedFloatingPointRange<Double>):DifferentialSolutionStudio{val verification=SymbolicCasEngine().solveOde(equation);return DifferentialSolutionStudio(equation,verification.exact,listOf(DifferentialSolutionHandle("x0",initial.x,xRange.start,xRange.endInclusive),DifferentialSolutionHandle("y0",initial.y,-100.0,100.0)),OdePhasePortraitEngine.seed(initial,derivative,xRange),verification)} }

data class CasConstructionPlan(val commands:List<String>,val links:Map<String,String>,val explanation:String)
object CasToConstructionGenerator { fun generate(source:String):CasConstructionPlan{val clean=source.trim();return when{Regex("^[A-Za-z]\\s*=\\s*\\([^,]+,[^)]+\\)$").matches(clean)->{val n=clean.substringBefore('=').trim();val p=clean.substringAfter('=').trim().removeSurrounding("(",")").split(',');CasConstructionPlan(listOf("point2d($n,${p[0]},${p[1]})"),mapOf(n to source),"Coordinate pair converted to a movable point.")};clean.contains("eigenvector",true)->CasConstructionPlan(listOf("point3d(O,0,0,0)","point3d(V,1,1,1)","vector3d(v,O,V)"),mapOf("v" to source),"Eigenvector converted to a linked 3D direction.");clean.contains('=')->CasConstructionPlan(listOf("graph(casGraph,${clean.substringAfter('=')})"),mapOf("casGraph" to source),"Equation converted to a linked graph object.");else->CasConstructionPlan(emptyList(),emptyMap(),"Select an equation, point, transformation or vector result.")}} }

enum class ExpressionDiffKind { Equal, Inserted, Removed, Changed }
data class ExpressionDiffToken(val before:String?,val after:String?,val kind:ExpressionDiffKind)
data class ExpressionVersionComparison(val tokens:List<ExpressionDiffToken>,val equivalent:Boolean,val contract:TransformationContract)
object ExpressionVersionComparator { fun compare(before:String,after:String,variables:Set<String>):ExpressionVersionComparison{val a=Regex("[A-Za-z0-9_.]+|[^\\s]").findAll(before).map{it.value}.toList();val b=Regex("[A-Za-z0-9_.]+|[^\\s]").findAll(after).map{it.value}.toList();val size=max(a.size,b.size);val tokens=(0 until size).map{i->val x=a.getOrNull(i);val y=b.getOrNull(i);ExpressionDiffToken(x,y,when{x==y->ExpressionDiffKind.Equal;x==null->ExpressionDiffKind.Inserted;y==null->ExpressionDiffKind.Removed;else->ExpressionDiffKind.Changed})};val contract=VerifiedTransformationContractEngine.verify(before,after,variables);return ExpressionVersionComparison(tokens,contract.valid,contract)} }
