package com.indianservers.aiexplorer.solver.domain.catalogue

enum class SolverCalculatorGroup(val label: String) {
    ArithmeticPreAlgebra("Arithmetic and pre-algebra"),
    Algebra("Algebra"),
    FunctionsGraphs("Functions and graphs"),
    Trigonometry("Trigonometry"),
    Calculus("Calculus"),
    DifferentialEquations("Differential equations"),
    MultivariableVectorCalculus("Multivariable and vector calculus"),
    LinearAlgebra("Linear algebra"),
    SequencesSeries("Sequences and series"),
    ComplexNumbers("Complex numbers"),
}

data class SolverCalculatorPreset(
    val id: String,
    val title: String,
    val group: SolverCalculatorGroup,
    val starterExpression: String,
    val supported: Boolean,
    val description: String,
)

object SolverCalculatorCatalogue {
    val presets = listOf(
        preset("fraction", "Fraction calculator", SolverCalculatorGroup.ArithmeticPreAlgebra, "3/4 + 5/6"),
        preset("percentage", "Percentage calculator", SolverCalculatorGroup.ArithmeticPreAlgebra, "25% of 80"),
        preset("ratio", "Ratio calculator", SolverCalculatorGroup.ArithmeticPreAlgebra, "2/3 = x/12"),
        preset("scientific-notation", "Scientific notation", SolverCalculatorGroup.ArithmeticPreAlgebra, "3.2*10^5"),
        preset("prime-factor", "Prime factorisation", SolverCalculatorGroup.ArithmeticPreAlgebra, "primeFactors(84)"),
        preset("gcd-lcm", "GCD and LCM", SolverCalculatorGroup.ArithmeticPreAlgebra, "gcd(84,30)"),
        preset("base", "Base converter", SolverCalculatorGroup.ArithmeticPreAlgebra, "base(101101,2,10)"),
        preset("equation", "Equation solver", SolverCalculatorGroup.Algebra, "3x+5=20"),
        preset("inequality", "Inequality solver", SolverCalculatorGroup.Algebra, "-2x+3<=9"),
        preset("simplifier", "Simplifier", SolverCalculatorGroup.Algebra, "2(x+3)+4x"),
        preset("expander", "Expander", SolverCalculatorGroup.Algebra, "(x+2)(x-3)"),
        preset("factoriser", "Factoriser", SolverCalculatorGroup.Algebra, "x^2-5x+6=0"),
        preset("polynomial-division", "Polynomial division", SolverCalculatorGroup.Algebra, "divide x^3-1 by x-1"),
        preset("system", "System solver", SolverCalculatorGroup.Algebra, "2x+y=7; x-y=2"),
        preset(
            "partial-fraction",
            "Partial fractions",
            SolverCalculatorGroup.Algebra,
            "partial fractions (2*x+3)/((x-1)*(x+2))",
            supported = false,
        ),
        preset("domain", "Domain calculator", SolverCalculatorGroup.FunctionsGraphs, "domain sqrt(x-2)/(x-3)"),
        preset("inverse-function", "Inverse-function calculator", SolverCalculatorGroup.FunctionsGraphs, "inverse function f(x)=2x+3", supported = false),
        preset("composition", "Composition calculator", SolverCalculatorGroup.FunctionsGraphs, "f(x)=x^2+1; f(3)"),
        preset("intercept", "Intercept calculator", SolverCalculatorGroup.FunctionsGraphs, "intercepts y=x^2-4", supported = false),
        preset("line", "Line calculator", SolverCalculatorGroup.FunctionsGraphs, "gradient(1,2,4,8)"),
        preset("circle", "Circle calculator", SolverCalculatorGroup.FunctionsGraphs, "distance(0,0,3,4)"),
        preset("triangle", "Triangle solver", SolverCalculatorGroup.Trigonometry, "triangle sides 3,4,5", supported = false),
        preset("trig-identity", "Identity simplifier", SolverCalculatorGroup.Trigonometry, "simplify sin(x)^2+cos(x)^2", supported = false),
        preset("trig-equation", "Trigonometric equation solver", SolverCalculatorGroup.Trigonometry, "solve sin(x)=1/2", supported = false),
        preset("degree-radian", "Degree-radian converter", SolverCalculatorGroup.Trigonometry, "180deg to rad"),
        preset("unit-circle", "Unit-circle explorer", SolverCalculatorGroup.Trigonometry, "sin(30deg)"),
        preset("limit", "Limit calculator", SolverCalculatorGroup.Calculus, "limit (x^2-4)/(x-2) as x -> 2"),
        preset("derivative", "Derivative calculator", SolverCalculatorGroup.Calculus, "differentiate x^3+2*x"),
        preset("tangent-normal", "Tangent line calculator", SolverCalculatorGroup.Calculus, "tangent x^2 at x=1"),
        preset("normal-line", "Normal line calculator", SolverCalculatorGroup.Calculus, "normal x^2 at x=1"),
        preset("derivative-analysis", "Derivative applications", SolverCalculatorGroup.Calculus, "derivative analysis x^3-3*x from -3 to 3"),
        preset("integral", "Integral calculator", SolverCalculatorGroup.Calculus, "integrate x^2"),
        preset("area", "Area calculator", SolverCalculatorGroup.Calculus, "integrate x^2 from 0 to 2"),
        preset("differential-equation", "Differential-equation calculator", SolverCalculatorGroup.Calculus, "linear ivp a 1 b 0 x0 0 y0 1 at 1"),
        preset("improper-integral", "Improper integral", SolverCalculatorGroup.Calculus, "improper integrate exp(-x) from 0 to infinity"),
        preset("double-integral", "Double integral", SolverCalculatorGroup.Calculus, "double integrate x+y x 0 to 1 y 0 to 1"),
        preset("triple-integral", "Triple integral", SolverCalculatorGroup.Calculus, "triple integrate x+y+z x 0 to 1 y 0 to 1 z 0 to 1"),
        preset("two-sided-improper", "Two-sided improper integral", SolverCalculatorGroup.Calculus, "improper integrate exp(-x^2) from -infinity to infinity"),
        preset("parameter-integral", "Parameterized integral", SolverCalculatorGroup.Calculus, "parameter integral a*x x 0 to 1 parameter a values 1,2,3"),
        preset("linear-ivp", "Linear initial-value problem", SolverCalculatorGroup.DifferentialEquations, "linear ivp a 2 b 0 x0 0 y0 3 at 1"),
        preset("rk4", "RK4 numerical solution", SolverCalculatorGroup.DifferentialEquations, "rk4 x+y x0 0 y0 1 to 1 step 0.1"),
        preset("ode-series", "ODE power series", SolverCalculatorGroup.DifferentialEquations, "ode series lambda 2 x0 0 y0 1 order 5"),
        preset("logistic-ivp", "Logistic IVP", SolverCalculatorGroup.DifferentialEquations, "logistic rate 1 capacity 100 x0 0 y0 10 at 2"),
        preset("second-order-ivp", "Second-order IVP", SolverCalculatorGroup.DifferentialEquations, "second order ivp a 0 b 1 x0 0 y0 0 v0 1 at 1.5707963267948966"),
        preset("coupled-rk4", "Coupled RK4 system", SolverCalculatorGroup.DifferentialEquations, "system rk4 y;-x initial 1,0 from 0 to 1.5707963267948966 step 0.02"),
        preset("laplace", "Laplace transform", SolverCalculatorGroup.DifferentialEquations, "laplace sin(2*x)"),
        preset("jacobian", "Jacobian matrix", SolverCalculatorGroup.MultivariableVectorCalculus, "jacobian x^2+y;x+y^2 vars x,y at x=1,y=2"),
        preset("hessian", "Hessian matrix", SolverCalculatorGroup.MultivariableVectorCalculus, "hessian x^2+3*x*y+2*y^2 vars x,y at x=1,y=2"),
        preset("gradient", "Gradient", SolverCalculatorGroup.MultivariableVectorCalculus, "gradient x^2*y+sin(y) at x=2,y=0"),
        preset("directional-derivative", "Directional derivative", SolverCalculatorGroup.MultivariableVectorCalculus, "directional derivative x^2+y^2 at x=1,y=2 direction 3,4"),
        preset("divergence", "Divergence", SolverCalculatorGroup.MultivariableVectorCalculus, "divergence x^2;y^2"),
        preset("curl", "Planar curl", SolverCalculatorGroup.MultivariableVectorCalculus, "curl -y;x"),
        preset("tangent-plane", "Tangent plane", SolverCalculatorGroup.MultivariableVectorCalculus, "tangent plane x^2+y^2 at x=1,y=2"),
        preset("lagrange", "Constrained extrema", SolverCalculatorGroup.MultivariableVectorCalculus, "lagrange x+y constraint x^2+y^2 level 1 seeds 1,1|-1,-1|1,-1"),
        preset("line-integral", "Scalar line integral", SolverCalculatorGroup.MultivariableVectorCalculus, "line integral 1 curve cos(t);sin(t) from 0 to 6.283185307179586"),
        preset("work-integral", "Work line integral", SolverCalculatorGroup.MultivariableVectorCalculus, "work integral -y;x curve cos(t);sin(t) from 0 to 6.283185307179586"),
        preset("surface-flux", "Surface flux", SolverCalculatorGroup.MultivariableVectorCalculus, "surface flux 0;0;1 surface u;v;0 u 0 to 2 v 0 to 3"),
        preset("green-theorem", "Green theorem verifier", SolverCalculatorGroup.MultivariableVectorCalculus, "green -y;x x -1 to 1 y -1 to 1"),
        preset("gauss-theorem", "Gauss theorem verifier", SolverCalculatorGroup.MultivariableVectorCalculus, "gauss x;y;z x 0 to 1 y 0 to 1 z 0 to 1"),
        preset("stokes-theorem", "Stokes theorem verifier", SolverCalculatorGroup.MultivariableVectorCalculus, "stokes -y;x;0 x -1 to 1 y -1 to 1"),
        preset("matrix", "Matrix calculator", SolverCalculatorGroup.LinearAlgebra, "matrixadd([[1,2],[3,4]],[[2,3],[4,5]])"),
        preset("determinant", "Determinant calculator", SolverCalculatorGroup.LinearAlgebra, "det([[1,2],[3,4]])"),
        preset("inverse", "Inverse calculator", SolverCalculatorGroup.LinearAlgebra, "inverse([[1,2],[3,4]])"),
        preset("row-reduction", "Row-reduction calculator", SolverCalculatorGroup.LinearAlgebra, "rref([[1,2],[3,4]])"),
        preset("linear-system", "Linear-system calculator", SolverCalculatorGroup.LinearAlgebra, "2x+y=7; x-y=2"),
        preset("eigenvalue", "Eigenvalue calculator", SolverCalculatorGroup.LinearAlgebra, "eigenvalues([[2,0],[0,3]])", supported = false),
        preset("arithmetic-sequence", "Arithmetic sequence", SolverCalculatorGroup.SequencesSeries, "arithmeticterm(3,2,10)"),
        preset("geometric-sequence", "Geometric sequence", SolverCalculatorGroup.SequencesSeries, "geometricsum(2,1/2,5)"),
        preset("sigma", "Sigma evaluator", SolverCalculatorGroup.SequencesSeries, "sum k from 1 to 10", supported = false),
        preset("convergence", "Convergence checker", SolverCalculatorGroup.SequencesSeries, "infinitegeometricsum(2,1/2)"),
        preset("complex", "Complex arithmetic", SolverCalculatorGroup.ComplexNumbers, "complex multiply 1+2i ; 3-4i"),
        preset("polar", "Polar conversion", SolverCalculatorGroup.ComplexNumbers, "complex 3+4i"),
        preset("complex-roots", "Complex roots", SolverCalculatorGroup.ComplexNumbers, "complex roots 1+i order 3"),
        preset("argand", "Argand representation", SolverCalculatorGroup.ComplexNumbers, "complex -2+5i"),
    )

    fun search(query: String): List<SolverCalculatorPreset> = presets.filter {
        query.isBlank() || it.title.contains(query, true) || it.group.label.contains(query, true) || it.description.contains(query, true)
    }

    private fun preset(
        id: String,
        title: String,
        group: SolverCalculatorGroup,
        starter: String,
        supported: Boolean = true,
    ) = SolverCalculatorPreset(
        id,
        title,
        group,
        starter,
        supported,
        if (supported) {
            "Routes through the shared offline Solver pipeline."
        } else {
            "Listed for future support and hidden from the active calculator picker."
        },
    )
}
