package com.indianservers.aiexplorer.mathworkspace.discrete

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.Text
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.TextButton
import androidx.compose.runtime.*
import kotlinx.coroutines.delay
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.input.pointer.positionChange
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.indianservers.aiexplorer.mathworkspace.MathWorkspaceShell
import com.indianservers.aiexplorer.mathworkspace.components.MathWorkspacePalette as P
import com.indianservers.aiexplorer.mathworkspace.components.WorkspaceAction
import com.indianservers.aiexplorer.mathworkspace.components.WorkspaceSegmentedControl

@Composable
fun DiscreteMathWorkspace(vm:DiscreteMathViewModel,onBack:()->Unit){
    val mode=vm.mode.value
    MathWorkspaceShell(title="Discrete Mathematics Lab",subtitle="Graphs · sets · relations · counting · logic",onBack=onBack,sheetTitle=mode.title,sheetStop=vm.sheet.value,onSheetStopChange={vm.sheet.value=it},
        canvas={if(mode==DiscreteMode.Graphs)GraphCanvas(vm)else ModeCanvas(vm)},
        tools={Column(Modifier.align(Alignment.TopCenter).fillMaxWidth().background(P.snow.copy(alpha=.96f)).padding(horizontal=6.dp, vertical=4.dp),verticalArrangement=Arrangement.spacedBy(4.dp),horizontalAlignment=Alignment.CenterHorizontally){WorkspaceSegmentedControl(DiscreteMode.entries.map{it.title},mode.ordinal){vm.mode.value=DiscreteMode.entries[it];vm.sheet.value=com.indianservers.aiexplorer.mathworkspace.components.WorkspaceSheetStop.Peek};if(mode==DiscreteMode.Graphs)Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(3.dp)){listOf("Select","Add vertex","Add edge","Delete").forEach{WorkspaceAction(it,it,{vm.tool.value=it},vm.tool.value==it)};WorkspaceAction("Directed","Toggle directed",{vm.toggleDirected()},vm.directed.value);WorkspaceAction("Weighted","Toggle weights",{vm.toggleWeighted()},vm.weighted.value)}}},
        sheet={Column(Modifier.fillMaxWidth().verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(6.dp)){when(mode){DiscreteMode.Graphs->GraphInspector(vm);DiscreteMode.Sets->SetsInspector(vm);DiscreteMode.Relations->RelationsInspector(vm);DiscreteMode.Combinatorics->CombinatoricsInspector(vm);DiscreteMode.Logic->LogicInspector(vm)}}})
}

@Composable private fun GraphCanvas(vm:DiscreteMathViewModel){
    val g=vm.graph.value;val current=vm.run.value?.steps?.getOrNull(vm.step.intValue);var edgeStart by remember{mutableStateOf<Int?>(null)};var dragNode by remember{mutableIntStateOf(-1)}
    Canvas(Modifier.fillMaxSize().padding(top=103.dp,bottom=74.dp).background(Color.White).semantics{contentDescription="Interactive graph canvas"}.pointerInput(g,vm.tool.value,edgeStart){
        detectTapGestures { p ->
            val w=size.width.toFloat().coerceAtLeast(1f);val h=size.height.toFloat().coerceAtLeast(1f)
            val hit=g.vertices.minByOrNull{v->kotlin.math.hypot(v.x*w-p.x.toDouble(),v.y*h-p.y.toDouble())}?.takeIf{kotlin.math.hypot(it.x*w-p.x.toDouble(),it.y*h-p.y.toDouble())<38}?.id
            when(vm.tool.value){
                "Add vertex"->{if(hit==null){val id=(g.vertices.maxOfOrNull{it.id}?:-1)+1;vm.graph.value=g.copy(vertices=g.vertices+GraphVertex(id,(p.x/w).toDouble(),(p.y/h).toDouble(),"${g.vertices.size+1}"))}}
                "Delete"->{if(hit!=null)vm.graph.value=g.copy(vertices=g.vertices.filterNot{it.id==hit},edges=g.edges.filterNot{it.from==hit||it.to==hit}) else {val map=g.vertices.associateBy{it.id};val edge=g.edges.minByOrNull{e->val a=map[e.from]?:return@minByOrNull Double.POSITIVE_INFINITY;val b=map[e.to]?:return@minByOrNull Double.POSITIVE_INFINITY;segmentDistance(p.x,p.y,a.x*w,a.y*h,b.x*w,b.y*h)};if(edge!=null&&segmentDistance(p.x,p.y,map[edge.from]!!.x*w,map[edge.from]!!.y*h,map[edge.to]!!.x*w,map[edge.to]!!.y*h)<18)vm.graph.value=g.copy(edges=g.edges-edge)}}
                "Add edge"->{if(hit!=null){if(edgeStart==null)edgeStart=hit else if(edgeStart!=hit){vm.graph.value=g.copy(edges=g.edges+GraphEdge(edgeStart!!,hit));edgeStart=null}}}
                else->{if(hit!=null)vm.source.intValue=hit}
            }
        }
    }.pointerInput(vm.tool.value){
        detectDragGestures(onDragStart={p->val vertices=vm.graph.value.vertices;dragNode=vertices.minByOrNull{kotlin.math.hypot(it.x*size.width-p.x.toDouble(),it.y*size.height-p.y.toDouble())}?.takeIf{kotlin.math.hypot(it.x*size.width-p.x.toDouble(),it.y*size.height-p.y.toDouble())<38}?.id?:-1},onDrag={change,_->if(dragNode>=0){val graph=vm.graph.value;val v=graph.vertices.firstOrNull{it.id==dragNode};if(v!=null){val delta=change.positionChange();val nx=(v.x+delta.x/size.width).coerceIn(.04, .96);val ny=(v.y+delta.y/size.height).coerceIn(.04,.96);vm.graph.value=graph.copy(vertices=graph.vertices.map{if(it.id==dragNode)it.copy(x=nx,y=ny)else it})}}},onDragEnd={dragNode=-1})
    }) {
        val map=g.vertices.associateBy{it.id}
        g.edges.forEach { e ->
            val a=map[e.from]?:return@forEach;val b=map[e.to]?:return@forEach
            val p1=Offset((a.x*size.width).toFloat(),(a.y*size.height).toFloat());val p2=Offset((b.x*size.width).toFloat(),(b.y*size.height).toFloat())
            val chosen=current?.edges?.contains(e.from to e.to)==true||current?.edges?.contains(e.to to e.from)==true
            drawLine(if(chosen)P.green else P.border,p1,p2,4f)
            if(vm.directed.value){val angle=kotlin.math.atan2(p2.y-p1.y,p2.x-p1.x);val tip=Offset(p2.x-kotlin.math.cos(angle)*23f,p2.y-kotlin.math.sin(angle)*23f);val arrow=Path().apply{moveTo(tip.x,tip.y);lineTo(tip.x-11*kotlin.math.cos(angle-.55f),tip.y-11*kotlin.math.sin(angle-.55f));lineTo(tip.x-11*kotlin.math.cos(angle+.55f),tip.y-11*kotlin.math.sin(angle+.55f));close()};drawPath(arrow,P.blue)}
            if(vm.weighted.value)drawContext.canvas.nativeCanvas.drawText(e.weight.toString(),(p1.x+p2.x)/2,(p1.y+p2.y)/2,android.graphics.Paint().apply{color=android.graphics.Color.DKGRAY;textSize=30f})
        }
        g.vertices.forEach{v->val p=Offset((v.x*size.width).toFloat(),(v.y*size.height).toFloat());val active=current?.current==v.id;val visited=current?.visited?.contains(v.id)==true;drawCircle(if(active)P.amber else if(visited)P.green else P.blue,20f,p);drawContext.canvas.nativeCanvas.drawText(v.label,(p.x-6),(p.y+5),android.graphics.Paint().apply{color=android.graphics.Color.WHITE;textSize=15f;isFakeBoldText=true})}
    }
}

@Composable private fun ModeCanvas(vm:DiscreteMathViewModel){Column(Modifier.fillMaxSize().padding(top=92.dp,bottom=70.dp).padding(16.dp).clip(RoundedCornerShape(18.dp)).background(Color.White).padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){when(vm.mode.value){DiscreteMode.Sets->SetResults(vm);DiscreteMode.Relations->RelationGraphCanvas(vm);DiscreteMode.Combinatorics->PascalView(vm);DiscreteMode.Logic->TruthView(vm);else->Unit}}}

@Composable private fun GraphInspector(vm:DiscreteMathViewModel){val g=vm.graph.value;val run=vm.run.value
    var matrixOpen by remember{mutableStateOf(false)}
    LaunchedEffect(vm.playing.value,run){while(vm.playing.value){delay(550);if(vm.step.intValue<(vm.run.value?.steps?.lastIndex?:0))vm.step.intValue++ else vm.playing.value=false}}
    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("Path","Cycle","Complete","Star","Tree","Weighted").forEach{WorkspaceAction(it,"Load $it graph",{vm.setPreset(it)})};WorkspaceAction("+","Add vertex",{val i=(g.vertices.maxOfOrNull{it.id}?:-1)+1;vm.graph.value=g.copy(vertices=g.vertices+GraphVertex(i,.5,.5,"${i+1}"))})}
    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("BFS","DFS","Dijkstra","MST").forEach{WorkspaceAction(it,"Run $it",{vm.startAlgorithm(it)})};WorkspaceAction("‹","Previous algorithm step",{vm.playing.value=false;vm.step.intValue=(vm.step.intValue-1).coerceAtLeast(0)},enabled=vm.step.intValue>0);WorkspaceAction(if(vm.playing.value)"Pause" else "Play","Play or pause algorithm steps",{vm.playing.value=!vm.playing.value},enabled=run!=null);WorkspaceAction("Next ›","Next algorithm step",{vm.playing.value=false;vm.step.intValue=(vm.step.intValue+1).coerceAtMost((run?.steps?.lastIndex?:0))},enabled=run!=null&&vm.step.intValue<(run.steps.lastIndex));WorkspaceAction("Reset","Reset algorithm",{vm.playing.value=false;vm.run.value=null;vm.step.intValue=0})}
    Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(4.dp)){Text("Start ${g.vertices.firstOrNull{it.id==vm.source.intValue}?.label?:"?"}",color=P.muted,fontSize=10.sp);WorkspaceAction("−","Previous start vertex",{val ids=g.vertices.map{it.id};if(ids.isNotEmpty())vm.source.intValue=ids[(ids.indexOf(vm.source.intValue)-1).mod(ids.size)]});WorkspaceAction("+","Next start vertex",{val ids=g.vertices.map{it.id};if(ids.isNotEmpty())vm.source.intValue=ids[(ids.indexOf(vm.source.intValue)+1).mod(ids.size)]});Text("Target ${g.vertices.firstOrNull{it.id==vm.target.intValue}?.label?:"?"}",color=P.muted,fontSize=10.sp);WorkspaceAction("+","Next target vertex",{val ids=g.vertices.map{it.id};if(ids.isNotEmpty())vm.target.intValue=ids[(ids.indexOf(vm.target.intValue)+1).mod(ids.size)]})}
    val degrees=GraphAlgorithms.degrees(g);Text("${g.vertices.size} vertices · ${g.edges.size} edges · ${GraphAlgorithms.components(g).size} components · ${if(GraphAlgorithms.hasCycle(g))"cycle" else "acyclic"}",color=P.ink,fontSize=11.sp)
    Text(if(vm.directed.value)g.vertices.joinToString("   "){"${it.label}: in ${degrees[it.id]?.second}, out ${degrees[it.id]?.third}"}else g.vertices.joinToString("   "){"${it.label}: deg ${degrees[it.id]?.first}"},color=P.muted,fontSize=10.sp)
    Row(verticalAlignment=Alignment.CenterVertically){Text("Adjacency: "+GraphAlgorithms.adjacency(g).entries.joinToString("  "){(id,es)->"${g.vertices.firstOrNull{it.id==id}?.label}: ${es.joinToString { g.vertices.firstOrNull{v->v.id==it.first}?.label.orEmpty() }}"},Modifier.weight(1f),color=P.ink,fontSize=10.sp);WorkspaceAction("Matrix","Show adjacency matrix",{matrixOpen=true})}
    if(matrixOpen)AlertDialog(onDismissRequest={matrixOpen=false},title={Text("Adjacency matrix")},text={Column(Modifier.horizontalScroll(rememberScrollState())){val ids=g.vertices.map{it.id};Text("   "+ids.joinToString("   "){id->g.vertices.first{it.id==id}.label},color=P.blue,fontSize=11.sp);ids.forEach{a->Text(g.vertices.first{it.id==a}.label+"  "+ids.joinToString("   "){b->if(g.edges.any{(it.from==a&&it.to==b)||(!g.directed&&it.from==b&&it.to==a)})"1" else "0"},color=P.ink,fontSize=11.sp)}}},confirmButton={TextButton(onClick={matrixOpen=false}){Text("Close")}})
    run?.let{Text("${it.result}  ·  step ${vm.step.intValue+1}/${it.steps.size}\n${it.steps.getOrNull(vm.step.intValue)?.note.orEmpty()}",color=P.blue,fontWeight=FontWeight.SemiBold,fontSize=11.sp)};if(vm.error.value.isNotBlank())Text(vm.error.value,color=P.red,fontSize=11.sp)
}

@Composable private fun SetsInspector(vm:DiscreteMathViewModel){TextInput("Set A",vm.setA.value){vm.setA.value=it};TextInput("Set B",vm.setB.value){vm.setB.value=it};TextInput("Universal set U",vm.universal.value){vm.universal.value=it};Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("Union","Intersection","A − B","B − A","Symmetric Δ","A × B","Complement A").forEach{WorkspaceAction(it,"Compute $it",{vm.setOp.value=it},vm.setOp.value==it)}};Text("Use comma-separated set members; repeats are removed.",color=P.muted,fontSize=10.sp)}
@Composable private fun SetResults(vm:DiscreteMathViewModel){val a=SetEngine.parse(vm.setA.value);val b=SetEngine.parse(vm.setB.value);val out=when(vm.setOp.value){"Intersection"->SetEngine.intersection(a,b);"A − B"->SetEngine.difference(a,b);"B − A"->SetEngine.difference(b,a);"Symmetric Δ"->SetEngine.symmetricDifference(a,b);"Complement A"->SetEngine.difference(SetEngine.parse(vm.universal.value),a);else->SetEngine.union(a,b)};Column(verticalArrangement=Arrangement.spacedBy(7.dp)){Text("A ${SetEngine.format(a)}",color=P.blue);Text("B ${SetEngine.format(b)}",color=P.violet);Text("${vm.setOp.value}: ${SetEngine.format(out)}",color=P.ink,fontSize=18.sp,fontWeight=FontWeight.Bold);Text("${a.size} elements · ${b.size} elements",color=P.muted,fontSize=11.sp);Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(72.dp).clip(CircleShape).background(P.blue.copy(alpha=.38f)));Box(Modifier.offset(x=(-20).dp).size(72.dp).clip(CircleShape).background(P.violet.copy(alpha=.45f)))};if(vm.setOp.value=="A × B")Text(SetEngine.product(a,b).joinToString("  "){"(${it.first},${it.second})"},color=P.ink,fontSize=12.sp)}}

@Composable private fun RelationsInspector(vm:DiscreteMathViewModel){TextInput("Set elements",vm.relationElements.value){vm.relationElements.value=it};TextInput("Pairs: (a,b), (b,c)",vm.relationPairs.value){vm.relationPairs.value=it};val e=SetEngine.parse(vm.relationElements.value);val r=RelationEngine.parsePairs(vm.relationPairs.value);val p=RelationEngine.properties(e,r);Text("${r.size} ordered pairs · ${if(p.equivalence)"equivalence relation" else if(p.partialOrder)"partial order" else "relation"}",color=P.blue,fontWeight=FontWeight.Bold,fontSize=12.sp);Text("Reflexive ${yes(p.reflexive)}   Symmetric ${yes(p.symmetric)}   Antisymmetric ${yes(p.antisymmetric)}   Transitive ${yes(p.transitive)}",color=P.ink,fontSize=11.sp);if(p.equivalence)Text("Classes: ${RelationEngine.equivalenceClasses(e,r)}",color=P.muted,fontSize=10.sp);if(p.partialOrder)Text("Hasse covers: ${RelationEngine.hasseEdges(e,r)}",color=P.violet,fontSize=10.sp)}
@Composable private fun CombinatoricsInspector(vm:DiscreteMathViewModel){Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){TextInput("n",vm.n.value){vm.n.value=it};TextInput("r",vm.r.value){vm.r.value=it}};Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(4.dp)){listOf("Factorial","Permute","Choose").forEach{WorkspaceAction(it,"Calculate $it",{vm.comboMode.value=it},vm.comboMode.value==it)}};TextInput("Pascal row",vm.pascalRow.value){vm.pascalRow.value=it};val n=vm.n.value.toIntOrNull();val r=vm.r.value.toIntOrNull();val result=runCatching{when(vm.comboMode.value){"Factorial"->CombinatoricsEngine.factorial(n!!);"Permute"->CombinatoricsEngine.permute(n!!,r!!);else->CombinatoricsEngine.choose(n!!,r!!)}.toString()}.getOrElse{"Enter integers with 0 ≤ r ≤ n"};Text("Result  $result",color=P.blue,fontWeight=FontWeight.Bold);if(n!=null&&r!=null&&n in 0..8&&r in 0..n)Text("Sample combinations: "+CombinatoricsEngine.combinations(('A'..'H').take(n).map{it.toString()},r,12).joinToString("  "){it.joinToString("")},color=P.ink,fontSize=10.sp);Text("Pigeonhole: placing ${n?:0} objects in ${r?:0} boxes guarantees at least ${if((n?:0)>0&&(r?:0)>0)(n!!-1)/(r!!)+1 else 0} in one box.",color=P.muted,fontSize=10.sp);Text("Inclusion–exclusion for two finite sets",color=P.ink,fontWeight=FontWeight.SemiBold,fontSize=11.sp);Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){TextInput("|A|",vm.inclusionA.value){vm.inclusionA.value=it};TextInput("|B|",vm.inclusionB.value){vm.inclusionB.value=it};TextInput("|A∩B|",vm.intersection.value){vm.intersection.value=it}};val ie=runCatching{vm.inclusionA.value.toInt()+vm.inclusionB.value.toInt()-vm.intersection.value.toInt()}.getOrNull();Text("|A∪B| = |A| + |B| − |A∩B| = ${ie?:"—"}",color=P.violet,fontSize=11.sp)}
@Composable private fun PascalView(vm:DiscreteMathViewModel){val n=vm.pascalRow.value.toIntOrNull()?.coerceIn(0,30)?:0;Column(verticalArrangement=Arrangement.spacedBy(2.dp)){Text("Pascal triangle through row ${minOf(n,12)}",color=P.ink,fontWeight=FontWeight.Bold);(0..minOf(n,12)).forEach{row->Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.Center){Text(CombinatoricsEngine.pascal(row).joinToString("   "),color=P.blue,fontSize=10.sp)}};Text("Choose C(n,r) with the input; exact BigInteger values are used.",color=P.muted,fontSize=10.sp)}}
@Composable private fun RelationGraphCanvas(vm:DiscreteMathViewModel){val e=SetEngine.parse(vm.relationElements.value).toList();val r=RelationEngine.parsePairs(vm.relationPairs.value);val properties=RelationEngine.properties(e.toSet(),r);val pairs=if(properties.partialOrder)RelationEngine.hasseEdges(e.toSet(),r)else r;Canvas(Modifier.fillMaxWidth().height(200.dp).background(P.snow,RoundedCornerShape(12.dp))){val left=e.mapIndexed{i,s->s to Offset(size.width*.24f,30f+i*size.height/e.size.coerceAtLeast(1))}.toMap();val right=e.mapIndexed{i,s->s to Offset(size.width*.76f,30f+i*size.height/e.size.coerceAtLeast(1))}.toMap();pairs.forEach{(a,b)->val p=left[a]?:return@forEach;val q=right[b]?:return@forEach;drawLine(P.blue,p,q,2f)};left.forEach{(s,p)->drawCircle(P.blue,12f,p);drawContext.canvas.nativeCanvas.drawText(s,p.x-4,p.y+4,android.graphics.Paint().apply{color=android.graphics.Color.WHITE;textSize=10f})};right.forEach{(s,p)->drawCircle(P.violet,12f,p);drawContext.canvas.nativeCanvas.drawText(s,p.x-4,p.y+4,android.graphics.Paint().apply{color=android.graphics.Color.WHITE;textSize=10f})}}}
@Composable private fun LogicInspector(vm:DiscreteMathViewModel){TextInput("Expression",vm.logic.value){vm.logic.value=it};Text("Operators: NOT / ! · AND / ∧ · OR / ∨ · XOR · -> · <->",color=P.muted,fontSize=10.sp);val result=runCatching{LogicEngine.table(vm.logic.value)};result.onSuccess{table->Text("${table.classification} · ${table.rows.size} rows",color=P.blue,fontWeight=FontWeight.Bold)}.onFailure{Text(it.message?:"Invalid expression",color=P.red,fontSize=10.sp)};TextInput("Compare expression (optional)",vm.secondLogic.value){vm.secondLogic.value=it};if(vm.secondLogic.value.isNotBlank()){val equivalent=runCatching{val a=LogicEngine.table(vm.logic.value);val b=LogicEngine.table(vm.secondLogic.value);a.variables==b.variables&&a.rows.map{it.result}==b.rows.map{it.result}}.getOrDefault(false);Text(if(equivalent)"Logically equivalent" else "Not equivalent",color=P.violet,fontSize=11.sp)}}
@Composable private fun TruthView(vm:DiscreteMathViewModel){runCatching{LogicEngine.table(vm.logic.value)}.onSuccess{table->Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(12.dp)){table.variables.forEach{Text(it,color=P.muted,fontWeight=FontWeight.Bold)};Text(vm.logic.value,color=P.blue,fontWeight=FontWeight.Bold)};table.rows.take(32).forEach{row->Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(12.dp)){table.variables.forEach{Text(if(row.values[it]==true)"T" else "F",color=P.ink)};Text(if(row.result)"T" else "F",color=if(row.result)P.green else P.red,fontWeight=FontWeight.Bold)}};Text(table.classification,color=P.violet,fontWeight=FontWeight.Bold)}.onFailure{Text(it.message?:"Enter a valid expression",color=P.red)}}
@Composable private fun TextInput(label:String,value:String,onChange:(String)->Unit){Column(Modifier.widthIn(min=88.dp).clip(RoundedCornerShape(9.dp)).background(P.snow).padding(horizontal=8.dp,vertical=5.dp)){Text(label,color=P.muted,fontSize=9.sp);BasicTextField(value,onChange,Modifier.fillMaxWidth().heightIn(min=25.dp).semantics{contentDescription=label},singleLine=true,textStyle=androidx.compose.ui.text.TextStyle(color=P.ink,fontSize=12.sp))}}
private fun yes(b:Boolean)=if(b)"✓" else "×"
private fun segmentDistance(px:Float,py:Float,ax:Double,ay:Double,bx:Double,by:Double):Double{val dx=bx-ax;val dy=by-ay;val length=dx*dx+dy*dy;val t=if(length==0.0)0.0 else (((px-ax)*dx+(py-ay)*dy)/length).coerceIn(0.0,1.0);return kotlin.math.hypot(px-(ax+t*dx),py-(ay+t*dy))}
