package com.indianservers.aiexplorer.mathworkspace.discrete

object GraphAlgorithms {
    fun adjacency(g: GraphModel): Map<Int,List<Pair<Int,Double>>> = g.vertices.associate { v -> v.id to buildList {
        g.edges.filter { it.from == v.id || (!g.directed && it.to == v.id) }.forEach { e -> add((if (e.from == v.id) e.to else e.from) to e.weight) }
        sortBy { it.first }
    } }
    fun degrees(g: GraphModel): Map<Int,Triple<Int,Int,Int>> = g.vertices.associate { v ->
        val out=g.edges.count { it.from==v.id || (!g.directed && it.to==v.id) }; val input=if(g.directed)g.edges.count{it.to==v.id}else out
        v.id to Triple(if(g.directed)out+input else out,input,out)
    }
    fun components(g: GraphModel): List<Set<Int>> { val adj=adjacency(g); val unseen=g.vertices.map{it.id}.toMutableSet(); val out=mutableListOf<Set<Int>>(); while(unseen.isNotEmpty()){val q=ArrayDeque<Int>();val c=linkedSetOf<Int>();q+=unseen.first();while(q.isNotEmpty()){val n=q.removeFirst();if(c.add(n)){unseen.remove(n);adj[n].orEmpty().forEach{q+=it.first}}};out+=c};return out }
    fun hasCycle(g: GraphModel): Boolean {
        if(g.directed){val adj=adjacency(g);val color=mutableMapOf<Int,Int>();fun visit(n:Int):Boolean {if(color[n]==1)return true;if(color[n]==2)return false;color[n]=1;for((to,_)in adj[n].orEmpty())if(visit(to))return true;color[n]=2;return false};return g.vertices.any{visit(it.id)} }
        val parent=mutableMapOf<Int,Int>();fun root(x:Int):Int {val p=parent[x]?:x;if(p==x)return x;val r=root(p);parent[x]=r;return r};for(e in g.edges){val a=root(e.from);val b=root(e.to);if(a==b)return true;parent[a]=b};return false
    }
    fun bfs(g: GraphModel, start: Int): AlgorithmRun = traverse(g,start,false)
    fun dfs(g: GraphModel, start: Int): AlgorithmRun = traverse(g,start,true)
    private fun traverse(g:GraphModel,start:Int,depth:Boolean):AlgorithmRun { val adj=adjacency(g);val visited=linkedSetOf<Int>();val q=ArrayDeque<Int>();q+=start;val steps=mutableListOf(AlgorithmStep(null,emptySet(),emptySet(),q.toList(),note="Start"));val used=linkedSetOf<Pair<Int,Int>>();while(q.isNotEmpty()){val n=if(depth)q.removeLast()else q.removeFirst();if(!visited.add(n))continue;val neighbors=adj[n].orEmpty().let{if(depth)it.asReversed()else it};for((to,_)in neighbors)if(to !in visited)q+=to;adj[n].orEmpty().filter{it.first in q}.forEach{used+=n to it.first};steps+=AlgorithmStep(n,visited.toSet(),used.toSet(),q.toList(),note="Visit ${label(g,n)}")};return AlgorithmRun(steps,visited.joinToString(" → "){label(g,it)}) }
    fun dijkstra(g:GraphModel,start:Int,end:Int):AlgorithmRun { require(g.edges.all{it.weight>=0}){"Dijkstra requires non-negative weights"};val adj=adjacency(g);val dist=g.vertices.associate{it.id to Double.POSITIVE_INFINITY}.toMutableMap();dist[start]=0.0;val previous=mutableMapOf<Int,Int>();val done=linkedSetOf<Int>();val steps=mutableListOf<AlgorithmStep>();while(done.size<g.vertices.size){val n=dist.filterKeys{it !in done}.minByOrNull{it.value}?.key?:break;if(!dist[n]!!.isFinite())break;done+=n;for((to,w)in adj[n].orEmpty())if(to !in done&&dist[n]!!+w<dist[to]!!){dist[to]=dist[n]!!+w;previous[to]=n};steps+=AlgorithmStep(n,done.toSet(),previous.map{it.value to it.key}.toSet(),dist.filter{it.value.isFinite()}.keys.toList(),dist.toMap(),"Distance to ${label(g,n)}: ${dist[n]}");if(n==end)break};val path=mutableListOf<Int>();var p:Int?=end;if(dist[end]?.isFinite()==true){while(p!=null){path.add(0,p);p=previous[p]};steps+=AlgorithmStep(end,done,path.zipWithNext().map{it.first to it.second}.toSet(),emptyList(),dist.toMap(),"Shortest path")};return AlgorithmRun(steps,if(path.isEmpty())"No path" else "${path.joinToString(" → "){label(g,it)}} · ${dist[end]}") }
    fun mst(g:GraphModel):AlgorithmRun { require(!g.directed){"MST requires an undirected graph"};val parent=mutableMapOf<Int,Int>();fun root(x:Int):Int{val p=parent[x]?:x;if(p==x)return x;val r=root(p);parent[x]=r;return r};val picked=mutableListOf<GraphEdge>();val steps=mutableListOf<AlgorithmStep>();for(e in g.edges.sortedBy{it.weight}){val a=root(e.from);val b=root(e.to);if(a!=b){parent[a]=b;picked+=e;steps+=AlgorithmStep(e.to,picked.flatMap{listOf(it.from,it.to)}.toSet(),picked.map{it.from to it.to}.toSet(),emptyList(),note="Add ${label(g,e.from)}–${label(g,e.to)} (${e.weight})")}};return AlgorithmRun(steps,"MST weight ${picked.sumOf{it.weight}}") }
    fun preset(kind:String):GraphModel {val count=when(kind){"Path"->5;"Cycle"->5;"Complete"->5;"Star"->6;"Tree"->7;else->5};val v=(0 until count).map{i->val a=2*Math.PI*i/count;GraphVertex(i,0.5+0.37*kotlin.math.cos(a),0.5+0.37*kotlin.math.sin(a),(i+1).toString())};val pairs=when(kind){"Path"->(0 until count-1).map{it to it+1};"Cycle"->(0 until count).map{it to (it+1)%count};"Complete"->(0 until count).flatMap{i->(i+1 until count).map{j->i to j}};"Star"->(1 until count).map{0 to it};"Tree"->(1 until count).map{(it-1)/2 to it};else->listOf(0 to 1,0 to 2,1 to 2,1 to 3,2 to 3,3 to 4)};return GraphModel(v,pairs.map{GraphEdge(it.first,it.second,if(kind=="Weighted")listOf(2.0,5.0,1.0,4.0,1.0,3.0)[pairs.indexOf(it)%6] else 1.0)},weighted=kind=="Weighted") }
    private fun label(g:GraphModel,id:Int)=g.vertices.firstOrNull{it.id==id}?.label?.ifBlank{(id+1).toString()}?:"?"
}
