package com.indianservers.aiexplorer.physics.ncert

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.*

object PhysicsNcertBatch02Content {
    private const val cid="cbse-2026-c10-physics-c3"; private const val tid="$cid-core"
    private fun q(id:String,type:CurriculumQuestionType,c:CompetencyType,p:String,a:String,e:String,s:String)=CurriculumQuestion("physics-electric-$id",SchoolSubject.PHYSICS,SchoolClassLevel.CLASS_10,cid,listOf(tid),c,QuestionDifficulty.STANDARD,type,p,answer=AnswerDefinition(a),explanation=e,commonErrorTags=listOf("electricity reasoning"),remediationSectionId=s)
    val electricity=SubjectOwnedCurriculumChapter(
        "physics-ncert-c10-electricity-production",cid,SchoolSubject.PHYSICS,SchoolClassLevel.CLASS_10,"Electricity","Effects of Current",130,"physics/ncert/10/electricity",listOf(tid),
        listOf("Relate current to charge flow and potential difference to energy transfer per charge.","Use Ohm's law with its conditions and SI units.","Analyse series and parallel resistor combinations.","Interpret V–I data and calculate electrical power and energy."),
        listOf("Electric charge","Energy and work","Ratio and graph slope","Simple circuit symbols"),
        linkedMapOf(
            "current-voltage" to "Current is charge passing a cross-section per time. Potential difference measures energy transferred per unit charge. An ammeter is placed in series and a voltmeter across the component so each measures the intended quantity.",
            "ohms-law" to "For an ohmic conductor at constant physical conditions, potential difference is proportional to current: V=IR. Resistance is the slope of a V-against-I graph; heating can change resistance and invalidate a single straight-line model.",
            "networks" to "Series components carry the same current and their potential differences add. Parallel branches share the same potential difference and their currents add. Equivalent resistance must reflect these constraints.",
            "power-energy" to "Electrical power is the rate of energy transfer, P=VI. Electrical energy is Pt. Commercial energy units and SI joules must not be mixed without conversion.",
            "safety" to "Fuses and protective devices reduce risk but do not make unsafe handling acceptable. Never experiment with mains electricity; school activities use teacher-approved low-voltage supplies."
        ),
        linkedMapOf("electric current" to "Rate of charge flow.","potential difference" to "Energy transferred per unit charge.","resistance" to "Opposition quantified by V/I under stated conditions.","power" to "Energy transferred per unit time."),
        listOf(
            WorkedExample("A 6 Ω resistor is connected across 12 V. Find current and power.",listOf("I=V/R=12/6=2 A.","P=VI=12×2=24 W."),"2 A; 24 W.","V/Ω=A and V×A=W."),
            WorkedExample("Find equivalent resistance of 4 Ω and 12 Ω in parallel.",listOf("1/R=1/4+1/12=4/12=1/3.","R=3 Ω."),"3 Ω.","Parallel equivalent resistance is below the smallest branch resistance.")),
        listOf(
            CurriculumDiagramSpecification("physics-c10-electric-circuit",SchoolSubject.PHYSICS,SchoolClassLevel.CLASS_10,tid,"Ohm's-law measurement circuit",DiagramType.CIRCUIT,listOf(DiagramLabelRequirement("cell","low-voltage source","energy supply"),DiagramLabelRequirement("ammeter","A in series","current"),DiagramLabelRequirement("resistor","test resistor","component"),DiagramLabelRequirement("voltmeter","V in parallel","potential difference"),DiagramLabelRequirement("switch","switch","safe control")),"Connect measurement roles with correct circuit placement.",listOf("Ammeter is series and voltmeter parallel.","Only low-voltage school supply is shown.","Connections are unambiguous at junctions."),DiagramInteractionMode.LABEL_HIDE_AND_QUIZ,"A closed low-voltage circuit places a switch, ammeter and resistor in series, with a voltmeter connected across the resistor.",ScientificReviewStatus.VERIFIED),
            CurriculumDiagramSpecification("physics-c10-vi-graph",SchoolSubject.PHYSICS,SchoolClassLevel.CLASS_10,tid,"Potential difference against current",DiagramType.GRAPH,listOf(DiagramLabelRequirement("i","current / A","horizontal axis"),DiagramLabelRequirement("v","potential difference / V","vertical axis"),DiagramLabelRequirement("slope","ΔV/ΔI","resistance")),"Infer resistance from data rather than formula recall alone.",listOf("Axes show units.","Best-fit line is not forced through noisy points unless justified.","Slope triangle spans well-separated points."),DiagramInteractionMode.LABEL_HIDE_AND_QUIZ,"Measured current is plotted horizontally and potential difference vertically; a straight best-fit line and slope triangle show resistance.",ScientificReviewStatus.VERIFIED)),
        listOf(CurriculumFormulaLink("physics-ohm","Ohm's law",mapOf("V" to "potential difference","I" to "current","R" to "resistance"),mapOf("V" to "V","I" to "A","R" to "Ω"),listOf("Temperature and other physical conditions are constant.","The component is ohmic over the measured range."),listOf("I=V/R","R=V/I"),listOf("Treating V/I as constant for every device.","Putting an ammeter in parallel."),"physics/formulas/calculator/physics-ohm")),
        listOf("Build series and parallel networks with a low-voltage virtual or physical kit and predict bulb/current changes before closing the switch.","Plot a supplied V–I table, calculate several V/I values and decide whether one resistance is supported."),
        listOf(CurriculumPracticalContent("physics-c10-ohm-practical",PracticalSupportType.PHYSICAL_LAB_GUIDANCE,"Determine the V–I relation for a resistor using a safe low-voltage circuit.",listOf("low-voltage DC source","resistor","ammeter","voltmeter","switch","connecting leads"),listOf("observation table"),listOf("Keep the switch open while wiring.","Have the circuit checked before switching on.","Take several brief V and I readings within instrument range.","Open the switch between readings to limit heating.","Plot V against I with units and determine slope."),listOf("V / V","I / A","instrument range and least count","visible heating or drift"),listOf("R=ΔV/ΔI from best-fit slope","compare individual V/I values"),"The graph is ______; resistance from slope is ______ Ω under the measured conditions.",listOf("Read analogue scales without parallax.","Do not exceed meter ranges.","Record all readings rather than selecting only convenient points."),listOf("Never connect to mains electricity.","Use teacher-approved low voltage.","Disconnect immediately if a component heats unexpectedly."),listOf("Why open the switch between readings?","Why is the voltmeter parallel?","What does graph slope represent?"),true)),
        linkedMapOf("Current is used up." to "Charge is conserved at a junction; electrical energy is transferred.","A battery supplies constant current." to "Current depends on source and connected network.","Parallel resistance must be larger." to "Adding a parallel path lowers equivalent resistance."),
        listOf(
            q("mcq",CurriculumQuestionType.MULTIPLE_CHOICE,CompetencyType.UNDERSTANDING,"Where is a voltmeter connected?","Across the component in parallel.","It compares potential at the two component terminals.","current-voltage"),
            q("numeric",CurriculumQuestionType.NUMERIC_INPUT,CompetencyType.APPLYING,"Find current through 20 Ω at 10 V.","0.5 A","I=10/20=0.5 A.","ohms-law"),
            q("graph",CurriculumQuestionType.GRAPH_INTERPRETATION,CompetencyType.ANALYSING,"A V–I line passes through (0.4 A, 6 V). Find resistance.","15 Ω","Slope V/I=6/0.4=15 Ω.","ohms-law"),
            q("case",CurriculumQuestionType.CASE_BASED,CompetencyType.EVALUATING,"Two identical resistors must draw less current from a fixed source. Choose series or parallel and justify.","Series; its equivalent resistance is larger.","For fixed V, larger R gives smaller total I.","networks"),
            q("experiment",CurriculumQuestionType.EXPERIMENTAL_REASONING,CompetencyType.ANALYSING,"Later V/I values rise during a long trial. Give a plausible cause and control.","Resistor heating changed resistance; open the switch between brief readings.","Ohm's relation assumes stable physical conditions.","safety")),
        CurriculumRevisionResource(listOf("Current is charge per time.","Voltage is energy per charge.","Ohm's law has physical conditions.","Series shares current; parallel shares voltage.","Validate units and limiting cases."),listOf("V=IR","P=VI","E=Pt"),listOf("Ammeter series, voltmeter parallel.","Slope of V–I graph is resistance."),listOf("charge versus energy","series versus parallel","power versus energy"),listOf("physics-electric-mcq","physics-electric-graph")),
        listOf("Magnetic Effects of Electric Current","Class XII Current Electricity","Mathematics: Linear Graphs"),CurriculumCompletionRequirements(true,true,true,true,true,true,true,true,true),ScientificReviewStatus.VERIFIED)
    val chapters=listOf(electricity)
}
