package com.indianservers.aiexplorer.physics.ncert

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.*

object PhysicsNcertProductionContent {
    private const val chapterId = "cbse-2026-c9-physics-c1"
    private const val topicId = "$chapterId-core"
    private fun q(id: String, type: CurriculumQuestionType, competency: CompetencyType, prompt: String, answer: String, explanation: String, error: String, section: String) = CurriculumQuestion("physics-motion-$id", SchoolSubject.PHYSICS, SchoolClassLevel.CLASS_9, chapterId, listOf(topicId), competency, QuestionDifficulty.STANDARD, type, prompt, answer = AnswerDefinition(answer), explanation = explanation, commonErrorTags = listOf(error), remediationSectionId = section)

    val motion = SubjectOwnedCurriculumChapter(
        id = "physics-ncert-c9-motion-production", curriculumNodeId = chapterId, subject = SchoolSubject.PHYSICS, classLevel = SchoolClassLevel.CLASS_9,
        officialChapterTitle = "Describing Motion Around Us", unitTitle = "Motion, Force, Work and Sound", estimatedMinutes = 120, route = "physics/ncert/9/describing-motion",
        topicIds = listOf(topicId),
        learningObjectives = listOf("Choose a reference point and describe position.", "Distinguish distance, displacement, speed and velocity.", "Calculate average speed, velocity and acceleration with SI units.", "Interpret position–time and velocity–time graphs."),
        prerequisites = listOf("Length and time measurement", "Signed numbers", "Coordinates and graph slope"),
        explanationSections = linkedMapOf(
            "reference" to "Motion is a change of position relative to a chosen reference over time. The same object can be stationary relative to one reference and moving relative to another, so the reference must be stated.",
            "distance-displacement" to "Distance is total path length and is non-negative. Displacement connects initial to final position with direction. Its magnitude cannot exceed distance; it can be zero after a non-zero round trip.",
            "speed-velocity" to "Average speed is total distance divided by total time. Average velocity is displacement divided by elapsed time. Equal numerical values occur only in suitable straight, one-direction motion.",
            "acceleration" to "Acceleration is change in velocity per unit time. A negative value along a chosen positive axis does not always mean slowing; compare velocity and acceleration directions.",
            "graphs" to "Slope of a position–time graph gives velocity. Slope of a velocity–time graph gives acceleration, while signed area under it gives displacement. Units must follow from the axes."
        ),
        keyTerms = linkedMapOf("position" to "Location relative to an origin and direction.", "distance" to "Total path length.", "displacement" to "Directed change from initial to final position.", "velocity" to "Rate of change of displacement.", "acceleration" to "Rate of change of velocity."),
        workedExamples = listOf(
            WorkedExample("A learner walks 30 m east then 10 m west in 20 s.", listOf("Distance=30+10=40 m.", "Taking east positive, displacement=30−10=20 m east.", "Average speed=40/20=2 m s⁻¹.", "Average velocity=20/20=1 m s⁻¹ east."), "Distance 40 m; displacement 20 m east; average speed 2 m/s; average velocity 1 m/s east.", "Distance ≥ |displacement| and both rates have SI unit m/s."),
            WorkedExample("Velocity changes uniformly from 4 m/s to 16 m/s in 6 s.", listOf("a=(v−u)/t.", "a=(16−4)/6.", "a=2 m s⁻²."), "2 m/s²", "(m/s)/s = m/s².")
        ),
        diagrams = listOf(
            CurriculumDiagramSpecification("physics-c9-position-time-graph", SchoolSubject.PHYSICS, SchoolClassLevel.CLASS_9, topicId, "Position–time graph and slope triangle", DiagramType.GRAPH, listOf(DiagramLabelRequirement("time", "time / s", "horizontal variable"), DiagramLabelRequirement("position", "position / m", "vertical variable"), DiagramLabelRequirement("slope", "Δposition/Δtime", "velocity")), "Read graph segments as physical motion.", listOf("Axis quantities and SI units are explicit.", "Slope triangle uses two points on the same straight segment.", "A vertical position–time segment is not physical finite-speed motion."), DiagramInteractionMode.LABEL_HIDE_AND_QUIZ, "Position in metres against time in seconds, with horizontal, rising, and falling segments and a labelled slope triangle.", ScientificReviewStatus.VERIFIED),
            CurriculumDiagramSpecification("physics-c9-path-displacement", SchoolSubject.PHYSICS, SchoolClassLevel.CLASS_9, topicId, "Path length and displacement", DiagramType.PROCESS_FLOW, listOf(DiagramLabelRequirement("start", "start", "initial position"), DiagramLabelRequirement("finish", "finish", "final position"), DiagramLabelRequirement("path", "distance path", "total travelled length"), DiagramLabelRequirement("arrow", "displacement", "directed separation")), "Contrast path-dependent distance with endpoint displacement.", listOf("Displacement arrow begins at start and ends at finish.", "Diagram is conceptual and marked not to scale."), DiagramInteractionMode.STATIC_WITH_LABELS, "A curved route from start to finish alongside a straight directed arrow joining the same endpoints.", ScientificReviewStatus.VERIFIED)
        ),
        formulaLinks = listOf(
            CurriculumFormulaLink("physics-speed", "Average speed", mapOf("v" to "average speed", "d" to "total distance", "t" to "elapsed time"), mapOf("v" to "m/s", "d" to "m", "t" to "s"), listOf("Elapsed time is positive."), listOf("d=vt", "t=d/v"), listOf("Using displacement when average speed is required.", "Mixing kilometres and seconds."), "physics/formulas/calculator/physics-speed"),
            CurriculumFormulaLink("physics-final-velocity", "Uniform acceleration relation", mapOf("v" to "final velocity", "u" to "initial velocity", "a" to "constant acceleration", "t" to "elapsed time"), mapOf("v" to "m/s", "u" to "m/s", "a" to "m/s²", "t" to "s"), listOf("Acceleration is constant over the interval.", "All signed quantities use one axis convention."), listOf("a=(v−u)/t", "t=(v−u)/a"), listOf("Dropping direction signs.", "Using this relation when acceleration is not uniform."), "physics/formulas/calculator/physics-final-velocity")
        ),
        activities = listOf("Move a marker along a number line; compare accumulated path tiles with the start-to-finish arrow after each movement.", "Predict a motion story from a graph, then reveal segment labels and revise the story."),
        practicals = listOf(CurriculumPracticalContent("physics-c9-walking-motion-practical", PracticalSupportType.PHYSICAL_LAB_GUIDANCE, "Measure and graph approximately uniform walking motion.", listOf("measuring tape", "stopwatch", "chalk or removable markers"), listOf("straight safe walking area", "observation sheet"), listOf("Mark equal distances along a clear straight path.", "Assign a timekeeper and walker; keep other learners clear of the path.", "Record the time at which the walker reaches each mark.", "Repeat at least three times and retain all readings.", "Plot position against time and calculate a best-supported average speed."), listOf("position / m", "time / s for each trial", "instrument resolution", "unexpected events"), listOf("average speed=total distance/elapsed time", "compare trial spread"), "Within measurement uncertainty, the graph indicates ______ motion because ______.", listOf("Do not start timing after the walker has moved.", "Read and record units with every column.", "Do not discard a trial without recording why."), listOf("Use a dry, obstruction-free path.", "Walking only; no running or collisions.", "Teacher supervision is required."), listOf("Why repeat observations?", "What does graph slope represent?", "Which uncertainty is introduced by human reaction time?"), true)),
        misconceptions = linkedMapOf("Distance and displacement are always equal." to "They differ whenever the route is not the direct one-direction separation.", "Negative acceleration always means slowing down." to "Speed decreases only when acceleration opposes velocity.", "A flat position–time graph means zero position." to "It means constant position and therefore zero velocity."),
        questions = listOf(
            q("mcq", CurriculumQuestionType.MULTIPLE_CHOICE, CompetencyType.UNDERSTANDING, "A runner completes one lap and stops at the start. Which is correct?", "Distance is non-zero and displacement is zero.", "The path has length, but endpoints coincide.", "direction", "distance-displacement"),
            q("numeric", CurriculumQuestionType.NUMERIC_INPUT, CompetencyType.APPLYING, "A car covers 150 m in 12 s. Find average speed with unit.", "12.5 m/s", "150/12=12.5 and m/s is the SI unit.", "unit conversion", "speed-velocity"),
            q("graph", CurriculumQuestionType.GRAPH_INTERPRETATION, CompetencyType.ANALYSING, "A position–time segment rises from (2 s, 5 m) to (7 s, 20 m). Find velocity.", "3 m/s", "Slope=(20−5)/(7−2)=15/5=3 m/s.", "graph interpretation", "graphs"),
            q("case", CurriculumQuestionType.CASE_BASED, CompetencyType.EVALUATING, "Two groups report 5 m/s and 18 km/h for the same walk. Decide whether the reports agree.", "They agree.", "5 m/s×3.6=18 km/h.", "unit conversion", "speed-velocity"),
            q("experiment", CurriculumQuestionType.EXPERIMENTAL_REASONING, CompetencyType.ANALYSING, "A stopwatch trial is much longer because the walker stopped to tie a shoe. Should it be erased?", "No; retain and annotate it, then distinguish it from uniform-motion trials.", "Transparent observation preserves evidence and explains the changed motion.", "conceptual reasoning", "graphs")
        ),
        revision = CurriculumRevisionResource(listOf("State the reference and positive direction.", "Distance follows the path; displacement uses endpoints.", "Graph slope carries physical units.", "Validate every numerical result dimensionally."), listOf("average speed=distance/time", "average velocity=displacement/time", "a=(v−u)/t", "v=u+at"), listOf("position–time slope is velocity", "velocity–time slope is acceleration", "velocity–time signed area is displacement"), listOf("speed versus velocity", "negative coordinate versus negative displacement", "negative acceleration versus slowing"), listOf("physics-motion-mcq", "physics-motion-numeric", "physics-motion-graph")),
        relationships = listOf("How Forces Affect Motion", "Work, Energy, and Simple Machines", "Mathematics: Coordinate Geometry"),
        requirements = CurriculumCompletionRequirements(true, true, true, true, true, true, true, true, true), reviewStatus = ScientificReviewStatus.VERIFIED
    )
    val chapters = listOf(motion)
}
