package com.indianservers.aiexplorer.learning.ncert.intelligence
import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.reference.*
object MathematicsLearningIntelligence{
 private val s=SchoolSubject.MATHEMATICS;private val levels=setOf(SchoolClassLevel.CLASS_7,SchoolClassLevel.CLASS_8,SchoolClassLevel.CLASS_9,SchoolClassLevel.CLASS_10)
 private fun node(vararg k:String)=ReferenceCurriculumResolver.topic(s,*k)
 val concepts=listOf(
  ReferenceConceptFactory.create("math-fractions",node("Number","Rational"),s,levels,emptyList(),null,"fraction comparison","math-larger-denominator","Larger denominator means larger fraction","For equal numerators, more equal parts make each part smaller.","One third is smaller than one half.","One third is larger because 3 is larger than 2.",DiagnosticQuestionKind.PREREQUISITE_DISCRIMINATION,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.SYMBOLIC_PROBLEM)),
  ReferenceConceptFactory.create("math-linear-equations",node("Linear Equation"),s,levels,listOf("math-fractions"),"math-linear-equation-balance","equation preservation","math-move-change-sign","A moved term changes sign automatically","The sign-change shortcut represents applying the same inverse operation to both sides.","Subtract the same quantity from both sides.","Move the term across and change its sign without an operation.",DiagnosticQuestionKind.REASONING,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.SYMBOLIC_PROBLEM)),
  ReferenceConceptFactory.create("math-triangles",node("Triangle"),s,levels,listOf("math-fractions"),"math-triangle-lab","triangle similarity","math-similar-congruent","Similar figures are necessarily congruent","Similar shapes may have different scale; congruent shapes also have equal corresponding lengths.","Similar triangles can differ in size.","Similar triangles are always the same size.",DiagnosticQuestionKind.VISUAL,setOf(MasteryEvidenceType.DIAGRAM_TASK,MasteryEvidenceType.CONSTRUCTION_TASK)),
  ReferenceConceptFactory.create("math-coordinate-geometry",node("Coordinate"),s,levels,listOf("math-linear-equations"),"math-coordinate-geometry","graph slope","math-height-is-slope","Graph height is slope","Slope is change in vertical coordinate divided by horizontal change, not a point's height.","Compare rise divided by run.","The highest point always has the greatest slope.",DiagnosticQuestionKind.VISUAL,setOf(MasteryEvidenceType.DATA_INTERPRETATION,MasteryEvidenceType.NUMERICAL_PROBLEM)),
  ReferenceConceptFactory.create("math-probability",node("Probability"),s,levels,listOf("math-fractions"),"math-probability-experiment","multiplicative size","math-multiply-always-larger","Multiplying always makes a number larger","Multiplication by a positive number below one makes a positive number smaller.","Multiplying by one half halves a positive quantity.","Every multiplication increases the starting number.",DiagnosticQuestionKind.CONCEPT,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.DATA_INTERPRETATION)),
  ReferenceConceptFactory.create("math-trigonometric-graphs",node("Trigon"),s,levels,listOf("math-coordinate-geometry"),"math-right-triangle-trig","trigonometric graph parameters","math-trig-amplitude-period","Amplitude changes the period","Amplitude changes vertical scale; frequency changes period and phase changes horizontal position.","Doubling amplitude doubles graph height but preserves its period.","A taller sine graph always completes cycles faster.",DiagnosticQuestionKind.VISUAL,setOf(MasteryEvidenceType.DATA_INTERPRETATION,MasteryEvidenceType.SIMULATION_PREDICTION))
 )
}
