package com.indianservers.aiexplorer.biology.ncert

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.*

object BiologyNcertBatch02Content {
    private const val cid="cbse-2026-c10-biology-c2"; private const val tid="$cid-core"
    private fun q(id:String,t:CurriculumQuestionType,c:CompetencyType,p:String,a:String,e:String,s:String)=CurriculumQuestion("bio-control-$id",SchoolSubject.BIOLOGY,SchoolClassLevel.CLASS_10,cid,listOf(tid),c,QuestionDifficulty.STANDARD,t,p,answer=AnswerDefinition(a),explanation=e,commonErrorTags=listOf("control reasoning"),remediationSectionId=s)
    val controlCoordination=SubjectOwnedCurriculumChapter(
        "biology-ncert-c10-control-production",cid,SchoolSubject.BIOLOGY,SchoolClassLevel.CLASS_10,"Control and Coordination","World of Living",135,"biology/ncert/10/control-and-coordination",listOf(tid),
        listOf("Trace stimulus–receptor–coordinator–effector pathways.","Distinguish reflex actions from conscious responses.","Compare nervous and hormonal coordination without treating either as universally faster or better.","Relate plant directional responses to growth and signalling."),
        listOf("Cell membranes and receptors","Muscle action","Life Processes","Plant growth"),
        linkedMapOf("nervous-system" to "Receptors detect change and neurons transmit electrical signals across organised pathways. Synapses pass signals between cells; the response depends on the pathway and central processing.","reflexes" to "A reflex arc provides a rapid organised response through receptor, sensory neuron, relay region, motor neuron and effector. The brain can receive information even when the immediate response is coordinated through the spinal cord.","hormones" to "Hormones are chemical signals released in small amounts and transported to target cells with appropriate receptors. Feedback helps regulate their effects; hormones do not act identically on every cell.","plants" to "Plants coordinate through chemical signals and changes in growth or cell water status. Tropisms are directional growth responses relative to a stimulus; they are not animal-like movement toward a conscious goal.","integration" to "Nervous and endocrine systems interact. A useful comparison states signal type, route, speed, duration and target specificity rather than using one vague faster/slower label."),
        linkedMapOf("stimulus" to "A detectable change.","receptor" to "A specialised structure detecting a stimulus.","reflex arc" to "Neural pathway producing a rapid automatic response.","hormone" to "A chemical signal acting on receptor-bearing target cells.","tropism" to "Directional plant growth response relative to a stimulus."),
        listOf(WorkedExample("Trace withdrawal from a hot surface.",listOf("Skin receptors detect damaging heat.","Sensory neuron carries the signal to the spinal pathway.","Motor neuron activates flexor muscles.","The hand withdraws while information also reaches the brain."),"receptor→sensory neuron→relay/spinal cord→motor neuron→effector","The pathway distinguishes detection, coordination and action."),WorkedExample("A shoot bends toward one-sided light. Explain without saying it chooses light.",listOf("Light direction alters growth-signal distribution.","Cells on opposite sides elongate differently.","Unequal growth bends the shoot."),"A directional growth response (phototropism).","The explanation uses mechanism, not intention.")),
        listOf(CurriculumDiagramSpecification("bio-c10-reflex-arc",SchoolSubject.BIOLOGY,SchoolClassLevel.CLASS_10,tid,"Reflex arc and information flow",DiagramType.PROCESS_FLOW,listOf(DiagramLabelRequirement("receptor","skin receptor","detects stimulus"),DiagramLabelRequirement("sensory","sensory neuron","input"),DiagramLabelRequirement("cord","spinal cord/relay","coordination"),DiagramLabelRequirement("motor","motor neuron","output"),DiagramLabelRequirement("effector","muscle","response")),"Connect structure, direction and function in a reflex.",listOf("Arrows show one signal direction around the arc.","Brain-information branch does not replace spinal coordination.","Synapses are represented as junctions, not fused neurons."),DiagramInteractionMode.LABEL_HIDE_AND_QUIZ,"A hand receptor connects by a sensory neuron to a spinal relay, then a motor neuron to an arm muscle; arrows show signal direction and a branch carries information toward the brain.",ScientificReviewStatus.VERIFIED)),
        emptyList(),listOf("Arrange pathway cards for three responses and justify where detection, coordination and action occur.","Observe time-lapse plant-response data and distinguish growth direction from ordinary movement."),
        listOf(CurriculumPracticalContent("bio-c10-tropism-data",PracticalSupportType.DATA_ANALYSIS_ACTIVITY,"Analyse controlled shoot-growth observations under one-sided light.",emptyList(),listOf("provided time-series images or angle table"),listOf("Identify independent, dependent and controlled variables.","Record shoot angle at each time without inventing intermediate values.","Plot angle against time for light and control groups.","Compare trends and variation.","State a conclusion limited to the supplied data."),listOf("time / h","shoot angle / degree","light direction","control condition"),listOf("change in angle","comparison of group trend"),"The data support/do not support directional growth because ______.",listOf("Do not infer conscious choice.","Do not ignore the control group.","Separate observation from mechanism."),listOf("Use only teacher-provided safe datasets or supervised plants; no hazardous materials."),listOf("Why is a control group needed?","Does bending prove conscious movement?","What additional replication would strengthen the result?"),false)),
        linkedMapOf("Reflexes never involve the brain." to "The immediate arc may be spinal while information also reaches the brain.","Every hormone affects every cell." to "Only cells with suitable receptors respond.","Plants have no coordination." to "Plants coordinate through chemical signals, growth and turgor changes."),
        listOf(q("sequence",CurriculumQuestionType.SEQUENCE_ORDERING,CompetencyType.APPLYING,"Order the reflex pathway components.","receptor→sensory neuron→relay→motor neuron→effector","Information flows from detection to response.","reflexes"),q("diagram",CurriculumQuestionType.DIAGRAM_LABELLING,CompetencyType.APPLYING,"On the reflex visual, label the input neuron and output neuron.","sensory neuron; motor neuron","Sensory carries input to the coordinator; motor carries output.","nervous-system"),q("compare",CurriculumQuestionType.TABLE_INTERPRETATION,CompetencyType.ANALYSING,"A signal is chemical, blood-borne and long-lasting. Classify the coordination mode.","endocrine/hormonal","The route and duration match hormone signalling.","integration"),q("case",CurriculumQuestionType.CASE_BASED,CompetencyType.EVALUATING,"A learner says a plant bends because it sees light. Rewrite scientifically.","Light direction changes growth signalling, causing unequal elongation and bending.","Mechanistic language avoids intention.","plants"),q("experiment",CurriculumQuestionType.EXPERIMENTAL_REASONING,CompetencyType.ANALYSING,"Both lit and dark control shoots bend equally. What should the conclusion say?","The data do not support one-sided light as the cause under these conditions.","The control trend prevents an unsupported causal claim.","plants")),
        CurriculumRevisionResource(listOf("Coordination links detection, processing and response.","Reflex arcs are rapid organised pathways.","Hormones require target receptors.","Tropisms are directional growth responses."),emptyList(),listOf("Reflex arrows distinguish sensory input from motor output."),listOf("reflex versus voluntary action","neural versus hormonal signalling","growth response versus locomotion"),listOf("bio-control-sequence","bio-control-case")),
        listOf("Life Processes","How do Organisms Reproduce?","Class XI Neural Control and Coordination"),CurriculumCompletionRequirements(true,true,false,true,true,true,true,true,true),ScientificReviewStatus.VERIFIED)
    val chapters=listOf(controlCoordination)
}
