package com.indianservers.aiexplorer.biology.ncert

import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.curriculum.production.*

object BiologyNcertProductionContent {
    private const val chapterId = "cbse-2026-c10-biology-c1"
    private const val topicId = "$chapterId-core"
    private fun q(id: String, type: CurriculumQuestionType, competency: CompetencyType, prompt: String, answer: String, explanation: String, error: String, section: String) = CurriculumQuestion("bio-life-$id", SchoolSubject.BIOLOGY, SchoolClassLevel.CLASS_10, chapterId, listOf(topicId), competency, QuestionDifficulty.STANDARD, type, prompt, answer = AnswerDefinition(answer), explanation = explanation, commonErrorTags = listOf(error), remediationSectionId = section)

    val lifeProcesses = SubjectOwnedCurriculumChapter(
        id = "biology-ncert-c10-life-processes-production", curriculumNodeId = chapterId, subject = SchoolSubject.BIOLOGY, classLevel = SchoolClassLevel.CLASS_10,
        officialChapterTitle = "Life Processes", unitTitle = "World of Living", estimatedMinutes = 150, route = "biology/ncert/10/life-processes",
        topicIds = listOf(topicId),
        learningObjectives = listOf("Explain why maintenance processes continue even at rest.", "Compare autotrophic and heterotrophic nutrition.", "Trace gas exchange, transport and cellular respiration without confusing them.", "Relate specialised exchange surfaces and transport systems to organism size.", "Explain excretion as controlled removal of metabolic waste."),
        prerequisites = listOf("Cell structure and organelles", "Tissues", "Diffusion", "Atoms, molecules and chemical change"),
        explanationSections = linkedMapOf(
            "overview" to "Life processes maintain an organised living system: obtaining and using materials, releasing usable energy, transporting substances and removing metabolic wastes. They are coordinated rather than isolated chapters inside the body.",
            "nutrition" to "Green plants use light energy captured by chlorophyll to form carbohydrate from carbon dioxide and water, releasing oxygen. Animals obtain food and digest large molecules before absorption; enzymes act under suitable conditions and do not themselves provide energy.",
            "respiration" to "Breathing moves air; gas exchange transfers oxygen and carbon dioxide; cellular respiration releases usable energy from food inside cells. Aerobic respiration releases more usable energy than incomplete anaerobic pathways, but breathing and cellular respiration are not synonyms.",
            "transport" to "Large multicellular organisms need bulk transport because diffusion alone is too slow over long distances. Blood distributes gases, nutrients, wastes and signals. In plants, xylem moves water/minerals and phloem transports organic solutes; their mechanisms and directions should not be treated as identical.",
            "excretion" to "Metabolism forms wastes that can disturb internal conditions. Human kidneys filter blood, selectively reabsorb useful substances and adjust water and ion removal. Excretion is not the same as egestion of undigested food.",
            "integration" to "The processes form a dependency network: nutrition supplies molecules, respiration releases usable energy, transport connects exchange surfaces with cells, and excretion controls waste. A failure in one process affects the others."
        ),
        keyTerms = linkedMapOf("autotrophic nutrition" to "Production of organic food from inorganic materials using an energy source.", "digestion" to "Breakdown of complex food into absorbable forms.", "gas exchange" to "Diffusion of respiratory gases across a surface.", "cellular respiration" to "Cell reactions that release usable energy from food.", "translocation" to "Movement of organic solutes through phloem.", "excretion" to "Removal of metabolic waste."),
        workedExamples = listOf(
            WorkedExample("Explain why an athlete continues breathing rapidly just after a sprint.", listOf("Working muscles increased energy demand.", "Oxygen delivery and carbon-dioxide removal must recover toward resting conditions.", "Circulation and ventilation remain elevated briefly while internal conditions are restored."), "Rapid breathing supports recovery of gas exchange and metabolic balance; it is not evidence that breathing itself releases cellular energy.", "The explanation links organ-level ventilation with cellular demand."),
            WorkedExample("Predict one consequence of severe loss of functional villi.", listOf("Villi provide large absorptive surface area.", "Loss reduces absorption of digested nutrients.", "Cells receive less material despite digestion occurring."), "Reduced nutrient absorption and possible deficiency/low energy availability.", "Structure–function reasoning identifies surface area as the changed variable.")
        ),
        diagrams = listOf(
            CurriculumDiagramSpecification("bio-c10-life-process-network", SchoolSubject.BIOLOGY, SchoolClassLevel.CLASS_10, topicId, "Life-process dependency network", DiagramType.PROCESS_FLOW, listOf(DiagramLabelRequirement("nutrition", "nutrition", "material input"), DiagramLabelRequirement("respiration", "cellular respiration", "usable energy release"), DiagramLabelRequirement("transport", "transport", "distribution"), DiagramLabelRequirement("excretion", "excretion", "waste control"), DiagramLabelRequirement("cells", "body cells", "shared destination/source")), "Show causal relationships among processes rather than four disconnected definitions.", listOf("Arrows are labelled with transported material or dependency.", "Breathing and cellular respiration use distinct labels.", "Excretion arrow refers to metabolic waste, not undigested food."), DiagramInteractionMode.LABEL_HIDE_AND_QUIZ, "A central body-cell node connects to nutrition, gas exchange, transport and excretion; arrows name nutrients, oxygen, carbon dioxide and nitrogenous wastes.", ScientificReviewStatus.VERIFIED),
            CurriculumDiagramSpecification("bio-c10-nephron-structure-function", SchoolSubject.BIOLOGY, SchoolClassLevel.CLASS_10, topicId, "Simplified nephron: filtration and selective reabsorption", DiagramType.BIOLOGICAL_STRUCTURE, listOf(DiagramLabelRequirement("glomerulus", "glomerulus", "capillary filtration region"), DiagramLabelRequirement("capsule", "Bowman's capsule", "collects filtrate"), DiagramLabelRequirement("tubule", "renal tubule", "selective reabsorption/secretion"), DiagramLabelRequirement("collecting", "collecting duct", "final water adjustment and urine flow"), DiagramLabelRequirement("capillary", "surrounding capillaries", "return useful substances")), "Relate nephron regions to urine formation at school level.", listOf("Blood and filtrate paths use distinct styles.", "Diagram is simplified and not to scale.", "It does not imply that useful cells or large proteins normally enter filtrate."), DiagramInteractionMode.LABEL_HIDE_AND_QUIZ, "A labelled nephron shows a capillary knot in Bowman's capsule, a tubule beside surrounding capillaries and a collecting duct, with arrows for filtration and reabsorption.", ScientificReviewStatus.VERIFIED)
        ),
        formulaLinks = emptyList(),
        activities = listOf("Build a card network linking food, oxygen, carbon dioxide, water, urea and cells; justify every arrow and revise any arrow that confuses organ exchange with cell reactions.", "Compare exchange-surface cards—villus, alveolus, root hair and nephron—by surface area, thin boundary, transport link and concentration-gradient role."),
        practicals = listOf(CurriculumPracticalContent("bio-c10-stomata-slide", PracticalSupportType.PHYSICAL_LAB_GUIDANCE, "Prepare and observe a temporary leaf-peel mount to relate stomatal structure to gas exchange.", listOf("clean slide", "cover slip", "dropper", "forceps", "needle/brush", "school microscope"), listOf("fresh teacher-approved leaf peel", "water", "teacher-approved stain if prescribed"), listOf("Obtain a very thin epidermal peel with teacher guidance.", "Place it flat in a drop of water; add only the approved stain if directed.", "Lower the cover slip at an angle to reduce trapped air.", "Begin with low power, focus safely, then observe at suitable magnification.", "Draw observed cells and label guard cells, pore and surrounding epidermal cells; do not invent unseen structures."), listOf("field of view", "number and distribution of visible stomata", "guard-cell appearance", "labelled biological drawing"), emptyList(), "Stomata were identified by ______; their structure supports gas exchange because ______.", listOf("Use a thin, flat peel.", "Do not allow the objective lens to strike the slide.", "Base the drawing on the specimen actually observed."), listOf("Handle needles, glass and stain only as instructed.", "Wash hands after plant material or stain.", "Physical microscope work requires teacher supervision; this guide is not a virtual substitute."), listOf("What is the function of guard cells?", "Why start with low power?", "How can an air bubble be distinguished from a cell?", "Why might stomatal distribution vary?"), true)),
        misconceptions = linkedMapOf("Breathing and respiration are the same." to "Breathing ventilates exchange surfaces; cellular respiration is a chemical energy-releasing process in cells.", "Plants obtain all food from soil." to "Plants obtain water/minerals from soil but make organic food using carbon dioxide, water and light energy.", "Excretion means removal of undigested food." to "Excretion removes metabolic waste; egestion removes undigested material.", "Arteries always carry oxygenated blood." to "Arteries carry blood away from the heart; oxygen content depends on the circuit."),
        questions = listOf(
            q("multi", CurriculumQuestionType.MULTIPLE_SELECT, CompetencyType.UNDERSTANDING, "Select processes occurring at an exchange surface: diffusion of oxygen across alveoli; breakdown of glucose inside mitochondria; absorption across villi.", "diffusion across alveoli and absorption across villi", "Both move substances across specialised boundaries; mitochondrial respiration occurs within cells.", "mechanism", "respiration"),
            q("sequence", CurriculumQuestionType.SEQUENCE_ORDERING, CompetencyType.APPLYING, "Order: absorption into blood, digestion into small molecules, transport to cells, ingestion.", "ingestion → digestion → absorption → transport", "Materials must be made absorbable before entering transport.", "sequence", "nutrition"),
            q("diagram", CurriculumQuestionType.DIAGRAM_LABELLING, CompetencyType.APPLYING, "On the nephron visual, identify the filtration region and the region where useful solutes return to blood.", "glomerulus/Bowman's capsule; renal tubule with surrounding capillaries", "Filtration begins at the renal corpuscle; selective reabsorption occurs along the tubule.", "diagram interpretation", "excretion"),
            q("case", CurriculumQuestionType.CASE_BASED, CompetencyType.ANALYSING, "A ring of bark including phloem is removed while xylem remains. Predict the most direct transport disruption.", "Movement of sugars and other organic solutes through phloem is disrupted.", "Xylem and phloem have distinct transport roles.", "structure and function", "transport"),
            q("experiment", CurriculumQuestionType.EXPERIMENTAL_REASONING, CompetencyType.EVALUATING, "A learner draws ten stomata although only four were visible. Explain the scientific problem.", "The record no longer represents the observation and creates fabricated data.", "Biological drawings must distinguish observation from expectation.", "diagram interpretation", "integration")
        ),
        revision = CurriculumRevisionResource(listOf("Maintenance requires continuous coordinated processes.", "Distinguish ventilation, gas exchange and cellular respiration.", "Transport solves long-distance diffusion limits.", "Excretion removes metabolic waste and regulates internal conditions."), emptyList(), listOf("Dependency network links materials and processes.", "Nephron diagram connects filtration, reabsorption and urine flow."), listOf("breathing versus respiration", "xylem versus phloem", "excretion versus egestion", "artery direction versus oxygen content"), listOf("bio-life-multi", "bio-life-diagram", "bio-life-case")),
        relationships = listOf("Control and Coordination", "How do Organisms Reproduce?", "Class XI Human Physiology"),
        requirements = CurriculumCompletionRequirements(true, true, false, true, true, true, true, true, true), reviewStatus = ScientificReviewStatus.VERIFIED
    )
    val chapters = listOf(lifeProcesses)
}
