package com.indianservers.aiexplorer.learning

private val algebra = KnowledgeTopic.Algebra

internal fun algebraAndDiscreteTheorems(): List<TheoremCard> = listOf(
    theoremEntry("rank-nullity", "Rank-nullity theorem", "Linear Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "For T:V→W with finite-dimensional V, dim V=rank T+nullity T.", "linear systems|dimension|matrices", "finite-dimensional domain", "Choose a basis of ker T and extend it to V.|The images of the added basis vectors form a basis of im T."),
    theoremEntry("invertible-matrix", "Invertible matrix theorem", "Linear Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "For a square matrix, invertibility, full rank, trivial nullspace, nonzero determinant, and unique solvability are equivalent.", "matrix inverse|linear systems|rank", "square matrix over a field", "Use Gaussian elimination to connect pivot conditions.|Translate pivots into rank, nullspace, determinant, and inverse statements."),
    theoremEntry("spectral", "Spectral theorem", "Linear Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "Every real symmetric matrix has real eigenvalues and an orthonormal eigenbasis.", "eigenvalues|orthogonality|PCA", "real symmetric matrix", "Symmetry makes distinct eigenspaces orthogonal.|Induct on invariant orthogonal complements."),
    theoremEntry("cayley-hamilton", "Cayley-Hamilton theorem", "Linear Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "Every square matrix satisfies its own characteristic polynomial.", "matrix powers|inverse formulas|linear recurrences", "square matrix over a commutative field", "Use the adjugate identity for λI-A.|Compare polynomial coefficients and substitute A."),
    theoremEntry("singular-value-decomposition", "Singular value decomposition theorem", "Linear Algebra", algebra, KnowledgeLevel.PG, TheoremBand.PG, "Every real matrix A can be written UΣVᵀ with U,V orthogonal and Σ diagonal with non-negative entries.", "data compression|least squares|low-rank approximation", "finite real matrix", "Apply the spectral theorem to AᵀA.|Use its orthonormal eigenvectors and normalized images under A."),

    theoremEntry("lagrange-group", "Lagrange's theorem", "Abstract Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "The order of a subgroup of a finite group divides the order of the group.", "group orders|cyclic subgroups|modular arithmetic", "finite group|subgroup", "Left cosets partition the group.|Every coset has the subgroup's size."),
    theoremEntry("orbit-stabilizer", "Orbit-stabilizer theorem", "Abstract Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "For a finite group action, |G|=|Orb(x)|·|Stab(x)|.", "symmetry|counting|group actions", "finite group action", "Elements sending x to a fixed orbit point form a stabilizer coset.|Count these equal fibres."),
    theoremEntry("first-isomorphism-group", "First isomorphism theorem for groups", "Abstract Algebra", algebra, KnowledgeLevel.UG, TheoremBand.UG, "For a homomorphism φ:G→H, G/kerφ is isomorphic to imφ.", "quotient groups|homomorphisms|structure", "group homomorphism", "Map a coset g kerφ to φ(g).|Verify it is well-defined, bijective, and operation-preserving."),
    theoremEntry("sylow-first", "First Sylow theorem", "Abstract Algebra", algebra, KnowledgeLevel.PG, TheoremBand.PG, "If p^k divides |G|, then a finite group G has a subgroup of order p^k.", "finite groups|p-subgroups|classification", "finite group|p prime", "Let a maximal p-subgroup act on cosets.|A counting argument forces its order to contain the full p-part."),
    theoremEntry("fg-abelian-structure", "Structure theorem for finitely generated abelian groups", "Abstract Algebra", algebra, KnowledgeLevel.PG, TheoremBand.PG, "Every finitely generated abelian group is a direct sum of a free abelian group and finite cyclic prime-power groups.", "classification|modules|abelian groups", "finitely generated abelian group", "Present the group as a quotient of a free module.|Apply Smith normal form to the relation matrix."),

    theoremEntry("euclid-primes", "Euclid's theorem on primes", "Number Theory", algebra, KnowledgeLevel.School, TheoremBand.CLASS_6_8, "There are infinitely many prime numbers.", "primes|divisibility|contradiction", "positive integers", "Assume finitely many primes.|Multiply them and add one; any prime divisor is absent from the list."),
    theoremEntry("bezout-identity", "Bézout's identity", "Number Theory", algebra, KnowledgeLevel.School, TheoremBand.CLASS_9_10, "For integers a,b, gcd(a,b)=ax+by for some integers x,y.", "HCF|linear Diophantine equations|modular inverses", "a,b are not both zero", "Run the Euclidean algorithm.|Back-substitute each remainder."),
    theoremEntry("fermat-little", "Fermat's little theorem", "Number Theory", algebra, KnowledgeLevel.UG, TheoremBand.UG, "If p is prime and p∤a, then a^(p-1)≡1 (mod p).", "modular arithmetic|primes|cryptography", "p prime|gcd(a,p)=1", "Multiplication by a permutes the nonzero residues modulo p.|Multiply and cancel their product."),
    theoremEntry("euler-totient", "Euler's theorem", "Number Theory", algebra, KnowledgeLevel.UG, TheoremBand.UG, "If gcd(a,n)=1, then a^φ(n)≡1 (mod n).", "modular powers|RSA|congruences", "n>1|gcd(a,n)=1", "Multiplication by a permutes the reduced residue system modulo n.|Multiply and cancel."),
    theoremEntry("chinese-remainder", "Chinese remainder theorem", "Number Theory", algebra, KnowledgeLevel.UG, TheoremBand.UG, "A system of congruences modulo pairwise coprime integers has a unique solution modulo their product.", "simultaneous congruences|cryptography|computation", "moduli are pairwise coprime", "Use Bézout coefficients to build selectors equal to one modulo one factor and zero modulo the others.|Sum the selected residues."),

    theoremEntry("pigeonhole", "Pigeonhole principle", "Combinatorics", algebra, KnowledgeLevel.School, TheoremBand.CLASS_6_8, "If more than n objects are placed in n boxes, some box contains at least two objects.", "counting|existence|distribution", "finite objects and boxes", "If every box held at most one object, there would be at most n objects."),
    theoremEntry("inclusion-exclusion", "Inclusion-exclusion principle", "Combinatorics", algebra, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "The size of a finite union equals the alternating sum of intersection sizes.", "counting unions|probability|derangements", "finite sets", "An element lying in r sets contributes Σ(-1)^(k+1)C(r,k)=1."),
    theoremEntry("vandermonde", "Vandermonde's identity", "Combinatorics", algebra, KnowledgeLevel.UG, TheoremBand.UG, "Σ C(r,k)C(s,n-k)=C(r+s,n).", "binomial coefficients|counting|convolution", "non-negative integers", "Count n-person selections from two disjoint groups.|Partition by the number selected from the first group."),
    theoremEntry("hall-marriage", "Hall's marriage theorem", "Combinatorics", algebra, KnowledgeLevel.UG, TheoremBand.UG, "A finite bipartite graph has a matching saturating one part exactly when every subset has at least as many neighbours.", "matching|scheduling|assignment", "finite bipartite graph", "Necessity follows from any matching.|For sufficiency, induct and split on a tight subset or extend after deleting an edge."),
    theoremEntry("burnside", "Burnside's lemma", "Combinatorics", algebra, KnowledgeLevel.UG, TheoremBand.UG, "The number of orbits of a finite group action equals the average number of fixed points.", "symmetry counting|colourings|necklaces", "finite group acting on a finite set", "Count pairs (g,x) with gx=x first by group elements and then by orbits."),

    theoremEntry("handshaking", "Handshaking lemma", "Graph Theory", algebra, KnowledgeLevel.School, TheoremBand.CLASS_6_8, "In a finite undirected graph, the sum of vertex degrees is twice the number of edges.", "graphs|degree|counting", "finite undirected graph", "Count edge endpoints by vertices and by edges."),
    theoremEntry("euler-trail", "Euler trail criterion", "Graph Theory", algebra, KnowledgeLevel.School, TheoremBand.CLASS_9_10, "A connected graph has an Euler circuit exactly when every vertex has even degree; it has an open Euler trail exactly when two vertices have odd degree.", "routes|networks|graph traversal", "all non-isolated vertices are connected", "Entering and leaving pairs incident edges at internal vertices.|Construct a closed trail and splice in unused cycles."),
    theoremEntry("tree-equivalence", "Tree characterisation theorem", "Graph Theory", algebra, KnowledgeLevel.UG, TheoremBand.UG, "For a finite graph, being connected and acyclic is equivalent to having a unique path between every vertex pair and to being connected with |E|=|V|-1.", "trees|networks|induction", "finite graph", "Remove a leaf and apply induction.|Cycles create alternate paths, while missing connectivity lowers the edge requirement."),
    theoremEntry("euler-planar", "Euler's planar formula", "Graph Theory", algebra, KnowledgeLevel.UG, TheoremBand.UG, "For a connected planar embedding, V-E+F=2.", "planarity|polyhedra|map colouring", "finite connected planar embedding", "A tree has one face and satisfies the formula.|Adding a non-crossing edge increases E and F together."),
    theoremEntry("max-flow-min-cut", "Max-flow min-cut theorem", "Graph Theory", algebra, KnowledgeLevel.UG, TheoremBand.UG, "The maximum value of an s-t flow equals the minimum capacity of an s-t cut.", "networks|routing|capacity planning", "finite capacitated directed network", "Any flow is bounded by every cut.|When no augmenting path remains, reachable residual vertices define a cut whose capacity equals the flow."),
)
