package com.indianservers.aiexplorer.learning

private val calculus = KnowledgeTopic.Calculus

internal fun analysisTheorems(): List<TheoremCard> = listOf(
    theoremEntry("rolle", "Rolle's theorem", "Calculus", calculus, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "If f is continuous on [a,b], differentiable on (a,b), and f(a)=f(b), then f'(c)=0 for some c∈(a,b).", "stationary points|root separation|mean value theorem", "continuous on [a,b]|differentiable on (a,b)|equal endpoint values", "The extreme-value theorem gives an interior maximum or minimum unless f is constant.|Fermat's theorem gives zero derivative there."),
    theoremEntry("mean-value", "Mean value theorem", "Calculus", calculus, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "A differentiable curve has a tangent parallel to its endpoint secant.", "derivatives|rates|error bounds", "continuous on [a,b]|differentiable on (a,b)", "Subtract the endpoint secant line.|Apply Rolle's theorem."),
    theoremEntry("fundamental-calculus", "Fundamental theorem of calculus", "Calculus", calculus, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "For continuous f, the accumulated-area function has derivative f, and ∫[a,b]f=F(b)-F(a) for any antiderivative F.", "definite integrals|antiderivatives|area", "continuous integrand", "Bound the area increment by local minimum and maximum values.|Take the difference-quotient limit."),
    theoremEntry("taylor", "Taylor's theorem with remainder", "Calculus", calculus, KnowledgeLevel.UG, TheoremBand.UG, "A sufficiently differentiable function equals its degree-n Taylor polynomial plus a controlled remainder involving f^(n+1).", "approximation|series|error bounds", "n+1 derivatives on the interval", "Subtract the Taylor polynomial and an adjusted power term.|Apply Rolle's theorem repeatedly."),
    theoremEntry("inverse-function", "Inverse function theorem", "Calculus", calculus, KnowledgeLevel.UG, TheoremBand.UG, "A continuously differentiable map with invertible derivative at a point has a differentiable local inverse there.", "coordinate changes|nonlinear systems|Jacobians", "continuously differentiable map|non-singular derivative", "Linearise around the point.|Use contraction estimates to solve locally and differentiate the identity."),

    theoremEntry("intermediate-value", "Intermediate value theorem", "Real Analysis", calculus, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "A continuous function on an interval assumes every value between any two of its values.", "root existence|continuity|bisection", "continuous on an interval", "Bisect intervals whose endpoint values bracket the target.|Completeness gives a limit point and continuity gives the target value."),
    theoremEntry("extreme-value", "Extreme value theorem", "Real Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "A continuous real function on a compact set attains its maximum and minimum.", "optimization|bounds|existence", "continuous function|nonempty compact domain", "An optimizing sequence has a convergent subsequence.|Continuity transfers the limiting value."),
    theoremEntry("bolzano-weierstrass", "Bolzano-Weierstrass theorem", "Real Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "Every bounded sequence in R^n has a convergent subsequence.", "sequences|compactness|limits", "bounded sequence|finite-dimensional Euclidean space", "Nest bounded boxes containing infinitely many terms.|Choose one term from each box."),
    theoremEntry("heine-borel", "Heine-Borel theorem", "Real Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "A subset of R^n is compact exactly when it is closed and bounded.", "compactness|optimization|uniform continuity", "finite-dimensional Euclidean space", "Compact sets are closed and bounded.|For the converse, use nested boxes or sequential compactness."),
    theoremEntry("monotone-convergence-sequence", "Monotone convergence theorem for sequences", "Real Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "Every bounded monotone real sequence converges.", "sequences|limits|series tests", "monotone and bounded sequence", "Take the supremum for an increasing sequence.|The supremum property supplies the ε-bound."),

    theoremEntry("cauchy-integral", "Cauchy's integral theorem", "Complex Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "The integral of a holomorphic function around a closed contractible contour is zero.", "contour integration|analytic functions|antiderivatives", "holomorphic on a simply connected region", "Use Green's theorem under smoothness, then approximation or deformation for the general case."),
    theoremEntry("cauchy-integral-formula", "Cauchy's integral formula", "Complex Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "If f is holomorphic inside and on C, then f(a)=(1/(2πi))∮C f(z)/(z-a) dz.", "function values|derivatives|analyticity", "a inside a positively oriented contour|f holomorphic", "Subtract f(a), making the apparent singularity removable.|Apply Cauchy's theorem to the remainder and evaluate ∮1/(z-a)."),
    theoremEntry("liouville", "Liouville's theorem", "Complex Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "Every bounded entire function is constant.", "fundamental theorem of algebra|entire functions|growth", "entire and bounded function", "Cauchy's derivative estimate gives |f'(a)|≤M/R for every R.|Let R→∞."),
    theoremEntry("maximum-modulus", "Maximum modulus principle", "Complex Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "A non-constant holomorphic function cannot attain a local maximum of its modulus inside its domain.", "complex optimization|uniqueness|boundary values", "holomorphic on a connected open set", "The mean-value property forces equality throughout a disk if an interior maximum occurs.|Continue across the connected domain."),
    theoremEntry("residue", "Residue theorem", "Complex Analysis", calculus, KnowledgeLevel.PG, TheoremBand.PG, "A contour integral of a meromorphic function equals 2πi times the sum of enclosed residues.", "improper integrals|inverse transforms|complex evaluation", "isolated enclosed singularities|no singularity on contour", "Excise small circles around singularities.|Apply Cauchy's theorem and read the z^-1 Laurent coefficients."),

    theoremEntry("superposition", "Superposition principle", "Differential Equations", calculus, KnowledgeLevel.UG, TheoremBand.UG, "Linear combinations of solutions of a homogeneous linear differential equation are solutions.", "linear ODEs|solution spaces|boundary problems", "linear homogeneous operator", "Apply the operator to a linear combination.|Linearity distributes and each solution term vanishes."),
    theoremEntry("ode-existence", "Picard-Lindelöf theorem", "Differential Equations", calculus, KnowledgeLevel.PG, TheoremBand.PG, "A locally Lipschitz first-order initial-value problem has a unique local solution.", "ODE existence|uniqueness|numerical methods", "continuous field|local Lipschitz condition", "Convert the ODE to an integral equation.|Picard iteration is a contraction on a small interval."),
    theoremEntry("gronwall", "Grönwall's inequality", "Differential Equations", calculus, KnowledgeLevel.PG, TheoremBand.PG, "An integral inequality u(t)≤A+∫a(s)u(s)ds yields an exponential bound on u.", "stability|uniqueness|error analysis", "non-negative integrable data", "Introduce the accumulated upper bound.|Differentiate after multiplying by an integrating factor."),
    theoremEntry("sturm-liouville", "Sturm-Liouville spectral theorem", "Differential Equations", calculus, KnowledgeLevel.PG, TheoremBand.PG, "A regular self-adjoint Sturm-Liouville problem has real eigenvalues and orthogonal eigenfunctions forming a complete expansion system.", "boundary-value problems|Fourier series|quantum models", "regular self-adjoint problem|separated boundary conditions", "Integration by parts gives reality and orthogonality.|Compact self-adjoint operator theory gives completeness."),
    theoremEntry("stable-manifold-linear", "Hartman-Grobman theorem", "Differential Equations", calculus, KnowledgeLevel.PG, TheoremBand.PG, "Near a hyperbolic equilibrium, a nonlinear dynamical system is topologically conjugate to its linearisation.", "phase portraits|stability|dynamical systems", "hyperbolic equilibrium|continuously differentiable vector field", "Split into stable and unstable linear subspaces.|Construct a local conjugacy by controlled orbit corrections."),

    theoremEntry("bisection-convergence", "Bisection convergence theorem", "Numerical Analysis", calculus, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "If a continuous function changes sign on [a,b], bisection produces a root bracket of width (b-a)/2^n after n steps.", "root finding|guaranteed error|computation", "continuous function|opposite endpoint signs", "The intermediate value theorem preserves a root in one half.|Each iteration halves the bracket."),
    theoremEntry("newton-quadratic", "Local quadratic convergence of Newton's method", "Numerical Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "Near a simple root and under smoothness bounds, Newton errors satisfy |e_(n+1)|≤C|e_n|².", "root finding|fast convergence|nonlinear equations", "simple root|bounded second derivative|initial point sufficiently close", "Apply Taylor's theorem about the current iterate.|Use a lower bound on the derivative."),
    theoremEntry("lagrange-interpolation-error", "Polynomial interpolation error theorem", "Numerical Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "The degree-n interpolation error equals f^(n+1)(ξ)/(n+1)! times the product of (x-x_i).", "interpolation|error bounds|approximation", "n+1 distinct nodes|n+1 derivatives", "Add a multiple of the nodal product so the error also vanishes at x.|Apply Rolle's theorem n+1 times."),
    theoremEntry("trapezoidal-error", "Composite trapezoidal error theorem", "Numerical Analysis", calculus, KnowledgeLevel.UG, TheoremBand.UG, "For twice differentiable f, the composite trapezoidal error is bounded by (b-a)h² max|f''|/12.", "numerical integration|mesh selection|error control", "bounded second derivative|uniform mesh", "Use the local linear-interpolation remainder on each panel.|Integrate and sum the bounds."),
    theoremEntry("lax-equivalence", "Lax equivalence theorem", "Numerical Analysis", calculus, KnowledgeLevel.PG, TheoremBand.PG, "For a well-posed linear initial-value problem, a consistent finite-difference scheme converges exactly when it is stable.", "PDE solvers|stability|convergence", "linear well-posed problem|consistent scheme", "Consistency controls local error and stability propagates it.|Uniform boundedness proves the converse."),
)
