package com.indianservers.aiexplorer.learning

private val probability = KnowledgeTopic.Probability
private val statistics = KnowledgeTopic.Statistics
private val algebraAdvanced = KnowledgeTopic.Algebra
private val calculusAdvanced = KnowledgeTopic.Calculus

internal fun probabilityAndAdvancedTheorems(): List<TheoremCard> = listOf(
    theoremEntry("probability-addition", "Addition theorem of probability", "Probability", probability, KnowledgeLevel.School, TheoremBand.CLASS_6_8, "P(A∪B)=P(A)+P(B)-P(A∩B).", "combined events|Venn diagrams|risk", "events in one probability space", "Adding P(A) and P(B) counts the overlap twice.|Subtract it once."),
    theoremEntry("total-probability", "Law of total probability", "Probability", probability, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "For a partition {B_i}, P(A)=ΣP(A|B_i)P(B_i).", "partitions|diagnosis|Bayes", "B_i form a measurable partition", "Split A into the disjoint events A∩B_i.|Add and use conditional probability."),
    theoremEntry("bayes-rule", "Bayes' theorem", "Probability", probability, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "P(A|B)=P(B|A)P(A)/P(B) whenever P(B)>0.", "conditional probability|diagnosis|inference", "P(B)>0", "Write P(A∩B) in both conditional forms.|Equate and divide by P(B)."),
    theoremEntry("strong-law-large-numbers", "Strong law of large numbers", "Probability", probability, KnowledgeLevel.UG, TheoremBand.UG, "For iid integrable random variables, the sample mean converges almost surely to the expected value.", "simulation|long-run averages|estimation", "iid variables|finite first moment", "Control deviations on a suitable subsequence.|Use truncation and Borel-Cantelli, then fill the gaps."),
    theoremEntry("borel-cantelli", "Borel-Cantelli lemmas", "Probability", probability, KnowledgeLevel.PG, TheoremBand.PG, "If ΣP(A_n)<∞, only finitely many A_n occur almost surely; with independence, divergence implies infinitely many occur almost surely.", "rare events|almost-sure convergence|stochastic processes", "events in one probability space|independence for the converse", "Use the union bound for tail events.|For the converse, multiply independent complement probabilities."),

    theoremEntry("chebyshev", "Chebyshev's inequality", "Statistics", statistics, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "For a variable with mean μ and variance σ², P(|X-μ|≥kσ)≤1/k².", "data spread|quality control|probability bounds", "finite variance|k>0", "Apply Markov's inequality to (X-μ)²."),
    theoremEntry("central-limit", "Central limit theorem", "Statistics", statistics, KnowledgeLevel.UG, TheoremBand.UG, "Standardised sums of iid variables with finite positive variance converge in distribution to the normal law.", "sampling distributions|confidence intervals|normal approximation", "iid samples|finite positive variance", "Expand the characteristic function near zero.|Raise it to the sample size and take the limit."),
    theoremEntry("gauss-markov", "Gauss-Markov theorem", "Statistics", statistics, KnowledgeLevel.UG, TheoremBand.UG, "Under classical linear-model assumptions, ordinary least squares is the best linear unbiased estimator.", "regression|least squares|estimation", "linear model|zero conditional mean|spherical errors", "Write another linear unbiased estimator as OLS plus a residual term.|The extra covariance is positive semidefinite."),
    theoremEntry("factorization-sufficiency", "Fisher-Neyman factorisation theorem", "Statistics", statistics, KnowledgeLevel.PG, TheoremBand.PG, "A statistic T is sufficient exactly when the likelihood factors into a parameter-dependent function of T and a parameter-free function of the data.", "sufficient statistics|likelihood|data reduction", "dominated statistical model", "Factorisation makes the conditional data law parameter-free.|Conversely reconstruct the likelihood from sufficiency."),
    theoremEntry("rao-blackwell", "Rao-Blackwell theorem", "Statistics", statistics, KnowledgeLevel.PG, TheoremBand.PG, "Conditioning an estimator on a sufficient statistic preserves its expectation and cannot increase convex loss, including variance.", "estimator improvement|sufficiency|variance reduction", "integrable estimator|sufficient statistic", "Use iterated expectation.|Apply conditional Jensen's inequality."),

    theoremEntry("induction-principle", "Principle of mathematical induction", "Discrete Mathematics", algebraAdvanced, KnowledgeLevel.School, TheoremBand.CLASS_6_8, "If P(1) holds and P(n) implies P(n+1), then P(n) holds for every positive integer n.", "proof|sequences|divisibility", "base case|inductive step", "Any first failing integer would have a predecessor for which the implication forces success."),
    theoremEntry("de-morgan-sets", "De Morgan's laws", "Discrete Mathematics", algebraAdvanced, KnowledgeLevel.School, TheoremBand.CLASS_6_8, "The complement of a union is the intersection of complements, and the complement of an intersection is the union of complements.", "sets|logic|probability", "sets in a common universe", "Check membership of an arbitrary element using not-or and not-and logic."),
    theoremEntry("cantor-schroeder-bernstein", "Cantor-Schröder-Bernstein theorem", "Discrete Mathematics", algebraAdvanced, KnowledgeLevel.UG, TheoremBand.UG, "If there are injections A→B and B→A, then there is a bijection A↔B.", "cardinality|infinite sets|bijections", "two injections", "Decompose the directed injection graph into chains and cycles.|Choose the appropriate direction on each component."),
    theoremEntry("ramsey", "Ramsey's theorem", "Discrete Mathematics", algebraAdvanced, KnowledgeLevel.UG, TheoremBand.UG, "Every sufficiently large finite colouring contains a prescribed monochromatic complete substructure.", "combinatorics|graph colouring|guaranteed patterns", "finite number of colours and target sizes", "Induct on target sizes.|A vertex has a large same-colour neighbourhood by pigeonhole."),
    theoremEntry("master-theorem", "Master theorem for recurrences", "Discrete Mathematics", algebraAdvanced, KnowledgeLevel.UG, TheoremBand.UG, "The growth of T(n)=aT(n/b)+f(n) is determined by comparing f(n) with n^(log_b a), subject to regularity conditions.", "algorithm analysis|divide and conquer|complexity", "a≥1|b>1|regularity in the dominant case", "Expand the recursion tree.|Compare work across levels and sum the resulting geometric pattern."),

    theoremEntry("jordan-curve", "Jordan curve theorem", "Topology", geometryTopicForAdvanced(), KnowledgeLevel.UG, TheoremBand.UG, "Every simple closed curve in the plane separates it into exactly one bounded inside and one unbounded outside, with the curve as common boundary.", "inside-outside tests|planar topology|geometry", "simple closed planar curve", "Approximate polygonal cases and use topological invariance to pass to general curves."),
    theoremEntry("brouwer-fixed-point", "Brouwer fixed-point theorem", "Topology", geometryTopicForAdvanced(), KnowledgeLevel.UG, TheoremBand.UG, "Every continuous map from a closed ball to itself has a fixed point.", "equilibria|economics|topology", "continuous self-map of a finite-dimensional closed ball", "Assume no fixed point and project each point along its displacement to the boundary.|This would retract the ball onto its sphere, which is impossible."),
    theoremEntry("invariance-domain", "Invariance of domain", "Topology", geometryTopicForAdvanced(), KnowledgeLevel.PG, TheoremBand.PG, "A continuous injective map between open subsets of R^n is open and a homeomorphism onto its image.", "dimension|manifolds|coordinate charts", "continuous injection|same finite dimension", "Reduce locally to a degree-theoretic statement.|Nonzero local degree forces images of neighbourhoods to be open."),
    theoremEntry("urysohn-lemma", "Urysohn's lemma", "Topology", geometryTopicForAdvanced(), KnowledgeLevel.PG, TheoremBand.PG, "In a normal space, disjoint closed sets can be separated by a continuous function taking values 0 and 1.", "separation axioms|continuous functions|metrisation", "normal topological space|disjoint closed sets", "Nest open sets indexed by dyadic rationals.|Define the function from the first index whose closure contains each point."),
    theoremEntry("tychonoff", "Tychonoff's theorem", "Topology", geometryTopicForAdvanced(), KnowledgeLevel.PG, TheoremBand.PG, "Any product of compact topological spaces is compact in the product topology.", "product spaces|functional analysis|compactness", "compact factor spaces|choice principle in full generality", "Use ultrafilters or the finite-intersection property.|Project a filter to every factor and combine the limit coordinates."),

    theoremEntry("weierstrass-optimization", "Weierstrass existence theorem", "Optimization", calculusAdvanced, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "A continuous objective on a nonempty compact feasible set attains a global minimum and maximum.", "global optimization|bounded constraints|existence", "continuous objective|nonempty compact feasible set", "Take an optimizing sequence.|Compactness gives a convergent subsequence and continuity preserves its limiting value."),
    theoremEntry("fermat-stationary", "Fermat's stationary-point theorem", "Optimization", calculusAdvanced, KnowledgeLevel.School, TheoremBand.CLASS_11_12, "If a differentiable function has a local extremum at an interior point, its derivative or gradient is zero there.", "critical points|calculus optimization|necessary conditions", "differentiable objective|interior local extremum", "Directional one-variable restrictions have an extremum at zero.|Their derivatives vanish in every direction."),
    theoremEntry("lagrange-multipliers", "Lagrange multiplier theorem", "Optimization", calculusAdvanced, KnowledgeLevel.UG, TheoremBand.UG, "At a regular constrained local extremum, the objective gradient lies in the span of active constraint gradients.", "constrained optimization|economics|geometry", "differentiable functions|independent constraint gradients", "Feasible tangent directions annihilate the constraint gradients.|The objective gradient annihilates the same tangent space."),
    theoremEntry("kkt", "Karush-Kuhn-Tucker theorem", "Optimization", calculusAdvanced, KnowledgeLevel.PG, TheoremBand.PG, "Under a constraint qualification, a local constrained optimum satisfies stationarity, primal feasibility, dual feasibility, and complementary slackness.", "nonlinear programming|inequality constraints|duality", "differentiable problem|constraint qualification", "Separate feasible descent directions from the linearised constraint cone.|The separating multipliers yield the KKT conditions."),
    theoremEntry("convex-strong-duality", "Strong duality for convex programs", "Optimization", calculusAdvanced, KnowledgeLevel.PG, TheoremBand.PG, "For a convex problem satisfying Slater's condition, the primal and dual optimal values agree and dual optima are attained under standard finiteness assumptions.", "convex optimization|certificates|resource allocation", "convex objective and constraints|Slater condition", "Separate the convex attainable epigraph from values below the optimum.|The separating hyperplane supplies optimal multipliers."),
)

private fun geometryTopicForAdvanced() = KnowledgeTopic.Geometry
