package com.indianservers.aiexplorer.learning

private val school = KnowledgeLevel.School
private val algebraTopic = KnowledgeTopic.Algebra
private val geometryTopic = KnowledgeTopic.Geometry

internal fun schoolAndGeometryTheorems(): List<TheoremCard> = listOf(
    theoremEntry("division-algorithm", "Division algorithm", "Foundations & Arithmetic", algebraTopic, school, TheoremBand.CLASS_6_8, "For integers a and positive b, there are unique integers q,r with a=bq+r and 0≤r<b.", "division|remainders|place value", "b>0", "Choose the greatest multiple bq≤a.|Uniqueness follows because two allowed remainders differ by less than b."),
    theoremEntry("fundamental-arithmetic", "Fundamental theorem of arithmetic", "Foundations & Arithmetic", algebraTopic, school, TheoremBand.CLASS_6_8, "Every integer greater than 1 has a prime factorisation unique up to order.", "prime factors|HCF and LCM|fractions", "integer greater than 1", "Repeatedly divide by a prime factor.|Euclid's lemma proves uniqueness."),
    theoremEntry("euclidean-algorithm", "Euclidean algorithm theorem", "Foundations & Arithmetic", algebraTopic, school, TheoremBand.CLASS_6_8, "Replacing (a,b) by (b,a mod b) preserves their greatest common divisor.", "HCF|fractions|Diophantine equations", "a,b are not both zero", "Common divisors of a and b are exactly common divisors of b and a-qb.|Iterate until the remainder is zero."),
    theoremEntry("sqrt2-irrational", "Irrationality of √2", "Foundations & Arithmetic", algebraTopic, school, TheoremBand.CLASS_9_10, "The number √2 cannot be expressed as a ratio of integers.", "irrational numbers|proof by contradiction|number systems", "fraction assumed in lowest terms", "Assume √2=p/q.|Then p² is even, so p is even; the same argument makes q even, contradicting lowest terms."),
    theoremEntry("binomial-theorem", "Binomial theorem", "Foundations & Arithmetic", algebraTopic, school, TheoremBand.CLASS_11_12, "(x+y)^n=Σ C(n,k)x^(n-k)y^k for every non-negative integer n.", "expansion|combinations|probability", "n is a non-negative integer", "Choose which k of the n factors contribute y.|There are C(n,k) identical terms."),

    theoremEntry("remainder", "Remainder theorem", "Algebra", algebraTopic, school, TheoremBand.CLASS_9_10, "The remainder when p(x) is divided by x-a is p(a).", "polynomial division|evaluation|roots", "p is a polynomial", "Write p(x)=(x-a)q(x)+r.|Set x=a."),
    theoremEntry("factor", "Factor theorem", "Algebra", algebraTopic, school, TheoremBand.CLASS_9_10, "For a polynomial p(x), x-a is a factor exactly when p(a)=0.", "factorisation|roots|polynomials", "p is a polynomial", "Apply the remainder theorem.|A zero remainder is equivalent to exact divisibility."),
    theoremEntry("vieta-quadratic", "Vieta's formulas for a quadratic", "Algebra", algebraTopic, school, TheoremBand.CLASS_9_10, "If ax²+bx+c has roots α,β, then α+β=-b/a and αβ=c/a.", "quadratic equations|root relations|factorisation", "a≠0", "Write a(x-α)(x-β).|Compare coefficients."),
    theoremEntry("rational-root", "Rational root theorem", "Algebra", algebraTopic, school, TheoremBand.CLASS_11_12, "For an integer polynomial, a reduced rational root p/q has p dividing the constant term and q dividing the leading coefficient.", "polynomial roots|factorisation|candidate testing", "integer coefficients|gcd(p,q)=1", "Substitute p/q and clear denominators.|Use coprimality to obtain both divisibility claims."),
    theoremEntry("fundamental-algebra", "Fundamental theorem of algebra", "Algebra", algebraTopic, KnowledgeLevel.UG, TheoremBand.UG, "Every non-constant complex polynomial has a complex root and factors completely over C.", "complex roots|factorisation|polynomials", "complex polynomial of positive degree", "Use a minimum-modulus or Liouville argument to obtain one root.|Divide out linear factors inductively."),

    theoremEntry("triangle-angle-sum-theorem", "Triangle angle-sum theorem", "Plane Geometry", geometryTopic, school, TheoremBand.CLASS_6_8, "The interior angles of a Euclidean triangle sum to 180°.", "triangles|angle finding|polygons", "Euclidean plane", "Draw a line through one vertex parallel to the opposite side.|Use alternate interior angles on a straight line."),
    theoremEntry("exterior-angle-theorem", "Exterior angle theorem", "Plane Geometry", geometryTopic, school, TheoremBand.CLASS_6_8, "A triangle's exterior angle equals the sum of its two remote interior angles.", "triangles|parallel lines|angle finding", "one side is extended", "Combine the triangle angle sum with the linear-pair angle."),
    theoremEntry("sas-congruence", "SAS congruence theorem", "Plane Geometry", geometryTopic, school, TheoremBand.CLASS_6_8, "Two triangles with two corresponding sides and the included angle equal are congruent.", "congruence|construction|rigidity", "included angles correspond", "Place one triangle on the other.|The fixed sides and included angle force the third vertices to coincide."),
    theoremEntry("pythagoras", "Pythagorean theorem", "Plane Geometry", geometryTopic, school, TheoremBand.CLASS_9_10, "In a right triangle with legs a,b and hypotenuse c, a²+b²=c².", "distance|area|right triangles", "right triangle|Euclidean plane", "Arrange four congruent triangles inside a square.|Compare the two expressions for the remaining area."),
    theoremEntry("circle-angle", "Inscribed angle theorem", "Plane Geometry", geometryTopic, school, TheoremBand.CLASS_9_10, "An angle at a circle's circumference is half the central angle subtending the same arc.", "circles|angles|cyclic quadrilaterals", "angles subtend the same arc", "Join the centre to the chord endpoints.|Use isosceles-triangle angle relations."),

    theoremEntry("distance-formula", "Distance formula", "Coordinate Geometry", geometryTopic, school, TheoremBand.CLASS_9_10, "The distance between (x₁,y₁) and (x₂,y₂) is √((x₂-x₁)²+(y₂-y₁)²).", "coordinates|distance|length", "Cartesian plane", "Horizontal and vertical differences form a right triangle.|Apply Pythagoras."),
    theoremEntry("midpoint-theorem-coordinate", "Coordinate midpoint theorem", "Coordinate Geometry", geometryTopic, school, TheoremBand.CLASS_9_10, "The midpoint of (x₁,y₁) and (x₂,y₂) is ((x₁+x₂)/2,(y₁+y₂)/2).", "midpoints|segments|coordinates", "Cartesian plane", "A midpoint averages equal directed changes in each coordinate."),
    theoremEntry("section-formula", "Internal section formula", "Coordinate Geometry", geometryTopic, school, TheoremBand.CLASS_9_10, "A point dividing AB internally in ratio m:n has coordinates ((nx₁+mx₂)/(m+n),(ny₁+my₂)/(m+n)).", "ratio|coordinates|barycentric combinations", "m,n>0", "Write the point as A plus m/(m+n) of the displacement B-A.|Simplify each coordinate."),
    theoremEntry("parallel-slope", "Parallel and perpendicular slope theorem", "Coordinate Geometry", geometryTopic, school, TheoremBand.CLASS_9_10, "Non-vertical parallel lines have equal slopes; perpendicular non-vertical lines have slope product -1.", "straight lines|parallelism|perpendicularity", "relevant slopes are defined", "Compare direction vectors.|A zero dot product gives m₁m₂=-1."),
    theoremEntry("shoelace", "Shoelace theorem", "Coordinate Geometry", geometryTopic, KnowledgeLevel.UG, TheoremBand.UG, "A simple polygon's signed area is half the alternating sum of adjacent coordinate products.", "polygon area|coordinates|determinants", "vertices are cyclically ordered", "Split into oriented triangles.|Sum determinant areas and cancel internal contributions."),

    theoremEntry("pythagorean-identity", "Pythagorean trigonometric identity", "Trigonometry", geometryTopic, school, TheoremBand.CLASS_9_10, "For every angle θ, sin²θ+cos²θ=1.", "identities|unit circle|equations", "real angle θ", "The point (cosθ,sinθ) lies on the unit circle x²+y²=1."),
    theoremEntry("sine-law", "Law of sines", "Trigonometry", geometryTopic, school, TheoremBand.CLASS_11_12, "For any triangle, a/sin A=b/sin B=c/sin C=2R.", "triangles|circumradius|unknown sides", "non-degenerate triangle", "Express a common altitude using two side-angle pairs.|Use the circumcircle for the 2R form."),
    theoremEntry("cosine-law", "Law of cosines", "Trigonometry", geometryTopic, school, TheoremBand.CLASS_11_12, "For any triangle, c²=a²+b²-2ab cos C.", "triangles|distance|unknown angles", "non-degenerate triangle", "Resolve a side into components.|Apply Pythagoras and simplify."),
    theoremEntry("triangle-area-sine", "Triangle sine-area theorem", "Trigonometry", geometryTopic, school, TheoremBand.CLASS_11_12, "A triangle with adjacent sides a,b and included angle C has area ½ab sin C.", "triangle area|surveying|vectors", "non-degenerate triangle", "Use b sin C as the altitude to base a."),
    theoremEntry("de-moivre", "De Moivre's theorem", "Trigonometry", algebraTopic, KnowledgeLevel.UG, TheoremBand.UG, "(cosθ+i sinθ)^n=cos(nθ)+i sin(nθ) for every integer n.", "multiple angles|complex roots|trigonometric identities", "integer n", "Use Euler's formula or induction and angle-addition identities."),
)
