from pathlib import Path
import math,json,re
out=Path('app/src/test/java/com/indianservers/aiexplorer')
cases=[]
def add(dim,kind,source,expected=0.0,x=.5,y=-.5,z=0.0):
    cases.append(dict(dim=dim,kind=kind,source=source,expected=expected,x=x,y=y,z=z))
for n in range(1,11):
    forms=[(f'y={n}*x+1',n*.5+1),(f'y=x^2+{n}',.25+n),(f'y=x^3-{n}*x',.125-n*.5),(f'y=sin(x)+{n}',math.sin(.5)+n),(f'y=cos(x)*{n}',math.cos(.5)*n),(f'y=sqrt(x^2+{n})',math.sqrt(.25+n)),(f'y=abs(x-{n})',n-.5),(f'y=exp(x)/{n}',math.exp(.5)/n),(f'y=ln(x^2+{n})',math.log(.25+n))]
    for src,expect in forms:add(2,'explicit',src,expect)
for n in range(1,11):
    add(2,'implicit',f'x^2+y^2={n}',x=math.sqrt(n),y=0)
    add(2,'implicit',f'y=x+y^2-{n}',x=n,y=0)
    add(2,'polar',f'r={n}+cos(theta)',n+1,x=0,y=0)
    add(2,'parametric',f'x(t)={n}*cos(t);y(t)={n}*sin(t)',n,x=0,y=0)
    add(2,'inequality',f'y<=x^2+{n}')
for src in ['y=','y=sin(','y=1+','x^2+=1','y=sqrt()','y=cos(x))','y=2**x','y=1/','y=ln()','y=(x+1']:
    add(2,'invalid',src)
for n in range(1,11):
    x=.5;y=-.5
    forms=[(f'z={n}*x+y',n*x+y),(f'z=x^2+y^2+{n}',.5+n),(f'z=x^2-y^2+{n}',n),(f'z=x^3+y^3+{n}',n),(f'z=sin(x)+cos(y)+{n}',math.sin(x)+math.cos(y)+n),(f'z=sin(x*y)*{n}',math.sin(x*y)*n),(f'z=sqrt(x^2+y^2+{n})',math.sqrt(.5+n)),(f'z=exp(-x^2-y^2)*{n}',math.exp(-.5)*n),(f'z=ln(x^2+y^2+{n})',math.log(.5+n)),(f'z=abs(x)+abs(y)+{n}',1+n),(f'z=(x+y+{n})/(1+x^2+y^2)',n/1.5)]
    for src,expect in forms:add(3,'explicit',src,expect)
for n in range(1,11):
    r=1+n/10
    add(3,'implicit',f'x^2+y^2+z^2={r*r:.2f}',x=r,y=0,z=0)
    add(3,'implicit',f'z=x^2+y^2+z^2-{n}',x=math.sqrt(n),y=0,z=0)
    add(3,'parametric',f'x=u;y=v;z={n}*u*v',expected=-n*.25)
for src in ['z=','z=sin(','z=1+','x^2+y^2+=1','z=sqrt()','z=cos(x))','z=2**x','x=u;x=v;y=u;z=v','x=u;y=v','z=ln()']:
    add(3,'invalid',src)
assert sum(c['dim']==2 for c in cases)==150
assert sum(c['dim']==3 for c in cases)==150
lines=['package com.indianservers.aiexplorer','', '// Generated by scripts/generate_math_keyboard_graph_cases.py; expected numbers use Python math, independently of the app.', 'data class KeyboardGraphCase(val id: String, val dimension: Int, val kind: String, val source: String, val expected: Double, val x: Double, val y: Double, val z: Double)', '', 'object KeyboardGraphCases {','    val all = listOf(']
manual=['MATH KEYBOARD GRAPH MANUAL CHECKLIST','300 cases: 150 for 2D and 150 for 3D.','Status: automated keyboard-action replay; physical phone execution NOT performed.','For each case: open the indicated graph workspace; clear the input; use only MathKeyboard; press Done/Add.','Digits and operators: tap the matching keys. Powers ^2/^3: long-press 2/3.','Functions: choose the function key, fill its argument, then use the right-arrow to leave the template.','Use abc for letters and semicolon; sym for <=. For sqrt, hold x² on Math+ and select √x. Invalid cases must show an error and keep the app responsive.','At each valid case: inspect the plot, pan/zoom, edit one digit, undo, and re-add. Confirm native keyboard stays hidden.','For explicit cases verify the trace/surface coordinate below. Implicit cases list a point on the relation.','Record physical-device PASS/FAIL, device model, Android version, and any crash separately.','']
def keyboard_steps(source):
    steps=[]; stack=[]; i=0
    while i<len(source):
        ch=source[i]
        if ch=='^' and i+1<len(source) and source[i+1].isdigit():
            steps.append('HOLD '+source[i+1]); i+=2; continue
        match=re.match(r'(sin|cos|sqrt|abs|exp|ln)\(',source[i:])
        if match:
            steps.append('TAP '+match[1]+' template');stack.append(True);i+=len(match[0]);continue
        if ch==')' and stack and stack[-1]:
            steps.append('TAP right arrow');stack.pop();i+=1;continue
        token='<=' if source[i:i+2]=='<=' else ch
        steps.append('TAP '+token)
        if ch=='(':stack.append(False)
        if ch==')' and stack:stack.pop()
        i+=len(token)
    return ' -> '.join(steps)+' -> TAP Done/Add'

counts={2:0,3:0}
for c in cases:
    counts[c['dim']]+=1;c['id']=f"{c['dim']}D-{counts[c['dim']]:03}"
    args=[json.dumps(c['id']),str(c['dim']),json.dumps(c['kind']),json.dumps(c['source']),repr(float(c['expected'])),repr(float(c['x'])),repr(float(c['y'])),repr(float(c['z']))]
    lines.append('        KeyboardGraphCase('+', '.join(args)+'),')
    expectation='Show validation error; no crash' if c['kind']=='invalid' else f"{c['kind']}: x={c['x']}, y={c['y']}, z={c['z']}; expected value={c['expected']}"
    if c['kind'] in ('polar','parametric') and c['dim']==2:
        expectation=f"At parameter 0: point ({c['expected']}, 0); visible curve"
    elif c['kind']=='parametric' and c['dim']==3:
        expectation=f"At u={c['x']}, v={c['y']}: point ({c['x']}, {c['y']}, {c['expected']}); visible surface"
    elif c['kind']=='inequality':
        expectation='Shade the region below and including the parabola; show its boundary; no crash'
    manual.extend([f"{c['id']} | {c['source']}",f"Keys: {keyboard_steps(c['source'])}",f"Expected: {expectation}",'Physical device result: NOT RUN',''])
lines.extend(['    )','}'])
(out/'KeyboardGraphCases.kt').write_text('\n'.join(lines)+'\n',encoding='utf-8')
Path('docs/qa/math-keyboard-300-manual-cases.txt').write_text('\n'.join(manual),encoding='utf-8')
