package com.indianservers.aiexplorer.learningintelligence.learner

import com.indianservers.aiexplorer.learningintelligence.engine.*
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.reference.LearningIntelligenceCatalog
import com.indianservers.aiexplorer.learningintelligence.repository.InMemoryLearningIntelligenceRepository
import java.time.Instant

class LocalLearningIntelligenceService(
 val repository:InMemoryLearningIntelligenceRepository=InMemoryLearningIntelligenceRepository(LearningIntelligenceCatalog.graph,LearningIntelligenceCatalog.misconceptions,LearningIntelligenceCatalog.hints),
 private val mastery:MasteryEngine=DeterministicMasteryEngine(),private val misconception:MisconceptionEngine=DeterministicMisconceptionEngine(),private val hintSelector:HintSelectionEngine=DeterministicHintSelectionEngine(),private val reviewEngine:SpacedReviewEngine=DeterministicSpacedReviewEngine(),private val next:NextLessonEngine=DeterministicNextLessonEngine()
){
 private val graphIndex=KnowledgeGraphIndex(repository.graph())
 init{LearningIntelligenceCatalog.concepts.forEach{c->if(repository.get(c.conceptId)==null)repository.save(LearnerConceptState(c.conceptId,setOf(c.curriculumNodeId),c.subject))}}
 fun state(conceptId:String)=repository.get(conceptId)?:error("Unknown concept $conceptId")
 fun emit(event:LearnerEvent):LearnerConceptState{val policy=LearningIntelligenceCatalog.policies[event.conceptId]?:error("Missing policy ${event.conceptId}");val before=state(event.conceptId);var after=mastery.process(before,event,policy);after.masteryEvidence.drop(before.masteryEvidence.size).forEach(repository::appendMastery);if(event is LearnerEvent.PracticeAnswered&&!event.result.valid){val added=event.result.misconceptionCandidateIds.map{id->MisconceptionEvidence(id,event.conceptId,event.questionId,if(event.confidence==LearnerConfidence.VERY_SURE)1.25 else .7,event.confidence,event.occurredAt)};added.forEach(repository::appendMisconception);after=after.copy(misconceptionEvidence=after.misconceptionEvidence+added)};repository.save(after);if(event is LearnerEvent.ReviewCompleted){val scheduled=reviewEngine.schedule(after,event.occurredAt,event.correct,event.independence==EvidenceIndependence.INDEPENDENT,!event.correct&&event.confidence==LearnerConfidence.VERY_SURE);repository.save(scheduled);repository.save(after.copy(nextReviewAt=scheduled.scheduledAt,retentionState=after.retentionState.copy(intervalDays=java.time.Duration.between(event.occurredAt,scheduled.scheduledAt).toDays().toInt())))};return repository.get(event.conceptId)!!}
 fun hint(conceptId:String,failedAttempts:Int):HintSelection?{val assessments=repository.definitions(conceptId).map{misconception.assess(it,repository.misconceptionEvidence(conceptId))};val selected=hintSelector.select(repository.hints(conceptId),state(conceptId),failedAttempts,assessments,repository.used(conceptId))?:return null;repository.recordSelection(conceptId,selected.hint.id);emit(LearnerEvent.HintRequested(conceptId,selected.hint.id,selected.hint.level,Instant.now()));return selected}
 fun recordError(conceptId:String,curriculumNodeId:String,questionId:String?,answer:String,steps:List<LearnerAnswerStep>,result:ValidationResult,confidence:LearnerConfidence?,corrected:List<String>,remediationActivityId:String?,now:Instant=Instant.now()):ErrorBookEntry{require(!result.valid&&result.errorType!=null);val misconceptionId=result.misconceptionCandidateIds.firstOrNull();val entry=ErrorBookEntry("error-$conceptId-${now.toEpochMilli()}",conceptId,curriculumNodeId,questionId,answer,steps,result.firstInvalidStepIndex,result.errorType,misconceptionId,confidence,state(conceptId).hintUsage.maximumLevel,corrected,remediationActivityId,now.plusSeconds(86_400),ErrorBookStatus.RETRY_SCHEDULED);repository.save(entry);return entry}
 fun resolveError(id:String):ErrorBookEntry{val old=repository.entry(id)?:error("Unknown error $id");val updated=old.copy(status=ErrorBookStatus.RESOLVED,retryAt=null);repository.save(updated);return updated}
 fun recommend(timeMinutes:Int=10,recentActivityIds:List<String> = emptyList(),now:Instant=Instant.now()):LearningRecommendation?{val r=next.recommend(repository.all().associateBy{it.conceptId},graphIndex,LearningIntelligenceCatalog.activities,timeMinutes,recentActivityIds,now);repository.replace(listOfNotNull(r));return r}
}
