package com.indianservers.aiexplorer.physics.ncert.intelligence
import com.indianservers.aiexplorer.curriculum.*
import com.indianservers.aiexplorer.learningintelligence.model.*
import com.indianservers.aiexplorer.learningintelligence.reference.*
object PhysicsLearningIntelligence{
 private val s=SchoolSubject.PHYSICS;private val levels=setOf(SchoolClassLevel.CLASS_8,SchoolClassLevel.CLASS_9,SchoolClassLevel.CLASS_11)
 private fun node(vararg k:String)=ReferenceCurriculumResolver.topic(s,*k)
 val concepts=listOf(
  ReferenceConceptFactory.create("physics-distance-displacement",node("Motion"),s,levels,emptyList(),"physics-motion-graphs","ideal free fall","physics-heavy-falls-faster","Heavier objects fall faster in ideal free fall","With air resistance neglected, all bodies at one location have the same gravitational acceleration.","Equal gravitational acceleration gives equal ideal fall time.","Greater mass creates greater ideal acceleration.",DiagnosticQuestionKind.REASONING,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.DATA_INTERPRETATION)),
  ReferenceConceptFactory.create("physics-velocity-acceleration",node("Motion"),s,levels,listOf("physics-distance-displacement"),"physics-motion-graphs","position-time interpretation","physics-flat-position-speed","A flat position-time graph means constant non-zero speed","Constant position has zero slope and therefore zero velocity.","A horizontal position-time line represents rest.","A horizontal position-time line represents steady non-zero motion.",DiagnosticQuestionKind.VISUAL,setOf(MasteryEvidenceType.DATA_INTERPRETATION,MasteryEvidenceType.NUMERICAL_PROBLEM)),
  ReferenceConceptFactory.create("physics-newton-second-law",node("Force","Laws of Motion"),s,levels,listOf("physics-velocity-acceleration"),"physics-newton-second-law","force and velocity","physics-force-maintains-velocity","Continuous force is needed to maintain constant velocity","Net force changes velocity; zero net force permits constant velocity.","A net force is required for acceleration.","A forward force is always required for forward velocity.",DiagnosticQuestionKind.CONCEPT,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.NUMERICAL_PROBLEM,MasteryEvidenceType.SIMULATION_PREDICTION)),
  ReferenceConceptFactory.create("physics-wave-speed",node("Wave","Sound"),s,levels,listOf("physics-velocity-acceleration"),"physics-wave-speed","wave transport","physics-particles-travel","Wave particles move from source to destination","Particles oscillate locally while energy and the disturbance propagate.","Medium particles oscillate about equilibrium.","A marked particle travels with the wave to the receiver.",DiagnosticQuestionKind.VISUAL,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.SIMULATION_PREDICTION)),
  ReferenceConceptFactory.create("physics-electric-circuits",node("Electric"),s,levels,emptyList(),"physics-electric-circuits","circuit current","physics-current-consumed","Current is consumed by a resistor","Charge flow is continuous in a steady series circuit; energy is transferred in components.","Series current is the same before and after a resistor.","Less current leaves a resistor because it was used up.",DiagnosticQuestionKind.PREREQUISITE_DISCRIMINATION,setOf(MasteryEvidenceType.CONCEPT_QUESTION,MasteryEvidenceType.NUMERICAL_PROBLEM,MasteryEvidenceType.SIMULATION_PREDICTION))
 )
}
